### ISSUE TITLE
Error while unpacking - https://dpaste.de/VwrV

### ISSUE THREAD

**Issue by baptistapedro** [sensepost/objection#100]
Not sure how to solve out this issue.

https://dpaste.de/VwrV

Thoughts?

**Comment by leonjza** [comment]
Unfortunately, Windows support is a little the flaky. The only thing I can suggest is playing with the `--skip-resources` / `-D` flag to see if make any further progress, or try it on a Linux VM with the latest `apktool` available.

**Comment by leonjza** [comment]
Similar to #68
