### ISSUE TITLE
iOS SSL pinning bypass ineffective on iOS 11.2.6

### ISSUE THREAD

**Issue by systocrat** [sensepost/objection#102]
With the new jailbreak for iOS 11.2.*-11.3.1 by Coolstar, objection's SSL certificate pinning bypass is nonfunctional.

I'm not an iOS developer at all, I don't have a Mac, but if someone wants to point me in the right direction for solving this myself and submitting a patch, I'd really appreciate it. 

I can also provide access to my device for testing, provided all experimentation is done in a shared tmux session.

iOS version: 11.2.6
iPhone model: 5s

**Comment by leonjza** [comment]
Do you perhaps have some more details about what exactly does not work? Things like how its implemented in the application you are testing and which hook you think fails would be helpful! SSL pinning is tricky as there are many ways in which a developer could have implemented the pinning. I am not 100% sure its specifically related to a major iOS version either, other than the iOS 10 specific `tls_helper_create_peer_trust_export` type bypass we have.

Generally, its a good idea to reverse engineer the target app if the default bypasses don't give you joy to see how its implemented.

The hooks packaged with objection for the purpose of SSL pinning bypasses can be found [here](https://github.com/sensepost/objection/blob/master/objection/hooks/ios/pinning/disable.js). It is definitely not an exhaustive list, but covers many cases. I have not had problems with SSL pinning bypasses on iOS 11 yet either, but my sample set might just not include the case you are facing now.

**Comment by systocrat** [comment]
Can you give me an example application that works for you that I can test on my own?
It's true that I might have been wrong about whether or not the bypass is working, as I tested on two apps that may or may not take unpatched approaches.

I'm very new to the iOS reversing scene, so I definitely didn't take as many steps as I could have due to lack of knowledge of the ecosystem.

**Comment by leonjza** [comment]
Unfortunately I don't have applications I can share, but one example in a private test app I have implements [`URLSession:task:didReceiveChallenge:completionHandler:`](https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1411595-urlsession) as:

```objc
- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential *))completionHandler {
    
    SecTrustRef serverTrust = challenge.protectionSpace.serverTrust;
    SecCertificateRef certificate = SecTrustGetCertificateAtIndex(serverTrust, 0);
    NSData *remoteCertificateData = CFBridgingRelease(SecCertificateCopyData(certificate));
    NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"domain.com" ofType:@"der"];
    NSData *localCertData = [NSData dataWithContentsOfFile:cerPath];
    
    if ([remoteCertificateData isEqualToData:localCertData]) {

        NSURLCredential *credential = [NSURLCredential credentialForTrust:serverTrust];
        [[challenge sender] useCredential:credential forAuthenticationChallenge:challenge];
        completionHandler(NSURLSessionAuthChallengeUseCredential, credential);
    
    } else {
        
        [[challenge sender] cancelAuthenticationChallenge:challenge];
        completionHandler(NSURLSessionAuthChallengeCancelAuthenticationChallenge, nil);
    }
}
```

Bypassing this one example (of many) definitely still works even in iOS 11.41.

**Comment by systocrat** [comment]
Alrighty, I'm going to close this and come back if/when I find something more concrete. Thank you for your patience.
