### ISSUE TITLE
Error to dump all memory

### ISSUE THREAD

**Issue by georgepetz** [sensepost/objection#104]
Hi,

When I tried to dump all memory the follow error was displayed:

..[app] on (iPhone: 9.3.1) [usb] # memory dump all .
Destination file . already exists
Continue append? [y/N]: y
An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: 'Session' object has no attribute 'enumerate_ranges'

Could someone help me?

**Comment by georgepetz** [comment]
It's sounds like a problem with frida, but I couldn't solve that by myself.

The version of frida and frida-server is 12.0.3

**Comment by leonjza** [comment]
Thanks for the report. The convenience / bridging methods like `enumerate_ranges` were dropped in Frida 12, and as a result are causing some issues with objection that made use of them. I am working to re-add the stuff that is used in objection as soon as possible.

**Comment by georgepetz** [comment]
Thanks for reply Leon!

I'm anxious to use the objection!

**Comment by leonjza** [comment]
Just realeased v1.4.1 which should now be compatible with Frida 12 for memory dumping again.
