### ISSUE TITLE
Wiki Issue - Missing 7zip dependency

### ISSUE THREAD

**Issue by decidedlygray** [sensepost/objection#113]
In the wiki here: https://github.com/sensepost/objection/wiki/Patching-iOS-Applications#patching---dependencies

A suggestion to `brew install p7zip` should be added. Otherwise signing a new IPA fails with an error code like:

```
Codesigning patched IPA...
{ Error: not found: 7z
    at getNotFoundError (/usr/local/lib/node_modules/applesign/node_modules/which/which.js:13:12)
    ...
```

I know technically this is an applesign issue, which is a different project. Close this ticket if this is a `#wontfix` kind of problem

DG

**Comment by leonjza** [comment]
Added! Thanks!
