### ISSUE TITLE
Touch ID Bypass

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#118]
Hi,

Right now if we want to bypass the touch id for that we have to execute cmd ios ui touchid_bypass before App asked for Give Thumb.

Is there any way to execute **ios ui touchid_bypass** cmd when app ask and then execute **ios ui touchid_bypass** this cmd for yes 

if will execute then it will fail the bypass

Thanks 
Bikee

**Comment by leonjza** [comment]
It is only possible to override the call for TouchID local authentication to [true](https://github.com/sensepost/objection/blob/master/objection/hooks/ios/ui/touchid.js#L61) at the moment. Will keep this open to include the ability to control the desired status.
