### ISSUE TITLE
App Crashing on Startup

### ISSUE THREAD

**Issue by yausername** [sensepost/objection#119]
`E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libnative-lib.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"`

Command used to patch apk
`objection patchapk -D -s app.apk`

**Comment by yausername** [comment]
https://developer.android.com/about/versions/nougat/android-7.0-changes#ndk-errors

**Comment by yausername** [comment]
I got it to work by passing arch in command
`objection patchapk -a armeabi-v7a -D -s app.apk`

**Comment by leonjza** [comment]
Thanks for the report. Did the patching complain about not being able to detect the attached devices architecture by any change?

**Comment by yausername** [comment]
Hi,
Thanks for replying.
It was able to detect the architecture as `arm64-v8a`.
But the apk was crashing with this architecture. So I tried with `armeabi-v7a`
