### ISSUE TITLE
Argument for TouchID

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#121]
What are the argument can be pass to touchid

as you can see that when i try to list jobs there is one column  Arguments and no any argument is showing

can be pass any argument here

com.test.touchid on (iPhone: 11.4.1) [usb] # jobs list
UUID                                  Name            Started              **Arguments
-**-----------------------------------  --------------  -------------------  -----------
0c238d4c-059d-47f3-82c1-db3bf78a3932  touchid-bypass  2018-08-14 18:46:53  **n/a**
5fb24352-af77-4a84-84b2-a9e9fda7efaf  touchid-bypass  2018-08-14 18:48:29  **n/a**

**Comment by leonjza** [comment]
This command takes no arguments. All commands have a [help file](https://github.com/sensepost/objection/blob/master/objection/console/helpfiles/ios.ui.touchid_bypass.txt) which can be accessed by prefixing a command with `help`. ie: 

`help ios ui touchid_bypass`.
