### ISSUE TITLE
Objection explore frida.Protocol error

### ISSUE THREAD

**Issue by aaisha79** [sensepost/objection#123]
I have just patched an IPA and I'm trying to run it using objection explore, however I got the following error:

frida.ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use

I have done a pip install frida --upgrade but still facing the same error any ideas?

**Comment by aaisha79** [comment]
Hi @leonjza 

Thanks for the response, I have frida client version 12.0.8 & Python version 3.6.5.... I am downloading v11 of fridgadget on a internet connected Mac...

**Comment by leonjza** [comment]
You will need version 12 of the Gadget.
