### ISSUE TITLE
While using Touch ID Bypass

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#125]
While using touch id Bypass we have observed that 

if TouchID Pop is already requested then that time if i executed touch id bypass cmd then it say fail in i want to bypass.

Means if i want to bypass touch id for that i have to execute touch id bypass cmd before touch id is being ask for show  Touch ID. 

Is there any way if  pop is already there and then if execute cmd for TouchID bypass cmd for pass or for fail no need to execute  any cmd

Thanks

**Comment by leonjza** [comment]
Unfortunately I don't have hooks that scan the heap for active instances at the moment no. Pull requests welcome.
