### ISSUE TITLE
Frida 12.1.0 for iOS breaks "String(some_nsobject)"

### ISSUE THREAD

**Issue by pachoo** [sensepost/objection#127]
I noticed that with Frida 12.1.0 that `objection explore` blows up with a message `[hook failure] cannot string coerce Symbol`.  

this is happening in `objection/hooks/ios/device-information.js` where the lines constructing a String from an NSObjecty thing no longer work.
```
            data: {
                applicationName: String(NSBundle.mainBundle().objectForInfoDictionaryKey_('CFBundleIdentifier')),
                deviceName: String(UIDevice.currentDevice().name()),
                systemName: String(UIDevice.currentDevice().systemName()),
                model: String(UIDevice.currentDevice().model()),
                systemVersion: String(UIDevice.currentDevice().systemVersion()),
                identifierForVendor: String(UIDevice.currentDevice().identifierForVendor())
            }
```

Switching to using `.toString()` instead seems to fix the issue.

I don't know if this behavioral change in Frida 12.1.0 was intentional or not, but there should be no issue changing these.

**Comment by leonjza** [comment]
Oh snap thanks for the report! Will make some time today to quickly test this one out and push a fix.

**Comment by leonjza** [comment]
Should be fixed in v1.4.2. `pip3 install --upgrade objection` to get it!

**Comment by pachoo** [comment]
@leonjza thanks!  Next time I'll fork and actually submit a PR :)

**Comment by sushi2k** [comment]
Awesome. Thanks @leonjza! Was just running in this issue and you already fixed it 👍
