### ISSUE TITLE
Frida 12.1.0:  cwd.js "hook failure coerce" issue

### ISSUE THREAD

**Issue by pachoo** [sensepost/objection#129]
Related to Issue #127 , I completely missed that the `objection/hooks/ios/filesystem/pwd.js`  has the same "String()" issue leading to a "[hook failure] cannot string coerce Symbol".  Apologies!

**Comment by leonjza** [comment]
Fixed in 1.4.3.

**Comment by leonjza** [comment]
More cases of these types of exceptions have creeped up today which seem to related to the Duktape upgrade in Frida 12.1 and the usage of `Boolean()` in the file system listing module. Going to reopen this one and recommend using the latest 12.0 gadget which is version 12.0.8 for now.

**Comment by leonjza** [comment]
![image](https://user-images.githubusercontent.com/1148127/44802078-0ec7a880-abbb-11e8-9688-c2339be2b785.png)

Small test case of the current error's using Frida 12.1. 12.0.8 work fine.

**Comment by leonjza** [comment]
Fixed in Frida 12.1.1! Just update the gadget/frida-server and the python frida lib!
