### ISSUE TITLE
Location of objection hook

### ISSUE THREAD

**Issue by bikeenld** [sensepost/objection#130]
Hi 

After installation of objection explorer 

in which directory all the hook get placed 

Thanks
Bikee

**Comment by leonjza** [comment]
Depending on how you install, all hooks live in [this directory](https://github.com/sensepost/objection/tree/master/objection/hooks) on your filesystem. In a base Kali install it appears to be in `/usr/local/lib/python3.6/dist-packages/objection/hooks/`, but you just just use the `find` utility yourself.
