### ISSUE TITLE
edit the list of pinned keys/certs

### ISSUE THREAD

**Issue by davemundane** [sensepost/objection#131]
excellent tool btw, thanks for the work. 
I wondered if it would be possible to add a feature that edited the network_security_config.xml so you could add a new certificate/key to the list of approved pinned keys. It is a documented method of bypassing pinning on android but would be great if objection could automate the process. 
I thought it might fit well in the unpack method, with maybe an additional flag to specify a new certificate and key pair, which were added before the apk was resigned etc.

**Comment by leonjza** [comment]
Yeah that would definitely be possible! Would probably take me a while to add that as my focus is currently on the agent rewrite, but if you are interested in trying a PR in the meantime that be awesome!

**Comment by realfukinghigh** [comment]
ok ill have a go, my python is good... android skills less good, but ill give it a shot

**Comment by IPMegladon** [comment]
Closing issue as stale, feel free to reopen.
