### ISSUE TITLE
Touch ID ByPass

### ISSUE THREAD

**Issue by bikeenld** [sensepost/objection#132]
Hi, I have created a new hook for touch id fail

Like this if we want to fail the touch id authentication i will call **ios ui touchidfail**

But this work only if executed the hook before asking for show touch id

Is there any way that if Touch Id pop is there and then execute this cmd  **ios ui touchidbypass**

will give success  result result

Right now i need to set passcode add a finger print before using touch id bypass

if there any way to avoid adding finger print and setting passcode 

Thanks 

Bikee

**Comment by leonjza** [comment]
TouchID requires a fingerprint and passcode to be configured.
