### ISSUE TITLE
App getting hang

### ISSUE THREAD

**Issue by bikeenld** [sensepost/objection#133]
Hi 
While using app

if ios ui touchid_bypass is already running 

and on App Touch id  pop is there and that time if i kill the job of **ios ui touchid_bypass**

Then app got hang 

after that i can't able to use the App  

Please help me

Thanks
Bikee

**Comment by leonjza** [comment]
Unfortunately you will have to debug your application locally to understand what is going on.

**Comment by bikeenld** [comment]
HI i tried with two app but both of them for hang


Thanks

Bikee
