### ISSUE TITLE
Using Patched IPA on another device

### ISSUE THREAD

**Issue by sushi2k** [sensepost/objection#143]
Hi, 

Following scenario:

I have my Xcode and objection setup running on my macOS and all is working. I can start the app and use objection on iPhone 1. 

But how can I get the same repackaged IPA with Frida running on a 2nd iPhone? At the moment I have whitelisted the UDID of the 2nd phone by using developers.apple.com and the UDID is also in the IPA (I can see it in the provisioning file when I unpack the IPA). But when I try to install the IPA with ideviceinstaller I get this error:

![image](https://user-images.githubusercontent.com/5951320/46244437-630bb580-c411-11e8-989d-f40abd5571f5.png)

When I connect the 2nd iPhone now to my Xcode and install a dummy app with my developer account and reinstall the app again with ideviceinstaller it works. 

Question is now:
- Is it really needed to put the 2nd iPhone to Xcode and install a dummy app? I was under the assumption that adding the UDID to the IPA should be sufficient. 
- What does Xcode actually do when installing a dummy app and why is it working then?

**Comment by leonjza** [comment]
Apologies for the late reply. As I understand it, the installation via XCode creates a developer profile on the target iDevice that you need to approve in Settings -> General -> Device Management. I am not aware of another way to replicate this other than via XCode and without this `ideviceinstaller` will fail when `installd` tries to verify the signer identify of the app. Similarly, if you have not yet allowed code from your developer profile to run on the target iDevice, verification should fail too.

**Comment by sushi2k** [comment]
Thanks for clarifying! In my scenario somehow I can just install now the app on the second device without accepting the developer profile. Very weird. 
Anyway thanks for the reply that helps!

**Comment by leonjza** [comment]
Has the profile perhaps already been approved? Could you check the status of the profile once the app is running? If you no longer have any apps on the device from that developer, the Device Management setting seems to disappear.
