### ISSUE TITLE
question of using

### ISSUE THREAD

**Issue by Blueskysun** [sensepost/objection#144]
I had a problem during using objection .How can I join apktool into environment variable in windows?Thanks if you can reply!

No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 12.2.8
Patcher will be using Gadget version: 12.2.8
Unable to find apktool. Install it with: apt install apktool (Kali Linux) before continuing.
Cleaning up temp files...

**Comment by leonjza** [comment]
Windows is not really supported, but you may get it working by adding the `apktool` executable to the `PATH` environment variable. Alternatively, using something like a Kali Linux virtual machine may just prove to be easier to get going. Good luck!

**Comment by Blueskysun** [comment]
> Windows is not really supported, but you may get it working by adding the `apktool` executable to the `PATH` environment variable. Alternatively, using something like a Kali Linux virtual machine may just prove to be easier to get going. Good luck!

I saw this tool here.
https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/
He used objection in windows,so I want have a try.This is my first issue,my English is not good because I am a Chinese .I am really happy for your reply ! I am a safety researcher.I will use  virtual machine if it don not work!Thanks again!!!

**Comment by Blueskysun** [comment]
I have solved it.Thanks！

**Comment by Blueeyes3** [comment]
@Blueskysun 

I am also encountering the same issue. Could you please share the steps how you solved it.

Thanks in advance.

**Comment by Blueeyes3** [comment]
@Blueskysun 

Figured out the installation procedure from https://ibotpeaches.github.io/Apktool/install/

Thanks
