### ISSUE TITLE
Error in patching Android apk

### ISSUE THREAD

**Issue by ytrewqytrewqytrewqytrewq1** [sensepost/objection#148]
I encountered an error in in the apk patcher 
apk : com.whatsapp_2.18.223-452426 (available on apkmirror)
objection version 1.4.3 installed from pip 

running: 

> objection patchapk --source whatsapp.apk 

the resulting code generated by the patcher is:

```
# direct methods
.method static constructor <clinit>()V
    .locals 0

    const-string p0, "frida-gadget"

    invoke-static {p0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V

    return-void
.end method
```
causing  this error in the logcat and crashing the app at the startup

```
I/dex2oat ( 6658): Verification error in void com.whatsapp.Main.<clinit>()
I/dex2oat ( 6658): void com.whatsapp.Main.<clinit>(): [0xFFFFFFFF] register index out of range (0 >= 0)
E/dex2oat ( 6658): Verification failed on class com.whatsapp.Main in /data/app/com.whatsapp-1/base.apk because: Verifier rejected class com.whatsapp.Main due to bad method void com.whatsapp.Main.<clinit>()
```
the correct code should have been:
```

.method static constructor <clinit>()V
    .locals 1

    const-string v0, "frida-gadget"

    invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V

    return-void
.end method
```
I tried to check the code in  objection/objection/utils/patchers/android.py but it looks correct

**Comment by leonjza** [comment]
Is there an existing constructor? I guess only the [partial loadLibrary](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L515-L517) gets patched in if thats the case.

**Comment by leonjza** [comment]
I wont really call the patcher one that adds code "blindly", vs just not updating the locals count.

**Comment by ytrewqytrewqytrewqytrewq1** [comment]
Using blindly I was meaning that it adds code to the constructor without performing any check. 
Instead of adding the code at the end of the constructor it could be better once inside we look for for the .locals line, check if the argoument of locals is equal 0 we change it to 1 and then we add our code in the following lines.

**Comment by leonjza** [comment]
Fwiw, also just had this on another app we are testing. Will fix soon!

**Comment by aph3rson** [comment]
@leonjza I'm also having this issue with another application. I'm not sure if it was compiled with Proguard, but it's definitely obfuscated like it was.

**Comment by leonjza** [comment]
Should be fixed in the next release.
