### ISSUE TITLE
[Feature Request] Android watch class wildcard

### ISSUE THREAD

**Issue by dvas0004** [sensepost/objection#150]
Similar to issue #45 , but instead of methods, being able to monitor all methods in classes that match a wildcard regex, for example:

`android hooking watch class 'com.exampleapp.ui.login.*' --dump-args --dump-return`

Is this useful? If so I can have a PR ready...

**Comment by leonjza** [comment]
I am sure this will be useful for both Android and iOS. A PR would be awesome! Keep in mind that the `typescript_agent` branch has the latest code with an updated agent. This branch is still missing a lot of Android hooks which I am still porting.

**Comment by dvas0004** [comment]
Fair enough, happy to help! I have an android version which I've been
testing on my last pentest assignment that's been working well. I'll see
which changes are required for integration into the branch. I don't have an
IOS simulator though so I can try do the IOS part later. Do you prefer a
merge PR to the typescript_agent branch or a rebase PR?

**Comment by leonjza** [comment]
Let's merge it to typescript_agent. The agent code is drastically different from master, and there is a lot of changes incoming! :)

**Comment by dvas0004** [comment]
Ok will do asap, and I'll try conform to the code you already have in the
branch :)

**Comment by dvas0004** [comment]
OK, all done, for your review :)

I left out some indentation on purpose to make it easier to spot the changes, but it's quite a straightforward change. Any issues let me know :)

**Comment by krapgras** [comment]
Was this ever implemented in IOS as well?

**Comment by leonjza** [comment]
@krapgras PR #502 will significantly change how the commands are used, effectively making wildcarding possible in smarter ways :D

**Comment by krapgras** [comment]
Cool 😎 I’ll have a look :)
