### ISSUE TITLE
Recursive Download of Apps Folder

### ISSUE THREAD

**Issue by ngkogkos** [sensepost/objection#152]
Hi,

First of all, good job on objection. 

As per title, it should be trivial to implement a recursive file download functionality or something like `folder download` which would help for quicker local analysis of files, such as opening all plist files together, grepping against all of them and so on.

**Comment by aph3rson** [comment]
@leonjza can I +1 this enhancement? Looking at the source, modifying `_download_android` and `_download_ios` to call `_ls_android`/`_ls_ios` (respectively), and determine if there's a file to be downloaded (or an entire folder) shouldn't be that difficult.

If it's something you'd like me to do a PR for, let me know.

**Comment by aph3rson** [comment]
@leonjza this is something I'd like to take on, can you assign this to me?

**Comment by leonjza** [comment]
Hey, sounds awesome and thank you for taking the time! 🙌

I was wondering about this one, and also had some thoughts about it:
- Maybe we could just update the commands & hooks to trigger recursively if the target path we specify ends with `/` or `/*` (or maybe even just automatically determine the target is a path irrespective)?
- We could update hooks to use things like [fileExistsAtPath:isDirectory:](https://developer.apple.com/documentation/foundation/nsfilemanager/1410277-fileexistsatpath?language=objc) to easily determine if the target is a path.
- Once a path destination is detected, prompt for recursive download.
- Profit :P

As for extracting the `_ls_*` commands, I agree with your suggestion and think it makes sense to extract them to be easily used internally.

**Comment by 7a** [comment]
+1 for this feature, without this checking for data leaks is a mess with objection currently.

Much easier to: 1) download all files + 2) grep for leak on everything

Could this be given more priority please?

**Comment by adayrodri** [comment]
+1 for this feature. Is it in development yet? Do you guys need any help /contribution?

**Comment by adayrodri** [comment]
+ 1 is this feature in development? do you need contribution help?

**Comment by IPMegladon** [comment]
Added in [#5f22e0a](https://github.com/sensepost/objection/commit/865fb7dbe4a3150bfb57651157b0710ff075ed21), although was an accidental commit (sry Leon).
@adayrodri should be able to use this now.
