### ISSUE TITLE
Not able to patch

### ISSUE THREAD

**Issue by asad0x01** [sensepost/objection#156]
I'm getting this issue while patching android app.

Screenshots:
http://prntscr.com/lfhf5t

https://prnt.sc/lfhfbk

**Comment by leonjza** [comment]
Unfortunately it is not possible to say why that happens just like that. Its usually very dependant and specific to the APK you are working with. The only thing I can suggest is that you try and decode and rebuild the APK manually using `apktool` first and then if you had to make any manual changes before the rebuild, use the `--pause` flag that will let you apply those before `objection` continues patching.

**Comment by asad0x01** [comment]
Thanks for the clarification :)
-- 
<https://about.me/asad0x01?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Asadul Islam
about.me/asad0x01
<https://about.me/asad0x01?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
