### ISSUE TITLE
aapt problem - cant patch

### ISSUE THREAD

**Issue by totaluserkksssssks** [sensepost/objection#157]
Hello,
I can't patch apk.

I receive such error while running "objection patchapk -s ap.apk":

```
An error may have occured while running aapt.
/usr/bin/aapt: symbol lookup error: /usr/lib/x86_64-linux-gnu/android/libandroidfw.so.0: undefined symbol: android_atomic_inc

Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1132, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/objection/console/cli.py", line 244, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.6/dist-packages/objection/commands/mobile_packages.py", line 153, in patch_android_apk
    patcher.inject_internet_permission()
  File "/usr/local/lib/python3.6/dist-packages/objection/utils/patchers/android.py", line 383, in inject_internet_permission
    xml = self._get_android_manifest()
  File "/usr/local/lib/python3.6/dist-packages/objection/utils/patchers/android.py", line 239, in _get_android_manifest
    return ElementTree.parse(os.path.join(self.apk_temp_directory, 'AndroidManifest.xml'))
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmps3r7emvw.apktemp.objection.apk'
```

i tried also 
`--skip-resources`

my aapt version is:  
`Android Asset Packaging Tool, v0.2-24.0.0`

I am running on kali:
`Linux kali2 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux`

And also I have installed all packages required:
`apt-get install python3.7 python3 python3-pip adb android-sdk libzopfli1 aapt zipalign && pip3 install objection`

**Comment by leonjza** [comment]
Unfortunately, you would have to try and figure out why `aapt` cant read the APK you have. The hint is this line in the output:

```
/usr/bin/aapt: symbol lookup error: /usr/lib/x86_64-linux-gnu/android/libandroidfw.so.0
```

`objection` simply wraps around `aapt` for some information with [`aapt dump badging app.apk`](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L249-L254).

**Comment by totaluserkksssssks** [comment]
For me it looks like the program can't resolve a symbol in a linked library.
So I decided to do:
`echo "/usr/lib/i386-linux-gnu/android" >>libc.conf && ldconfig`
and to other *.conf files, however the result is the same

I found that the problem maybe would be in libandroidfw library and decided to install:
`apt-get install android-libandroidfw`

And then another but similar error with aapt occured:

```
packing android-debug.apk
An error may have occured while running aapt.
/usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManagerC1ENS0_9CacheModeE

Injecting permission: android.permission.INTERNET
Writing new Android manifest...
An error may have occured while running aapt.
/usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManagerC1ENS0_9CacheModeE
```

Also tried purging and reinstalling aapt - no results...

Please note that everything is performed on fresh kali install (2018.4). Few months ago this problem has not occured at all. Maybe something in objection code was messed or in aapt package?

I have installed all in this way:
`apt-get install python3.7 python3 python3-pip adb android-sdk libzopfli1 zipalign && pip3 install objection`


Any suggestions? Maybe it is possible to omit the code (comment out) which causes the error?

**Comment by leonjza** [comment]
I would still suggest you try and get `aapt` to work in isolation first, maybe by trying some older versions.

**Comment by totaluserkksssssks** [comment]
Yes, I tried and the error was the same. So probably the aapt package is broken somehow.

Also I merged from Kali to Ubuntu2018 and previous errors with aapt are gone. However the new ones occured (but only for specific apps, with others everything is okay):

```
An error may have occured while extracting the APK.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
...many such above erros...

(..) 

Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 
W: res/drawable-v21/$file__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$file__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$file__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$file__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$file__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$file__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: A/        (15508): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 15337, --version-name, 3.118.45, --no-version-vectors, -F, /tmp/APKTOOL9876096418150316276.tmp, -0, arsc, -0, dat, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/tmpztzh12g1.apktemp/res, -M, /tmp/tmpztzh12g1.apktemp/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 15337, --version-name, 3.118.45, --no-version-vectors, -F, /tmp/APKTOOL9876096418150316276.tmp, -0, arsc, -0, dat, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/tmpztzh12g1.apktemp/res, -M, /tmp/tmpztzh12g1.apktemp/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 15337, --version-name, 3.118.45, --no-version-vectors, -F, /tmp/APKTOOL9876096418150316276.tmp, -0, arsc, -0, dat, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/tmpztzh12g1.apktemp/res, -M, /tmp/tmpztzh12g1.apktemp/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more

```

**Comment by leonjza** [comment]
`objection` requires `aapt` and `apktool` to do the heavy lifting for the patcher. Skipping the code will simply result in the patcher not patching the gadget in.

**Comment by leonjza** [comment]
Thanks for reverting back! Having a look at the flags, `-f` seems to only related to cleanup features and is used by default in objection already. As for the `-r` flag, this is added when you add the `--skip-resources` flag to the patcher [here](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L356).

It seems like there is nothing different when compared to the command that worked?

**Comment by pjmartorell** [comment]
Hi, I have the same kind of error on Ubuntu:
```
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: A/        (24525): First type is not attr!
```
If I patch the apk with the `-r` flag (skip resources),  everything seems okay but I noticed that the patched apk does not run properly. It sems to be not correctly patched. 

What are the implications of using this `-r` flag? According to `apktool` documentation:
```
-r, --no-res
This will prevent the decompile of resources. This keeps the resources.arsc intact without any decode. If only editing Java (smali) then this is the recommended action for faster decompile & rebuild
```
But I don't understand what does it mean in terms of patching with `objection`.

Thanks

**Comment by pjmartorell** [comment]
Here there is a discussion about this topic: https://github.com/iBotPeaches/Apktool/issues/1532
They suggest using `aapt2`, which is used by `apktool` from version 2.3.2.

To install the latest apktool version (2.3.4) follow these instructions: https://ibotpeaches.github.io/Apktool/install/

**Comment by leonjza** [comment]
> But I don't understand what does it mean in terms of patching with `objection`.

In the `objection` case, we actually don't touch any resources other than the smali for the main launchable activity. This can be seen [here](https://github.com/sensepost/objection/blob/ac13c44b549a21ec3299eac05e51bb732a3988d6/objection/utils/patchers/android.py#L487-L618). I recall making the resource skip optional because some APK's would not work well with the `-r` flag as you mentioned.

I'll give the `empty-framework-dir` tip some investigation, thanks for that! Do you suggest this as something we should routinely do when patching, or just when updating `apktool`? (I have not yet read the documentation 😊)

**Comment by pjmartorell** [comment]
Hi, `apktool empty-framework-dir --force` is just needed when you upgrade apktool. Anyway I have patched an apk but it's not opening correctly. I guess I will have to do it more manually.

**Comment by ssnkhan** [comment]
> For me it looks like the program can't resolve a symbol in a linked library.
> So I decided to do:
> `echo "/usr/lib/i386-linux-gnu/android" >>libc.conf && ldconfig`
> and to other *.conf files, however the result is the same
> 
> I found that the problem maybe would be in libandroidfw library and decided to install:
> `apt-get install android-libandroidfw`
> 
> And then another but similar error with aapt occured:
> 
> ```
> packing android-debug.apk
> An error may have occured while running aapt.
> /usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManagerC1ENS0_9CacheModeE
> 
> Injecting permission: android.permission.INTERNET
> Writing new Android manifest...
> An error may have occured while running aapt.
> /usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManagerC1ENS0_9CacheModeE
> ```
> Also tried purging and reinstalling aapt - no results...
> 
> Please note that everything is performed on fresh kali install (2018.4). Few months ago this problem has not occured at all. Maybe something in objection code was messed or in aapt package?
> 
> I have installed all in this way:
> `apt-get install python3.7 python3 python3-pip adb android-sdk libzopfli1 zipalign && pip3 install objection`
> 
> Any suggestions? Maybe it is possible to omit the code (comment out) which causes the error?

+1, Broken for me since upgrading to Kali 2018.4. Tried upgrading apktool and running the command above, but the decompilation still fails. Kali 2018.4 just seems to have broken a lot of things for me :(

**Comment by leonjza** [comment]
I still think this is isolated to the original target. Feel free to open a new issue if there is a bug specific to objection!
