### ISSUE TITLE
Unable to find aapt

### ISSUE THREAD

**Issue by lintangtimur** [sensepost/objection#158]
my cli > ```objection patchapk --source test.apk --architecture arm64-v8a```

Unable to find aapt. Install it with: apt install aapt (Kali Linux) before continuing.

### My System
Windows 10 64bit
Python 3.7

**Comment by leonjza** [comment]
As the error message states, you need to install `aapt`. Although Windows is not officially supported, you should be able to get it as part of the Android SDK.

Keep in mind there are a few dependencies that you will need to resolve. Good luck!

**Comment by Th3Samaritan** [comment]
please  i have similar issue how do i fix it?

**Comment by harrynajam** [comment]
PATH environment variable to include the path to the 'aapt' tool. 
In my case `set PATH=%PATH%;C:\Users\harry\AppData\Local\Android\Sdk\build-tools\30.0.3\`
