### ISSUE TITLE
Early Instrumentation on a Rooted Device (Android)

### ISSUE THREAD

**Issue by Budgiebrain994** [sensepost/objection#159]
Good morning

Quick question regarding early instrumentation on a rooted device.

According to the Early Instrumentation documentation, it is possible to execute commands before a patched app is fully loaded, allowing for SSL unpinning before the first connection attempt is made - this is awesome.

According to the Running on a Rooted Device documentation, no APK patching is required, as it is possible to run the server and directly inject into the app's namespace as it's running. However, this requires the app to be running in the first place, which means SSL connections have been made and pinned, making SSL unpinning hard to work with for some apps.

Question is - is it possible to perform early instrumentation on a rooted device without patching the APK? Maybe the ability to launch an app in a suspended state, inject into it, apply commands then resume execution. That way, e.g. SSL unpinning can be executed from the get-go without the need to reinstall the app.

Any reply is appreciated
Thanks!

**Comment by leonjza** [comment]
Yes, this is technically possible (can do this with standalone Frida for example), but not implemented yet. It has been suggested in [this](https://github.com/sensepost/objection/pull/47) PR, and I plan on pulling that in for the next major version.

**Comment by Budgiebrain994** [comment]
Thank you so much! :heart_eyes: 
As a workaround for now, and for any further users wishing to do the same, I have been putting the phone in Airplane Mode, launching the app, hooking, injecting the cert unpinner, then reactivating the network connection. The app then makes the initial handshakes fine without the pinned certs. But other scripts would require immediate injection before, so until then thanks again!
