### ISSUE TITLE
Documentation recommends using Python 3.3+ while specific functions used are only available from Python 3.4+

### ISSUE THREAD

**Issue by Thireus** [sensepost/objection#16]
The documentation https://github.com/sensepost/objection/wiki/Installation mentions:
```
python version 3.3+
```

File "./objection/utils/packages.py", line 466, in set_application_binary:
```
    info_plist = plistlib.load(f)
```

From Python documentation (https://docs.python.org/3/library/plistlib.html):
```
plistlib.load(fp, *, fmt=None, use_builtin_types=True, dict_type=dict)
Read a plist file. fp should be a readable and binary file object. Return the unpacked root object (which usually is a dictionary).
[...]
New in version 3.4.
```

As a result objection crashes when using plistlib.load with Python 3.3.

Documentation should be updated to mention Python 3.4+ requirement or code must be changed to be compatible with Python 3.3.

**Comment by leonjza** [comment]
Ah thanks! Reading the plist came in after the initial documentation was written. Thanks for spotting this! I'll check if its an easy port to support 3.3, else just bump the docs && `setup.py`.

**Comment by leonjza** [comment]
The minimum required python version is now 3.4 as of objection 1.1.2. Thanks!
