### ISSUE TITLE
Dont have connection

### ISSUE THREAD

**Issue by lintangtimur** [sensepost/objection#160]
`objection com.example.id explore`
`android sslpinning disable`

Device run on android emulator with proxy Burpsuite
com.example.id on (google: 8.1.0) [usb] # android sslpinning disable

Job: d6661ece-0f28-4441-ae3a-213193c03612 - Starting
[213193c03612] [android-ssl-pinning-bypass] Custom, Empty TrustManager ready
[213193c03612] [android-ssl-pinning-bypass] OkHTTP 3.x Found
[213193c03612] [android-ssl-pinning-bypass] TrustManagerImpl
Job: d6661ece-0f28-4441-ae3a-213193c03612 - Started
 com.example.id on (google: 8.1.0) [usb] # [213193c03612] [android-ssl-pinning-bypass] Overriding SSLContext.init() with the custom TrustManager

in application show pop up "dont have connection"

what happend?

**Comment by leonjza** [comment]
You would need to reverse engineer the target application to understand how connections work.
