### ISSUE TITLE
Wrong directory separator with cd and upload/download from Windows host

### ISSUE THREAD

**Issue by aph3rson** [sensepost/objection#165]
For `cd`, this appears to be due to:
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L93

Similarly, for `file download` and `file upload`:
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L481
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L547
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L619

`os.path.join` will use the path separator of the _host_ device, not the client - if using a Windows host, this will use `\`, not `/`.

This is only used with Android and iOS devices, so using a forward slash should be sufficient.

**Comment by aph3rson** [comment]
Updated to reflect issues with `cd`, and `file upload` and `file download`.

Note that `file download` appears to have different usage of `os.path.join` than `file upload`.

**Comment by aph3rson** [comment]
@leonjza if you'd like, I can file a PR for this, should be a simple fix.

**Comment by leonjza** [comment]
That would be splendid! Keep in mind that a lot of work has gone into the [`typescript_agent`](https://github.com/sensepost/objection/tree/typescript_agent) branch (and will be merged once I finish the Android specific code), so I will back port this patching when it's ready.

**Comment by leonjza** [comment]
Should be fixed in the next release.

**Comment by leonjza** [comment]
Fixed in 1.5.0
