### ISSUE TITLE
App crashes, couldn't find "libmonodroid.so"

### ISSUE THREAD

**Issue by lesleyxyz** [sensepost/objection#167]
When running the patched apk, I get this error:

> 12-29 22:13:18.228 25891 25891 E AndroidRuntime: FATAL EXCEPTION: main
12-29 22:13:18.228 25891 25891 E AndroidRuntime: Process: be.burgerbrandsbelgium.quick, PID: 25891
12-29 22:13:18.228 25891 25891 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/be.burgerbrandsbelgium.quick-bh8Km0nB3adgWS1xpScFqA==/base.apk"],nativeLibraryDirectories=[/data/app/be.burgerbrandsbelgium.quick-bh8Km0nB3adgWS1xpScFqA==/lib/arm64, /data/app/be.burgerbrandsbelgium.quick-bh8Km0nB3adgWS1xpScFqA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libmonodroid.so"
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1669)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:34)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:22)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6447)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5994)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5900)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:202)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:198)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6729)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-29 22:13:18.228 25891 25891 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I installed everything on windows, apktool 2.3.4.
My phone is Nokia 8 running Android 9

**Comment by TheDauntless** [comment]
It looks like something went wrong while patching the application. It's a Xamarin application and needs the libmonodroid file.

How did you patch the file? Did you get any errors while patching? After unzipping the generated apk, which files are available in the /lib folder?

Using apktool 2.3.4 on MacOS, I'm able to patch the apk and run it.

**Comment by leonjza** [comment]
At the end of last year I also had a look at a Xamarin application and ran in a similar thing. The solution for me was to look at the architecture specified in the applications `/lib` folder and then force that architecture with the `-a` to match, irrespective of the devices architecture that was autodetected.

**Comment by leonjza** [comment]
Feel free to re-open this if you have more information.
