### ISSUE TITLE
Serial option is not working

### ISSUE THREAD

**Issue by Drift-Security** [sensepost/objection#170]
Tried to connect mobile using objection with USB serial, it's not working. I could not find inofrmation in objection wiki. Please find the information below. 
Model: Oneplus
Rooted: Yes

adb devices
List of devices attached
8e524e27	device

 user  MAC  ~  %  objection -S 8exxxe27
Usage: objection [OPTIONS] COMMAND [ARGS]...
Try "objection --help" for help.

Error: Missing command.
user  MAC  ~  USAGE  %  objection --serial 8exxxe27
Usage: objection [OPTIONS] COMMAND [ARGS]...
Try "objection --help" for help.

Error: Missing command.

**Comment by leonjza** [comment]
You are missing the command that you want to run (indicated by the `Error: Missing command.` message), which I am assuming is going to be the `explore` command. Try `objection -S 8exxxe27 explore`

**Comment by Drift-Security** [comment]
@leonjza Issue was, I have installed a different version of Frida server in mobile. Now it's fixed with
**frida-server-12.2.28-android-arm64.xz** version. 

My testing device is rooted, It works like a champ after I used this command **objection --gadget "com.abc.android" explore**

#Thanks
