### ISSUE TITLE
Issue when starting objection

### ISSUE THREAD

**Issue by JBalanza** [sensepost/objection#178]
Hi,

I have pulled from master the new realease of objection and im getting the following error when linking with the objectioned app in the device.

![objection1](https://user-images.githubusercontent.com/31896165/51828660-58dcc380-22ec-11e9-86f7-1e24703d516a.png)

the error is arised when objection tries to retrieve agent.js from the local compiled directory since the file does not exist.

![objection2](https://user-images.githubusercontent.com/31896165/51828750-92153380-22ec-11e9-8854-e8a97b94ebc1.png)

When upgrading I have tried the following:
- pip uninstall objection
- git pull
- pip install -r requirements.txt (does not change from the previous release)
- python setup.py install

I saw that it have been some changes with that file recently https://github.com/sensepost/objection/search?q=agent.js&unscoped_q=agent.js and i dont know if the problem could be related to them.

regards.

**Comment by leonjza** [comment]
Heya! The newest release for development purposes from master requires a build artefact (the `agent.js`) to be compiled before you can run it. I have written up a short article [here](https://github.com/sensepost/objection/wiki/Agent-Development-Environment) describing the process to get NPM to build you a new `agent.js` with `npm run build`. Once you have done this the `agent.js` should be available.

Speaking of dependencies, `frida-tools` got a bump this weekend with a breaking dependency change in version 1.2.3, so update the local `requirements.txt` to use `frida-tools==1.2.2` until I can commit the `prompt-toolkit` change introduced in version 2.0.

**Comment by OscarAkaElvis** [comment]
I'm having the same issue.

More dependencies? omg... I think the npm stuff could be avoided keeping the js file in the project. I think moving forward all should be easier but now is more complicated.... IMO that commit should be reverted:  10e62cb59d9ca44fdcfd8c165d16068d13abf31d

**Comment by JBalanza** [comment]
hi @leonjza,

I have tried with npm following the article you referred. I still having problems to connect to the device:

![objection3](https://user-images.githubusercontent.com/31896165/51834206-e672e000-22f9-11e9-839c-0893a96e8a4b.png)

after the npm compilation i reinstalled objection. Now it throws me a different error.

**Comment by leonjza** [comment]
@JBalanza Interesting, so it seems like it is not able to read the generated `agent.js` you got from the build due to some encoding issues? I am assuming you built it on Windows, so not sure what the effect of that may have been. Could you have a quick look at it and see if it has valid JavaScript as well as check the files encoding? On my local computer its a UTF-8 encoded file that starts as follows:

```
~/Documents/git/objection(master*) » file objection/agent.js
objection/agent.js: UTF-8 Unicode text, with very long lines, with LF, NEL line terminators, with escape sequences
(venv3) ------------------------------------------------------------
~/Documents/git/objection(master*) » head objection/agent.js
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
module.exports = require("core-js/library/fn/array/from");

},{"core-js/library/fn/array/from":19}],2:[function(require,module,exports){
module.exports = require("core-js/library/fn/array/is-array");

},{"core-js/library/fn/array/is-array":20}],3:[function(require,module,exports){
module.exports = require("core-js/library/fn/get-iterator");

},{"core-js/library/fn/get-iterator":21}],4:[function(require,module,exports){
(venv3) ------------------------------------------------------------
~/Documents/git/objection(master*) »
```


If all of those seem fine, could you change the `with open(self.agent_path, 'r') as f:` to `with open(self.agent_path, 'rb') as f:` [here](https://github.com/sensepost/objection/blob/master/objection/utils/agent.py#L143) and test?

Thanks

**Comment by leonjza** [comment]
Ah awesome thanks for the feedback. The last thing to do I think would be to just cast the `agent.js` read to a `str()` before returning on the `join()`. I'll commit this shortly as its probably a good idea regardless.

**Comment by leonjza** [comment]
Could you test that last commit? I will also setup a Windows environment sometime and try and debug this better.

**Comment by JBalanza** [comment]
I've tried the last commit. Still but different error this time

![objection4](https://user-images.githubusercontent.com/31896165/51919637-27dfba00-23e4-11e9-8ce6-b099db0049e5.png)

without any doubt, if you want to support Windows users like me you shuld build a Windows env haha

**Comment by leonjza** [comment]
Thanks for the feedback. There is quite a bit going on at the moment that I need to focus on to get 1.5.0 ready. Let me sort those asap and then give a Windows environment a shot.

**Comment by JBalanza** [comment]
Hey! Just discovered that now the objection v1.5.2 it fully works in windows machines just doing what you proposed  [here](https://github.com/sensepost/objection/wiki/Agent-Development-Environment)

Awesome tool. I'm closing the issue.

**Comment by leonjza** [comment]
Ah awesome. Thank @aph3rson for that :)
