### ISSUE TITLE
Documentation needs to be changed for 'applesign' installation

### ISSUE THREAD

**Issue by Thireus** [sensepost/objection#18]
The sources for applesign are not available anymore from "npm install -g node-applesign" as mentioned by the documentation.

```
npm install -g node-applesign
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-applesign"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/node-applesign
npm ERR! 404 
npm ERR! 404  'node-applesign' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Instead the following should be used to install applesign:

`npm install -g -S "https://github.com/nowsecure/node-applesign.git"`

**Comment by leonjza** [comment]
Wups. You are right, however, its possible to install it with just `npm install -g applesign`. Could you confirm that this works for you?

Thanks for reporting this!

**Comment by Thireus** [comment]
Correct, `npm install -g applesign` works.

**Comment by leonjza** [comment]
Excellent thanks!
