### ISSUE TITLE
Exception during android sslpinning disable 

### ISSUE THREAD

**Issue by jpmasud** [sensepost/objection#182]
On a Xiaomi Mi8, I am able to patch the apk and was trying to disable sslpinning but I get an exception.

```
Job: 94ffc1bb-1938-4b3b-81ab-3abd7c6e92d3 - Starting


An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: the connection is closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 389, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 200, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.7/site-packages/objection/commands/android/pinning.py", line 30, in android_disable
    runner.run_as_job(name='pinning-disable')
  File "/usr/local/lib/python3.7/site-packages/objection/utils/frida_transport.py", line 400, in run_as_job
    job.script.load()
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 192, in load
    self._impl.load()
frida.TransportError: the connection is closed
```

In my adb logcat, the only interesting thing I see is
```
02-11 02:48:37.170 30627 30714 W name.app : Failed to determine odex file name: Dex location /data/data/name.app/cache/frida644904717091717560dat has no extension.
```

I suspect the issue is that my phone's architecture defaults at arm64-v8 but the app only has 32-bit libraries so I had to patchapk using the armeabi-v7a architecture flag
```
objection patchapk -a armeabi-v7a -D -s base.apk
```

Not really sure what to do next!

**Comment by leonjza** [comment]
Hey, I am not certain why this is happening, other than the fact that the application may have some special case that objection can't handle yet. When 1.5.0 lands soon I will have also included the new crash reporting features available in Frida 12.3 which may help with debugging these cases in the future.

For now, the only thing I can suggest would be to manually reverse engineer the application to determine the cause of the crash.
