### ISSUE TITLE
When patching an IPA which name is patched.ipa, the output is named "tched-frida-codesigned.ipa" (first two letters missing)

### ISSUE THREAD

**Issue by Thireus** [sensepost/objection#19]
I'm not sure what's happening there, but I just noticed that if I provide an IPA named "patched.ipa" the objection patchipa output is missing the first two letters:

`objection patchipa --source patched.ipa --codesign-signature XXXXXXX -p embedded.mobileprovision`

output:

`tched-frida-codesigned.ipa`

**Comment by leonjza** [comment]
All I can say is wtf. Nonetheless, I can confirm this is the case. Working on a fix. Thanks!
