### ISSUE TITLE
Encoding not declared correctly in agent.py

### ISSUE THREAD

**Issue by aph3rson** [sensepost/objection#191]
When calling `_get_agent_source()`, the compiled agent is opened with `open()`. However, the encoding isn't declared in this call properly - therefore, it will use the operating system default to open the file. On some systems, this will likely default to `utf-8` or similar - however, Windows systems will still open files as cp1252 (see [this StackOverflow thread](https://stackoverflow.com/questions/42070668/python-3-default-encoding-cp1252/42070962)). The `agent.js` file appears to contain some characters, such as `0x81` which are invalid in cp1252 (as to why, I'm unsure).

Reformatting `agent.js` in ANSI seems to fix this issue - however, I think the easier option would be to add `encoding='utf-8` to the `open()` call, as this is the standard method of doing so.

**Comment by aph3rson** [comment]
I can file a PR, if that's necessary.

**Comment by leonjza** [comment]
Thanks for the debugging work on this! Feel free to do a PR if you have time, otherwise, I should be able to get to this later tonight and push a new release. 👍

**Comment by aph3rson** [comment]
#192 will fix this issue.
