### ISSUE TITLE
"import" command disappeared

### ISSUE THREAD

**Issue by izadgot** [sensepost/objection#196]
"import" command for import Frida script disappeared on Objection version 1.5.2
Could you please take it back?

**Comment by aph3rson** [comment]
@leonjza as far as I know, this shouldn't be an enhancement - the help files still exist, and it just appears that the necessary command and metadata have been removed. It's still available in 1.4.1, and appears to have been removed in a834048a294a0f88429050904700d0b13f3e2fc1 during the typescript agent port.

Any particular reason why?

**Comment by himalr** [comment]
Is this why we don't see scripts imported using "import hook.js" in the "jobs list"?
