### ISSUE TITLE
Able to work in jailbroken device?

### ISSUE THREAD

**Issue by illnino** [sensepost/objection#2]
1. If an App installed on JB device, does it require patching the app?
2. Could two patched app installed at the same time? I did not where to specify the app name. Did I miss anything?

**Comment by leonjza** [comment]
I have not yet tested this yet, but the theory is if you have [`frida-server`](https://www.frida.re/docs/ios/#with-jailbreak) running on your jailbroken device, then you can connect objection to any running app with `objection -g <name> explore` where the name can be found using `frida-ps -U`. Not specifying a gadget name with `-g` simply defaults objection to `Gadget`, which is the name used for the gadget in patched iOS applications.

You can have as many apps installed as you your developer license allows for. I think the free one will let you install two/three apps. Patched applications by default will have the gadget name of `Gadget`, so objection will simply look for that and connect to it. Backgrounding an app will cause objection to lose connection, so if you start a second application, running `reconnect` will connect objection to that application.

Hope that helps.

**Comment by illnino** [comment]
Thanks. That definitely helps.
