### ISSUE TITLE
local fridagadget is v0.

### ISSUE THREAD

**Issue by Numlk12** [sensepost/objection#201]
I always fail when download the latest Fridagadget, like this:

- objection patchipa -s xxx.ipa -c xxxxxxxx
- A newer version of objection is available!
- You have v1.4.3 and v1.5.2 is ready for download.
- Upgrade with: pip3 install objection --upgrade
- For more information, please see: https://github.com/sensepost/objection/wiki/Updating
- Using latest Github gadget version: 12.4.0
- Remote FridaGadget version is v12.4.0, local is v0. Downloading...
- Downloading from: https://github.com/frida/frida/releases/download/12.4.0/frida-gadget-12.4.0-ios-universal.dylib.xz
- Downloading iOS dylib to /var/root/.objection/ios/FridaGadget.dylib.xz...

Then I will still waiting until failed. 
I tried to download the "frida-gadget-12.4.0-ios-universal.dylib.xz" ,rename it to "FridaGadget.dylib.xz" and put it into "/var/root/.objection/ios/" ,but it did not work.

Could you help me install the Fridagadget manually, I have no idea about that.

**Comment by leonjza** [comment]
Could you give some more information on the failure? Any errors?
