### ISSUE TITLE
failed to create process on windows 10 with python 3.7.1

### ISSUE THREAD

**Issue by UbaidAhmed2803** [sensepost/objection#207]
Hi,

I am using windows and trying to install objection via pip3 install -U objection. Installation completes without any error. However, when I type objection I get failed to create process.
please note that I have frida-tools installed and it is also throwing the same message when I type frida or any other frida command.

I am using Windows 10 and have python 3.7.1 installed.

**Comment by leonjza** [comment]
What is your full command line used to invoke objection?

**Comment by UbaidAhmed2803** [comment]
To test I tried following commands
1. objection
2. objection -h
3. objection --help
4. objection explore -q

failed to create process in every case

**Comment by leonjza** [comment]
Only `objection explore` would have attempted to connect to a process called `Gadget` via USB, whereas the other commands are all help commands. That being said, I suggest you have a read through the [wiki](https://github.com/sensepost/objection/wiki) to learn how objection works, and quite possibly the Frida [docs](https://www.frida.re/docs/home/) too.

**Comment by UbaidAhmed2803** [comment]
Yes, I followed each and every step in the doc. Everything works fine as far as installation is concerned. After successful installation, I moved to the usage document and as soon as I tried the very first command "objection --help", I got unable to create process thing.

Same is the case with frida.

**Comment by leonjza** [comment]
In that case, I am guessing there is something wrong locally, isolated to your machine. If `objection --help` complains about process creation, then it is not related to Frida yet as the code path to connect to a gadget/server is not followed yet.

Sorry I can't help more, but the problem statement is really vague. Good luck!

**Comment by towbes** [comment]
If folks are running into this from google...

I ran into this issue and figured out that I had installed objection inside a pipenv, but was trying to launch without being in the pipenv shell.  So that error is very likely related to your python environment setup and you should start looking there.

**Comment by LouisBellinger** [comment]
For other folks stumbling on this, having spaces in your path may create issues on windows when invoking objection ("test test" in your path may create issue for instance).
