### ISSUE TITLE
Is it possible to Bypass local Authentication Android | Query 

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#208]
Hi,

After patching apk using objection explorer

How can i bypass local authentication for Android device on which 
Biometric authentication is supported

Is this supporting now for Android

As i can see for iOS
After patching application using objection
I am able to bypass Face Id and Touch Id in  iOS device

Thanks 

Your Help will highly appreciable !!

**Comment by leonjza** [comment]
You will need to develop a new hook for this and is not a feature in objection yet.

**Comment by bikee1235** [comment]
Hi 

Can you suggest some instruction so i can develop the same

and integrate it objection 

Thanks

**Comment by leonjza** [comment]
Have a look at the objection source code and read the Frida documentation.
