### ISSUE TITLE
Objection Installation error on macOS

### ISSUE THREAD

**Issue by sentago** [sensepost/objection#210]
Hi everyone,

I'm facing an error when i tried to install objection on macOS using "pip3 install -U objection"

i got the below error message:

```
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/9k/gkg8xzc56_g6xv16y2x61y740000gn/T/pip-build-m1x4qr_a/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/9k/gkg8xzc56_g6xv16y2x61y740000gn/T/pip-vsbt2eiu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/9k/gkg8xzc56_g6xv16y2x61y740000gn/T/pip-build-m1x4qr_a/frida/
```

Could you please help me to solve this issue.

Thank you

**Comment by leonjza** [comment]
Unfortunately this is a super ambiguous error message and would require some local debugging from your side. For what its worth, I can confirm objection installs fine via pip on my local test host.

**Comment by d3tonator** [comment]
I'm facing this issue while installation... Is there anybody to help me out ... 

![image](https://user-images.githubusercontent.com/17857559/81470710-e6a2a080-9209-11ea-82e0-a429c3a88535.png)
