### ISSUE TITLE
Error in android sslpinning disable

### ISSUE THREAD

**Issue by kseniyaSlo** [sensepost/objection#219]
Hi all,

 When running the "android sslpinning disable" command, we receive the following error messages:

```
...com.xxx.xxx on (samsung: 7.0) [usb] # android sslpinning disable
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
script is destroyed

Python stack trace: Traceback (most recent call last):
  File "c:\python\python3\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "c:\python\python3\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "c:\python\python3\lib\site-packages\objection\commands\android\pinning.py", line 26, in android_disable
    api.android_ssl_pinning_disable(_should_be_quiet(args))
  File "c:\python\python3\lib\site-packages\frida\core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "c:\python\python3\lib\site-packages\frida\core.py", line 240, in _rpc_request
    self.post(message)
  File "c:\python\python3\lib\site-packages\frida\core.py", line 202, in post
    self._impl.post(raw_message, **kwargs)
frida.InvalidOperationError: script is destroyed

...com.xxx.xxx on (samsung: 7.0) [usb] #
```

Note: I'm using the updated version of Objection tool.

Thanks for your help!

**Comment by leonjza** [comment]
Hey, looking at the error, I think there was a problem on the Frida side of things. This may be due to many reasons, including some runtime integrity checks that could exist.

The best thing you can do is to debug this a little, and maybe try run some of the hooks manually using just the `frida` command line.

**Comment by aph3rson** [comment]
@kseniyaSlo are you able to run other Objection commands? That seems very much like the app is running integrity checks.

If your device is rooted, try using frida-server to see if it has to do with the patching process.

**Comment by 0xBADDCAFE** [comment]
I faced this problem too, and following the below steps solved in my case.

1. Launch frida-server with `adb shell "/data/local/tmp/frida-server &"`
2. Launch target application on device
3. Execute `objection --gadget "your.awesome.application" explore`

Note: my device is rooted.

In my case, when skip the step `2.` , the step `3.` seems launch the application on device, but it down immediately and get the `frida.InvalidOperationError: script is destroyed` message.
