### ISSUE TITLE
Plans to support frida-server instead of gadget?

### ISSUE THREAD

**Issue by ropnop** [sensepost/objection#22]
Great tool! Just wondering if there's every any plans to support funning frida-server as root instead of relying on the gadget? I see the value in using the gadget when jailbreak or root is not possible, but I would love to use the REPL with an unpatched app on a jailbroken/rooted device. Is that possible?

**Comment by bernard-wagner** [comment]
Already does. Start the frida-server and pass the same value as you would for frida.

## iOS ##
```
frida -U -n MyApp
python3 -m objection.console.cli --gadget MyApp explore
```

## Android ##

```
frida -U -n com.example.myapp
python3 -m objection.console.cli --gadget com.example.myapp explore
```

**Comment by leonjza** [comment]
Technically this is already possible as described in #2. I have a TODO to add this to the projects wiki to make it more obvious! But, exactly as @bernard-wagner said should do the trick!

**Comment by ropnop** [comment]
Worked great! Thanks!

**Comment by leonjza** [comment]
👍
