### ISSUE TITLE
how can i get wifi password from my phone without root  ?

### ISSUE THREAD

**Issue by minanagehsalalma** [sensepost/objection#221]
my phone is huawei y32 
android 5.1

**Comment by leonjza** [comment]
I don't think you can read the wpa_supplicant config file without root.

**Comment by minanagehsalalma** [comment]
@leonjza  ok thanks 
can you take a look on this https://www.reddit.com/r/androidapps/comments/b90mmg/is_there_an_app_that_can_backup_wifi_profiles/ek1kapo/
