### ISSUE TITLE
Unable to determine URL to download Library for android

### ISSUE THREAD

**Issue by rakeshraks** [sensepost/objection#226]
**Describe the bug**
Unable to determine URL to download Library

**To Reproduce**
1. objection patchapk -s xxx.apk

**Evidence / Logs / Screenshots**

[SSLissue](https://user-images.githubusercontent.com/26092136/56207431-50cf2d00-606c-11e9-8af5-3ead01ccffc4.png)

**Comment by leonjza** [comment]
It looks like the android gadget for x86 android is missing for [Frida 12.4.8](https://github.com/frida/frida/releases/tag/12.4.8) (frida-gadget-12.4.8-android-x86 is not there). Try specifying the version as 12.4.7 for the patcher with the `-V 12.4.7` flag.

**Comment by rakeshraks** [comment]
Thank You so much. Its working now.

**Comment by leonjza** [comment]
Awesome. I have asked about the missing gadget, next version should be ok again.
