### ISSUE TITLE
Can't get objection shell

### ISSUE THREAD

**Issue by Normaltic1018** [sensepost/objection#227]
Hi I like objection.

I use objection once.
when i first use it, it does work well.

but after that,
It does not give me objection shell.

It just print

Using USB device `iPhone`
Agent injected and responds ok!

and doesn't give me objection shell.

Even though i use another computer, it does not give me objection interpreter shell.
( windows 10, OS X ...  I try different OS, different notebook, desktop)

i don't know the reason.
I love this objection function, so i really want to use it

I try 
objection version 1.6.3.
frida 12.4.8
frida-server 12.2.30 (ios device)
python 3.7.3

**Comment by leonjza** [comment]
Hey, you haven't really provided much detail and there are a lot of things that may have gone wrong causing the behavior you describe. The only thing I can suggest you do is have a read through the [wiki](https://github.com/sensepost/objection/wiki) carefully and make sure you follow the steps applicable to your environment, step by step.

Good luck.
