### ISSUE TITLE
iOS Keychain: give binary data for non-decodable classes

### ISSUE THREAD

**Issue by aph3rson** [sensepost/objection#230]
**Is your feature request related to a problem? Please describe.**
At the moment, decoding items from the Keychain requires that the object stored be of a certain set of classes. However, if a class is of an arbitrary type, or there's another error decoding, all of the Keychain output shows `(failed to decode)`.

**Describe the solution you'd like**
Even if Objection is unable to properly decode the output, I would prefer to see some kind of binary data - that way, we can attempt to decode it ourselves.

**Describe alternatives you've considered**
I had thought that Objection supported this previously, but I can't find where it was in the codebase.

**Comment by leonjza** [comment]
This is definitely something I agree needs to be improved. For reference, the pre-1.5.0 hook is available here: https://github.com/sensepost/objection/blob/1.4.1/objection/hooks/ios/keychain/dump.js

**Comment by h4ng3r** [comment]
On iOS 11 with unc0ver JB I got "(failed to decode)". The needle keychaindumper is working for me, you could take a look, maybe it will help you with this issue too.
https://raw.githubusercontent.com/mwrlabs/needle/master/needle/modules/storage/data/keychain_dump_frida.py
