### ISSUE TITLE
Support PhoneGap's SSLCertificateChecker plugin

### ISSUE THREAD

**Issue by aph3rson** [sensepost/objection#231]
**Is your feature request related to a problem? Please describe.**
Using the `ios sslpinning disable` feature doesn't work on Cordova/PhoneGap apps which use [the above plugin](https://github.com/EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin) for certificate pinning.

**Describe the solution you'd like**
Hooking the `-[CustomURLConnectionDelegate isFingerprintTrusted:]` method to always return true should be all that's necessary. It works fine if that method is manually hooked.

**Describe alternatives you've considered**
Using `ios sslpinning disable` shows the call to `nw_tls_create_peer_trust()`, but that's not able to be overridden just yet. Hooking the above method appears to work just fine, though.

**Comment by aph3rson** [comment]
You can see the source of the method in question [here](https://github.com/EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin/blob/master/src/ios/SSLCertificateChecker.m#L109-L116).

**Comment by leonjza** [comment]
I don't have an application handy that makes use of this plugin now, but is it possible for you to test this patch perhaps? https://gist.github.com/leonjza/af7972b1f04b415970e1dbc8712f6e37

**Comment by aph3rson** [comment]
The diff looks good, I'll try it out tomorrow and report back.

**Comment by aph3rson** [comment]
@leonjza You were pretty much all the way there - the return value was wrong, though. I've modified the return value and filed PR #233 to fix this.

**Comment by leonjza** [comment]
Awesome, thanks 🙌

**Comment by aph3rson** [comment]
Thanks for the merge! When can we expect to see this in a release?

**Comment by leonjza** [comment]
Most probably by the end of the week.
