### ISSUE TITLE
How to remove a method/class watch?

### ISSUE THREAD

**Issue by qrx** [sensepost/objection#232]
I am not seeing in the help files how to remove a class/method watch.

`ios hooking watch method <method_name>`

How can I remove the method from being watched?

**Comment by aph3rson** [comment]
When executing any long-lasting command (such as `watch`, `set return_value`, `sslpinning disable`, etc.), it's stored as a job. The job ID is printed in the console when the command is invoked. You can also list all current jobs by using the command `jobs list`.

To stop the watch/any other job, use `jobs kill [jobID]`, where `[jobID]` is the aforementioned job ID for that job.

**Comment by leonjza** [comment]
Like @aph3rson has already mentioned, the `jobs` command is what you are interested in.
