### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by sushi2k** [sensepost/objection#237]
**Describe the bug**

I am using Frida 12.6.5 installed via Cydia on a jailbroken iOS 10.3.3 (doublehelix jb) and cannot upload a file. 

**To Reproduce**

I wanted to upload a file via objection and got the following error. 

```bash 
on (iPhone: 10.3.3) [usb] # file upload /Users/sven/Desktop/rsa.pub
Uploading /Users/sven/Desktop/rsa.pub to /var/mobile/Containers/Data/Application/72C7AAFB-1D75-4FBA-9D83-D8B4A2D44133/rsa.pub
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
timeout was reached

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.7/site-packages/objection/commands/filemanager.py", line 479, in upload
    _upload_ios(source, destination)
  File "/usr/local/lib/python3.7/site-packages/objection/commands/filemanager.py", line 501, in _upload_ios
    if not api.ios_file_writable(os.path.dirname(destination)):
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 319, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 237, in _rpc_request
    self.post(message)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 199, in post
    self._impl.post(raw_message, **kwargs)
frida.TransportError: timeout was reached
```

**Expected behavior**
Upload the file :-) 

**Evidence / Logs / Screenshots**
see above 

**Environment (please complete the following information):**
 - Device: [iPhone6 Plus]
 - OS: [e.g. iOS10.3.3]
 - Frida Version [12.6.5]
- Objection Version [1.6.4]

**Comment by aph3rson** [comment]
You're able to use other functions in Objection, correct? That error indicates that the Frida gadget/server is not responding, which is interesting to be seeing when trying to upload a file.

**Comment by sushi2k** [comment]
Other functions are working yes. For example downloading a file.

**Comment by leonjza** [comment]
Interesting. I would need to get my hands on a jailbroken iOS device before I could test this, but from the stack trace it looks like the timeout happens in the [writable check](https://github.com/sensepost/objection/blob/master/agent/src/ios/filesystem.ts#L49-L59) is done for the new path.

**Comment by aph3rson** [comment]
@leonjza I have a jailbroken iOS device if you want me to test something.

**Comment by leonjza** [comment]
Cool! Can you reproduce this bug?

**Comment by aph3rson** [comment]
I'll give it a shot later today and report back.

**Comment by aph3rson** [comment]
I was unable to reproduce this issue - on a jailbroken device, I was able to upload files just fine.

@sushi2k are you using a patched IPA, or frida-server? If the latter, can you confirm what version of frida-server you're using, and where it was obtained from?

**Comment by leonjza** [comment]
I recently tested using a device with the same jailbreak and could not reproduce this.
