### ISSUE TITLE
Codesigning issue when patching IPA

### ISSUE THREAD

**Issue by Blueeyes3** [sensepost/objection#241]
When trying to patch an IPA file, there is a problem occurring with codesigning. the detailed error is posted below.

Codesigning patched IPA...
Error: This IPA contains only bitcode. Must be transpiled for the target device to run.
    at Applesign.signAppDirectory (/usr/local/lib/node_modules/applesign/index.js:100:13)
    at Applesign.signIPA (/usr/local/lib/node_modules/applesign/index.js:71:16)
    at async main (/usr/local/lib/node_modules/applesign/bin/applesign.js:52:7)

Environment:
Objection - 1.6.5
MacOS
Gadget version - 12.6.6

**Comment by leonjza** [comment]
Resigning an IPA is handled by [applesign](https://github.com/nowsecure/node-applesign/), which can't sign [bitcode only](https://github.com/nowsecure/node-applesign/releases/tag/2.5.0) IPA's. [This](https://stackoverflow.com/a/31207170) StackOverflow answer may help you understand why. The only option you have is to ask the app developer to give you a fully compiled app.
