### ISSUE TITLE
Usage of xcrun bitcode_strip functionality to remove bitcode enabled in IPA

### ISSUE THREAD

**Issue by Blueeyes3** [sensepost/objection#249]
Hi Team,

With respect to the closed issue #241 , we came across a feature provide by xcode in order to remove bitcode enablement from the executable file in the Payload. 

This was helpful for us in order to remove the bitcode enablement and proceed further with patching using objection.

The below link helped to understand and utilize the xcrun to perform the process.
https://pspdfkit.com/guides/ios/current/faq/bitcode/

So thought of suggesting as a feature to be included so that bitcode enablement issue can also be handled by the Awesome Objection! ;)

Thanks

**Comment by leonjza** [comment]
Hey. As mentioned #241, this has to do with how the target IPA was built and is not something objection can solve. The original problem stated that the target was bitcode **only** (hence the applesign error), and not that it _also_ contained bitcode.

I don't think stripping bitcode in multi-format apps is necessary for applesign to do its magic.
