### ISSUE TITLE
Feature request: Frida interactive shell

### ISSUE THREAD

**Issue by vdun** [sensepost/objection#252]
Frida interactive shell within Objection shell. Something like:
```
com.test.Test on (iPhone: x.x.x) [usb] # frida shell
console.log('Hi from frida!')
```

**Comment by leonjza** [comment]
This was sort of implemented with the `evaluate` command available in v1.7.0, released during DEF CON 27. I don't think it makes much sense to reimplement the Frida interactive shell we already have using the `frida` command line too.
