### ISSUE TITLE
[FR] Pause before recompiling

### ISSUE THREAD

**Issue by pundoo** [sensepost/objection#256]
I'm trying to recompile a package that has invalid character in resource names. So, in order to recompile it successfully I've to manually rename those resources and fix related references beforehand.
But, when using **objection** there's no delay between the patching and recompilation process. It would be better to have some kind of user prompt before recompilation, to overcome such scenarios.

**Comment by leonjza** [comment]
The [`--pause`](https://github.com/sensepost/objection/blob/master/objection/console/cli.py#L319-L320) flag will pause (waiting for you to press enter) before asking `apktool` to recompile the apk. This should give you an opportunity to do any manual changes if needed.
