### ISSUE TITLE
 Called SSLContext.init(), overriding TrustManager with empty one.

### ISSUE THREAD

**Issue by rakeshraks** [sensepost/objection#261]
when accessing the application with "android sslpinning disable' its giving  'Called SSLContext.init(), overriding TrustManager with empty one.' But application not reaching the server. And no response.
How to resolve this?. kindly help me.
![issue](https://user-images.githubusercontent.com/26092136/62538116-a889e200-b86f-11e9-8551-31d5e8dfe055.png)

**Comment by leonjza** [comment]
Unfortunately, you would need to reverse your target application a little to understand why this could be happening. Without knowing the implementation in the app, there is not much we can do further.

Good luck!
