### ISSUE TITLE
Error: access violation accessing 0xb4073000

### ISSUE THREAD

**Issue by la0s** [sensepost/objection#264]
**Describe the bug**
When use command "memory dump from_base" to dump so, occurred error: access violation accessing 0xb4073000. So I think we should use Memory.protect to update memory protection before wo choose dump this.

**Evidence / Logs / Screenshots**
![image](https://user-images.githubusercontent.com/37521845/62855364-a23eae80-bd24-11e9-8b80-3f821a14dec9.png)

**Environment (please complete the following information):**
 - Device: nexus6p
 - OS: Android 6.0.1
 - Frida Version 12.6.12
- Objection Version 1.7.0

**Comment by leonjza** [comment]
How did you enumerate the range applicable here?
Happy for a PR to do the protection if it makes sense here.
