### ISSUE TITLE
Memory dump all error (session detach message) process-terminated

### ISSUE THREAD

**Issue by cpholguera** [sensepost/objection#269]
**Describe the bug**
Cannot dump a whole Android app. 

**To Reproduce**

https://github.com/OWASP/owasp-mstg/raw/master/Samples/Android/01_HelloWorld-JNI/HelloWord-JNI.apk

```
sg.vantagepoint.helloworldjni on (google: 8.1.0) [usb] # memory dump all /Users/Me/Desktop/memory_android_verbose                                                               

Will dump 719 rw- images, totalling 1.7 GiB
Dumping 1003.0 MiB from base: 0x14100000  [------------------------------------]    0%  00:12:57- [incoming message] ------------------
"process-terminated"
- [./incoming message] ----------------
(session detach message) process-terminated
Dumping 8.0 MiB from base: 0x7fc753e000  [####################################]  100%             
Memory dumped to file: /Users/Me/Desktop/memory_android_verbose
sg.vantagepoint.helloworldjni on (google: 8.1.0) [usb] # exit 
```

The app quickly crashes once the dump is started.

**Expected behavior**
Even with memory access violation errors for some regions, one should expect that at least all readable memory is dumped.

**Evidence / Logs / Screenshots**
See above.

**Environment**

 - Device: Nexus 5X
 - OS: Android 8.1.0
 - Frida Version: 12.6.16
 - Objection Version: 1.7.4

**Additional context**

For the sake of having a reference to help debugging I've run Fridump: `python3 fridump.py -v -U sg.vantagepoint.helloworldjni`. objection dumps a total of 31,5 MB while Fridump dumps 985,7 MB. Also in this case, the app does not crash so quickly, but after all those MBs were dumped (and probably due to memory access violations?).

Thanks in advance and please let me know if I can assist you on further testing.

**Comment by leonjza** [comment]
This *could* be because we are defaulting to `rw-` [pages](https://github.com/sensepost/objection/blob/4df9391e197e5c0547153019c503bff5b8c799e5/objection/commands/memory.py#L76). We could consider making the protection used an argument so that it could be changed to say `r--` only.

**Comment by cpholguera** [comment]
That could be it. Or maybe also a combination of that and handling of exceptions when reading from non-readable memory? Maybe those regions could be skipped and logged for the sake of knowing that not all memory was dumped.

I didn't have time to dive deep into the agent api calls you're using but will do it ;)

Thanks for the quick answer!

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen
