### ISSUE TITLE
TypeError when trying to connect to frida-server

### ISSUE THREAD

**Issue by frankmarco2000** [sensepost/objection#271]
Hello,
I have an error that is occurring whenever I try to connect to a remote (non usb) ios device using objection. 

my target is a jailbroken iOS device running 1131.
I am running the iOS frida server on the device. 

if I execute the following "device type" query:

```
objection -N -h 192.168.xxx.yyy -g frida-ios-server-arm64 -d device-type
```

I get the following:
```
**[debug] Process attached!
Agent injected and responds ok!
Traceback:
File "../objection" , line 10, in module sys.exit(cli())
........
frida.core.RCException: TypeError cannont read 'toString' of null.**
```

If I interact with the frida server just using frida scripts or frida tools everything works fine.

Any help or information would be greatly appreciated.

frida server version: 12.6.3
objection version: 1.7.4

Thank you in advance.

Frank

**Comment by leonjza** [comment]
Hey, thanks for the report. I suspect I have never actually tested this command since the agent port. Sorry about that!

Will add it to the stack to fix.

**Comment by frankmarco2000** [comment]
Great!

How will i know when it is fixed?
Should I just keep checking this ticket from time to time?

**Comment by leonjza** [comment]
This ticket should auto close when the commit lands that fixes and mentions this issue. That should trigger an email to you as the author.

**Comment by aph3rson** [comment]
@frankmarco2000 what's the goal of running that command? I'm able to use `objection explore` just fine with a network-bound frida-server, and it runs without issue.

**Comment by leonjza** [comment]
Just tested this and it seems to work fine for me?

```
$ objection --debug device-type
[debug] Agent path is: ~/objection/objection/agent.js
[debug] Injecting agent...
Using USB device `iPhone`
[debug] Attempting to attach to process: `Gadget`
[debug] Process attached!
Agent injected and responds ok!
Connection: USB
Name: za.sensepost.ipewpew
System: iOS
Model: iPhone
Version: 13.1
Asking jobs to stop...
Unloading objection agent...
[debug] Calling unload()
```

**Comment by leonjza** [comment]
Also works with `--network` for me. I notice you used `frida-ios-server-arm64` as the gadget name though. Have you tried an application bundle id?
