### ISSUE TITLE
frida.InvalidOperationError: script is destroyed for iOS

### ISSUE THREAD

**Issue by i11m20n** [sensepost/objection#273]
**Describe the bug**
When my command was running on iOS 10.2, the console experienced the following error. My device has been jailbroken.
![image](https://user-images.githubusercontent.com/13911593/64971654-940f1f80-d8da-11e9-9a31-f8faadd87976.png)

**To Reproduce**
1. Run command 'frida-ps -Uia'
2. Run command 'objection -g "com.tigisoftware.Filza" explore'

**Evidence / Logs / Screenshots**
![image](https://user-images.githubusercontent.com/13911593/64972227-81e1b100-d8db-11e9-9d20-59d5d9adadb5.png)

**Environment (please complete the following information):**
 - OS: [e.g. iOS10.2]
 - Frida Version [e.g. 12.7.0]
- Objection Version [e.g. 1.7.4]

**Comment by leonjza** [comment]
Hey can you connect just the normal `frida` command line utility?

**Comment by ITmustang** [comment]
I'm having same issue with the script is destroyed. i can though, connect to it using just frida 
![Screenshot from 2019-12-03 13-16-04](https://user-images.githubusercontent.com/7395551/70077526-01c01300-15cf-11ea-8ac0-a28334c0018f.png)

**Comment by ITmustang** [comment]
@i11m20n if you have frida installed through cydia, uninstall it and go here.. https://github.com/frida/frida/releases  and download appropriate version. i ended up having to run an older version of frida server on ios. i have 10.3.3 running on my test phone.

**Comment by i11m20n** [comment]
Sorry, I don't have any iOS jailbreak device at present. Could not help fix this problem.Sorry, I don't have any iOS jailbreak device at present. Could not help fix this problem.

**Comment by i11m20n** [comment]
Sorry, I don't have any iOS jailbreak device at present. Could not help fix this problem.

**Comment by leonjza** [comment]
@ITmustang do you have exactly the same stack trace? What is your version information?

**Comment by abdilahrf** [comment]
I also get this problem and still unsolved

**Comment by AYiXi** [comment]
in `/Users/ayixi/Library/Python/3.8/lib/python/site-packages/frida/core.py@get_process`
```python
  def get_process(self, process_name):
      process_name_lc = process_name.lower()
      matching = [process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
      if len(matching) == 1:
          return matching[0]
      elif len(matching) > 1:
          raise _frida.ProcessNotFoundError("ambiguous name; it matches: %s" % ", ".join(["%s (pid: %d)" % (process.name, process.pid) for process in matching]))
      else:
          raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
```

check `process_name` in `self._impl.enumerate_processes()`, for example, my process_name is `com.ninemax.ncsearchnew`, but it display as `统一代码查询`, so, edit source code to
```python
def get_process(self, process_name):
    if process_name == 'com.ninemax.ncsearchnew':
        process_name = '统一代码查询'

    process_name_lc = process_name.lower()
    matching = [process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
    if len(matching) == 1:
        return matching[0]
    elif len(matching) > 1:
        raise _frida.ProcessNotFoundError("ambiguous name; it matches: %s" % ", ".join(["%s (pid: %d)" % (process.name, process.pid) for process in matching]))
    else:
        raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
```
to debug objection, create file like this, and debug:
```python
import re
import sys
from objection.console.cli import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.argv = ['/Users/ayixi/Library/Python/3.8/bin/objection', '-g', 'com.ninemax.ncsearchnew', 'explore']
    sys.exit(cli())
```

**Comment by IPMegladon** [comment]
Marking issue as stale, feel free to reopen.
