### ISSUE TITLE
Image Injection

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#275]
Hi,

 I when I m using any iOS Device remotely 

and try to use the camera to scan any QR Code 

That time I am unable to provide QR Code image to the camera,

Using Frida can we inject  QR/BAR Code image to App using Frida
 
![screenshot-2019-09-26-07-19-48](https://user-images.githubusercontent.com/23609848/65666856-2ee6c700-e05c-11e9-9b91-a3e22df60d8b.png)

Thanks

**Comment by leonjza** [comment]
Unfortunately this sounds like something that will be very specific to an application implementation. You will need to reverse and write your own hooks for the app in question.

As for instrumenting/simulating the camera, #272 is open for that.
