### ISSUE TITLE
Hooking NSURLRequest with --dump-args crashes Objection

### ISSUE THREAD

**Issue by cakarlen** [sensepost/objection#279]
**Describe the bug**
When hooking -[NSURLRequest initWithURL:cachePolicy:timeoutInterval:], Objection will crash and terminate but will keep the app running

**To Reproduce**

1. ```ios hooking watch method "-[NSURLRequest initWithURL:cachePolicy:timeoutInterval:]" --dump-args```
2. Do something to invoke NSURLRequest
3. Objection crashes

**Expected behavior**
Obviously, this should dump the arguments of the request

**Evidence / Logs / Screenshots**
I have attached a screenshot from starting objection to the crash with --debug.
<img width="1253" alt="Bildschirmfoto 2019-10-01 um 19 30 48" src="https://user-images.githubusercontent.com/33635487/66007848-fc850180-e481-11e9-885c-cb73fc8b0820.png">

**Environment (please complete the following information):**
 - Device: iPhone 7+
 - OS: iOS 12.4
 - Frida Version: 12.7.5
- Objection Version: 1.7.5

**Comment by leonjza** [comment]
I am not sure why this would happen, and would suggest some more debugging / reversing of the target app. Chances are that one of the arguments cant be dumped the way it is being done [here](https://github.com/sensepost/objection/blob/master/agent/src/ios/hooking.ts#L144-L160).

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen
