### ISSUE TITLE
Wrong folder on plugin load

### ISSUE THREAD

**Issue by lukeasec** [sensepost/objection#287]
**Describe the bug**
When mettle plugin is not the last loaded plugin, it looks into the wrong folder when searching for the dylib.

**To Reproduce**
Run command 'plugin load mettle' when mettle is not the last loaded plugin

**Expected behavior**
dylib searched in plugins/mettle

**Screenshots**
Notice that the error goes away when flex is renamed to 0flex (therefore changing the order in the plugins folder). All those printed path are a print of `__file__` and current dir from `__init__.py` of the mettle plugin:

![image](https://user-images.githubusercontent.com/25990951/67204534-9860b800-f405-11e9-8fa7-0d151d6ffc13.png)

**Comment by leonjza** [comment]
Ooh nice catch. Thanks!
