### ISSUE TITLE
Download freezez when downloading latest frida-gadget 

### ISSUE THREAD

**Issue by NoyPCint** [sensepost/objection#288]
**Describe the bug**
I installed Objection and am trying to use it for my first time.
I'm trying to patch an apk. After entering the command specified below, 
A download of Frida gadget starts and then freezes.

**To Reproduce**
Run command
`objection patchapk --source some-app.apk
`

**Expected behavior**
I want to use the objection patchapk tool

**Evidence / Logs / Screenshots**
https://ibb.co/pvb0hXV

**Environment (please complete the following information):**
 - Device:Android Genymotion
 - OS: 7.0.0
 - Frida Version : 12.7.11
- Objection Version 1.8.1

**Additional context**
I installed all the pre-required programs, including ADB, jarsigner, and aapt**Describe the bug**
I installed objection and am trying to use it on my first time.
The download of the objection freeze when trying to patch an apk in the download frida gadget process.

**To Reproduce**

Run command
`objection patchapk --source some-app.apk
`

**Expected behavior**
I want to use the objection patchapk tool

**Evidence / Logs / Screenshots**
[](https://ibb.co/pvb0hXV
)
**Environment (please complete the following information):**
 - Device:Android Genymotion
 - OS: 7.0.0
 - Frida Version : 12.7.11
- Objection Version 1.8.1

**Additional context**

**Comment by leonjza** [comment]
The gadget gets downloaded directly from Github at the URL in the output. If it get's stuck there the only thing that I can think of would be network connectivity to Github.

**Comment by NoyPCint** [comment]
Github works in my computer, I can clone GitHub projects.
Where is the location of the frida gadget? I can download manually and move the file to the folder.

**Comment by leonjza** [comment]
Gadgets are downloaded [to](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L93-L94) `~/.objection/android/<architecture>/libfrida-gadget.so`. In the case of your screenshot it should be in the x86 architecture folder.

**Comment by NoyPCint** [comment]
I moved the frida gadget to the x86 folder, renamed it to libfrida-gadget.so but still I get the Downloading From message that freeze

**Comment by leonjza** [comment]
I don't know why. FWIW, here is the method that gets called there: https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L108-L130

**Comment by NoyPCint** [comment]
Indeed, seems that it was network issue. Thanks!
