### ISSUE TITLE
Kali Linux 2017.2 - install fail

### ISSUE THREAD

**Issue by ds2k5** [sensepost/objection#29]
Hello,
using Kali Linux 2017.2

root@kaliOS:~# pip install objection
Collecting objection
  Could not find a version that satisfies the requirement objection (from versions: )
No matching distribution found for objection

Installed python packages:
[list.txt](https://github.com/sensepost/objection/files/1362487/list.txt)

did git clone https://github.com/sensepost/objection

root@kaliOS:~# pip install /root/objection/
Processing ./objection
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-lOwQdW-build/setup.py", line 8
        def _package_files(directory: str, suffix: str) -> list:
                                    ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-lOwQdW-build/

How to fix this ?
Thanks

**Comment by leonjza** [comment]
Hey,

Make sure you are using a python3 environment. Basically, `pip3 install objection` should be all you need.

For more information, check out the installation wiki article: https://github.com/sensepost/objection/wiki/Installation#prerequisites

**Comment by ds2k5** [comment]
Thanks:

apt-get install python3-pip

**Comment by leonjza** [comment]
Assuming this is fixed now. Feel free to add more details if you are not winning.
