### ISSUE TITLE
How to pass class method arguments to heap execute?

### ISSUE THREAD

**Issue by mosherbrian** [sensepost/objection#294]
I am trying to use the Objection heap execute command to call a class method that takes a single argument. I have located the handles for the class instance and the argument instance, and the error message suggests that it is indeed trying to call the class method. It is complaining that the argument count is wrong (zero arguments passed) when it is expecting one argument. I tried a variety of ways of passing the single argument, but with no success. Reading the code for the heap execute command, it isn't clear that there is a way to pass args, but that seems strange. Is this something I am just doing wrong?

```
[usb] # android heap execute 0x2e36 onClick 0x2a3a

Handle 0x2e36 is to class d.b.a.e.H 
Executing method: onClick()
A Frida agent exception has occurred.
Error: onClick(): argument count of 0 does not match any of:
        .overload('android.view.View')
    at throwOverloadError (frida/node_modules/frida-java-bridge/lib/class-factory.js:1206)
    at a (frida/node_modules/frida-java-bridge/lib/class-factory.js:704)
    at /script1.js:9145
    at /script1.js:9433
    at frida/node_modules/frida-java-bridge/lib/vm.js:11
    at frida/node_modules/frida-java-bridge/index.js:279
    at /script1.js:9437
    at /script1.js:3010
    at /script1.js:9438
```

**Comment by leonjza** [comment]
The `execute` command is really just for methods that are simple and don't require arguments. You can imagine the difficulty when you need to pass along an `android.view.View` instance from a command line; I am not sure how that would work.

There is an alternative though. If you use the `android heap evaluate <handle>` command, a small editor will open where you can address the handle you passed through directly using the [`clazz`](https://github.com/sensepost/objection/blob/229e49272cb5799cff03864cd9c0a4215225544f/agent/src/android/heap.ts#L133) variable. This way, any pre-work (such as constructing new class instances) or anything else could be done. For example:

```javascript
[usb] # android heap evaluate 0x2e36

// clazz variable here would be the instance at 0x2e36

const i = Java.use("com.foo").$new();
const result = clazz.methodName(i);

console.log(JSON.stringify(result));
```

Once you are done editing, hit [ESC] and then [ENTER] to accept and run the small script within that context.

I am sure the overall experience could be improved of course :)

**Comment by mosherbrian** [comment]
Ah, that makes sense. With your example, I think I understand better how I can do what I am attempting using the evaluate command. Thank you!

**Comment by mosherbrian** [comment]
Using heap evaluate I was able to accomplish what I needed to. Thanks again.

**Comment by hhxdestiny** [comment]
> The `execute` command is really just for methods that are simple and don't require arguments. You can imagine the difficulty when you need to pass along an `android.view.View` instance from a command line; I am not sure how that would work.
> 
> There is an alternative though. If you use the `android heap evaluate <handle>` command, a small editor will open where you can address the handle you passed through directly using the [`clazz`](https://github.com/sensepost/objection/blob/229e49272cb5799cff03864cd9c0a4215225544f/agent/src/android/heap.ts#L133) variable. This way, any pre-work (such as constructing new class instances) or anything else could be done. For example:
> 
> ```js
> [usb] # android heap evaluate 0x2e36
> 
> // clazz variable here would be the instance at 0x2e36
> 
> const i = Java.use("com.foo").$new();
> const result = clazz.methodName(i);
> 
> console.log(JSON.stringify(result));
> ```
> 
> Once you are done editing, hit [ESC] and then [ENTER] to accept and run the small script within that context.
> 
> I am sure the overall experience could be improved of course :)

When I tried to do this, the following error was prompted, how can I solve it？Thank you!

```
Can't create handler inside thread Thread[Thread-32,10,main] that has not called Looper.prepare()
```
