### ISSUE TITLE
Frida server is not launching

### ISSUE THREAD

**Issue by karmakittenx** [sensepost/objection#295]
I am on a non rooted device and patched an apk with objection. The app successfully patched and installed ok, however, when I run the app, it continues to load without stopping on a blank screen as frida server runs. 

1. Patch apk with objection
2. Install patched apk
3. Run application and app continues to splash screen without being called. 

Expected behavior:
Launch app, app sits on blank screen, app awaits 'objection explore' command and continues as normal. 

Error: Unable to connect to the frida server: unable to connect to remote frida-server: Unexpected lack of content trying to read a line

Environment:
 - Device: Galaxy S8
 - OS: Android 9
 - Frida Version latest
- Objection Version latest

If this has already been solved, Id appreciate if you can link me there! If the app is just not possible to be used with objection then my bad.

**Comment by leonjza** [comment]
The android app patching process tries to choose a class that would most likely be run early in the application's startup. The default is to use the [launchable](https://github.com/sensepost/objection/blob/5cbb32857526d052bd9e4c06c0e4afcdb44afdd8/objection/utils/patchers/android.py#L268) activity defined in `AndroidManifest.xml` file.
(This is only a guess, but) I imagine that the default launchable activity may not be the best class to patch in your case.

An alternative would be to specify the target class that would receive the patch with the [`-t`](https://github.com/sensepost/objection/blob/772165a624d1cc9e414d53c5734166dc12115cd5/objection/console/cli.py#L332) flag on the `patchapk` command. This way, the effective `loadLibrary()` call booting Frida can be placed in a very specific class (such as one that runs when you open a specific activity). A good candidate to consider if you want this `loadLobrary()` call to happen as early as possible would be the application class defined in the `android:name` tag in the [`<application>`](https://developer.android.com/guide/topics/manifest/application-element) tag in the `AndroidManifest.xml` of your app.

**Comment by karmakittenx** [comment]
Ah thanks. Got it working fine. Apparently it was inserting the loadLibrary() too late in the class (around line 88) so I moved it up a bit and things are fine now. A few functions work, however, disabling ssl pinning says 'not throwing an exception' on the trustmanagers but I am guessing that is because it has other security precautions. Thanks anyway!

**Comment by leonjza** [comment]
That just means that the check would have normally thrown an exception (and probably propagated it up into the call stack), and we are catching it and not propagating it.

**Comment by lucaswxp** [comment]
@karmakittenx Hey there. Wouldn't the splash screen hanging means the injection works? I have this issue, but `objection explore` still doesnt work. The problem then might be the wrong activity that was automatically chosen by the apkpatcher?

**Comment by karmakittenx** [comment]
Yeah, hanging at the splash screen is the intended behavior. If your problem is that it doesn't stop and wait for the explore command, it's either you have the wrong activity or in my case, I moved up the loadLibrary call in the activity I originally had it in. Hope that helps!

**Comment by lucaswxp** [comment]
@karmakittenx Thank you, that helps. Can I ask for your help even further? I'm looking at the smali code, but I not sure how I'm supposed to "move up" the loadLibrary call, because it looks like its already in the very beginning, as you can see in the constructor:

```

# direct methods
.method static constructor <clinit>()V
   .locals 1

   .prologue
   const-string v0, "frida-gadget"

   invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V

   return-void
.end method
```

Any tips?

**Comment by lucaswxp** [comment]
@karmakittenx Sorry, I misread. You said "hanging at the splash screen is the intended behavior", that's exactly what is happening to me, but the explore command still doesn't work.

**Comment by karmakittenx** [comment]
> @karmakittenx Sorry, I misread. You said "hanging at the splash screen is the intended behavior", that's exactly what is happening to me, but the explore command still doesn't work.
> 
> ```
> Unable to connect to the frida server: need Gadget to attach on jailed Android; its default location is: /home/lucaswxp/.cache/frida/gadget-android-arm64.so
> ```

Try typing `frida -U gadget` before any commands

**Comment by karmakittenx** [comment]
> @karmakittenx Thank you, that helps. Can I ask for your help even further? I'm looking at the smali code, but I not sure how I'm supposed to "move up" the loadLibrary call, because it looks like its already in the very beginning, as you can see in the constructor:
> 
> ```
> 
> # direct methods
> .method static constructor <clinit>()V
>    .locals 1
> 
>    .prologue
>    const-string v0, "frida-gadget"
> 
>    invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V
> 
>    return-void
> .end method
> ```
> 
> Any tips?

As for this, I'm not sure since it depends per situation, like in mine, I actually had room to move it up, not sure here

**Comment by lucaswxp** [comment]
@karmakittenx Running `frida -U gadget`

Gives me:

```
Failed to spawn: unable to find process with name 'gadget'
```

Should I be running something else inside the phone/emulator?

**Comment by karmakittenx** [comment]
> @karmakittenx Running `frida -U gadget`
> 
> Gives me:
> 
> ```
> Failed to spawn: unable to find process with name 'gadget'
> ```
> 
> Should I be running something else inside the phone/emulator?

Hmm, I'm not sure, it's been a while 😅

**Comment by lucaswxp** [comment]
@karmakittenx Okay, thank you. I'll open a new issue then.

**Comment by lucaswxp** [comment]
Actually, it's this issue https://github.com/sensepost/objection/issues/456

**Comment by karmakittenx** [comment]
> Actually, it's this issue https://github.com/sensepost/objection/issues/456

Ahh

**Comment by cooliscool** [comment]
> The android app patching process tries to choose a class that would most likely be run early in the application's startup. The default is to use the [launchable](https://github.com/sensepost/objection/blob/5cbb32857526d052bd9e4c06c0e4afcdb44afdd8/objection/utils/patchers/android.py#L268) activity defined in `AndroidManifest.xml` file. (This is only a guess, but) I imagine that the default launchable activity may not be the best class to patch in your case.
> 
> An alternative would be to specify the target class that would receive the patch with the [`-t`](https://github.com/sensepost/objection/blob/772165a624d1cc9e414d53c5734166dc12115cd5/objection/console/cli.py#L332) flag on the `patchapk` command. This way, the effective `loadLibrary()` call booting Frida can be placed in a very specific class (such as one that runs when you open a specific activity). A good candidate to consider if you want this `loadLobrary()` call to happen as early as possible would be the application class defined in the `android:name` tag in the [`<application>`](https://developer.android.com/guide/topics/manifest/application-element) tag in the `AndroidManifest.xml` of your app.

Worked for me ! 
But I had to try running the app patched app 2-3 times for it to work fine.
