### ISSUE TITLE
Can objection be run directly on Android using termux?

### ISSUE THREAD

**Issue by mosherbrian** [sensepost/objection#296]
Can the objection client be run directly on Android using termux? Installing it with pip seemed like it might work but then it failed partway through. It appears that some of the frida support is available on termux though. Any idea whether this is doable?

**Comment by leonjza** [comment]
This is not something I test/build for, but if you could paste the error you got, maybe there is a small change we can make to have it work in the environment you describe.

**Comment by mosherbrian** [comment]
This seems like a bit of a rabbit hole at this point. It looks like there are a number of dependencies that are partially lacking on the termux platform currently. I think for this to work, I will need to build a number of things manually or perhaps set up a full chroot/[proot ](https://wiki.termux.com/wiki/PRoot)linux environment. If I have any success, I will let you know.

**Comment by mosherbrian** [comment]
Here's the sort of thing that I am seeing: [Frida setup-env.sh issue when building the toolchain ](https://github.com/frida/frida/issues/831)

It looks like there is no arm71 pre-built toolchain available, so the build fails. I'm not sure how much effort it is the build the toolchain. I assume it's non-trivial.

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen.
