### ISSUE TITLE
unable to get http server page

### ISSUE THREAD

**Issue by dineshdinz** [sensepost/objection#297]
**Describe the bug**
I have started the HTTP server from the file module and it started fine but I am not getting the page in the browser.

**To Reproduce**

com.test (motorola: 6.0) [usb] # **file http start**                                                                                                         
Starting server on port 9000...
[http server] Starting HTTP server in: /data/user/0/com.test/files/

I tried to access using my local IP and 127.0.0.1 but it's not showing anything. Please let me know if I am missing anything 😇.

**Expected behavior**

I tried to access using my local ip/127.0.0.01 but it's not showing anything.

**Environment (please complete the following information):**
 - Device: [e.g. Moto g2 ]
 - OS: [e.g. Android 6.0]
 - Frida Version [12.7.22]
 - Objection Version [1.8.2]

**Comment by leonjza** [comment]
Hey! Note the port in the output. The URL should be http://127.0.0.1:9000/.

**Comment by leonjza** [comment]
Apologies, ignore that previous message. You need to browse to the IP of the device as the web server starts there, on port 9000.

**Comment by dineshdinz** [comment]
Thanks @leonjza its working fine.
