### ISSUE TITLE
Question: Flex plugin is not loading

### ISSUE THREAD

**Issue by dineshdinz** [sensepost/objection#298]
**Describe the bug**
I have tried to load the flex plugin but its telling to build a libFlex.arm64.dylib file. Do we need to create or objection will generate the file. help me how to load the plugins.
**To Reproduce**

root@kali:~# objection --gadget test explore -q -P /root/flex/
Using USB device `iOS Device`
Agent injected and responds ok!
[plugin] /root/flex/__pycache__ does not appear to be a valid plugin. Missing __init__.py

com.test on (iPhone: 12.4.3) [usb] # plugin load flex                                                                             
Loaded plugin: flex

com.test on (iPhone: 12.4.3) [usb] # plugin flex load                                                                             
Flex not uploaded, uploading...
libFlex.arm64.dylib not available next to plugin file. Please build it!

**Expected behavior**
Flex should be loaded.

**Environment (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [iOS 12.4.3]
 - Frida Version [ 12.7.22]
- Objection Version [1.8.2]

#https://github.com/sensepost/objection/issues/287  

**Additional info**
I have used the below files :        
https://gist.github.com/leonjza/a138ba4d53fc5dd63f7fe12630e477f5

**Comment by leonjza** [comment]
You need to build libflex yourself and place it next to the `__init__.py` file of the plugin. The latest version of that plugin can be found [here](https://github.com/sensepost/objection/tree/master/plugins/flex) where the README has some information to get you started.
