### ISSUE TITLE
APK installation error: INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by vincentcox** [sensepost/objection#30]
I created the modified apk with:
`# objection patchapk --source com.myapk.apk --architecture arm64-v8a`

Then I tried to install the apk with:
`# adb install modified_apk.apk`

However I receive the following error:
Failed to install modified_apk.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl710965881.tmp/base.apk: Attempt to get length of null array]

Any idea's how to fix this? I also tried to manually sign it again with the following tool:
https://github.com/appium/sign
The command I used:
`# java -jar sign.jar modified_apk.apk`

**Comment by leonjza** [comment]
You may have already done this, but just to double check, did you remove the old app before installing the modified one?

**Comment by vincentcox** [comment]
Yes, I used adb uninstall name.package

**Comment by leonjza** [comment]
I am struggling to replicate a similar scenario at the moment. Could you give me some details like Android OS and if possible, the APK?

Thanks!

**Comment by rrmostert1** [comment]
I had a similar issue.  
Objection's output would indicate that patching succeeded, however, verifying with /usr/bin/jarsigner showed that the resulting APK had not been signed.

Installing the unsigned APK would result in the error message: INSTALL_PARSE_FAILED_NO_CERTIFICATES.

I traced this back to the jarsigner command being called with the wrong keystore path, i.e.
/usr/local/lib/python3.5/dist-packages/objection-1.12/py3.5.egg/objection/utils/patchers/assets/objection.jks

Instead of 
/usr/local/lib/python3.5/dist-packages/objection-1.1.12-py3.5.egg/objection/utils/assets/objection.jks

Setting the keystore variable in objection/utils/patchers/android.py to the correct path fixed the issue for me. 
The o.err check does not seem to catch this.

**Comment by leonjza** [comment]
Thanks for the detailed response @rrmostert1! I'll double check that the pathing to the keystore is being correctly calculated and fix up as needed.

**Comment by leonjza** [comment]
Yeah this is definitely a problem based on this [LoC](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L581), thanks @rrmostert1. This happened when I broke up the mobile patcher code to its own module. Hopefully, the unit tests I have been writing (and have planned for the patchers) will help prevent things like this in the future.

Patch incoming! 😄

**Comment by rrmostert1** [comment]
Thanks!

**Comment by leonjza** [comment]
Pushed https://github.com/sensepost/objection/commit/02a3ef865671b7e416361ef8fe59356312e65204 to address this. Will tag in the morning after pushing some more unit tests.

**Comment by leonjza** [comment]
Tagged and pushed [1.1.13](https://github.com/sensepost/objection/releases/tag/1.1.13) to hopefully address this. Also added a [test](https://github.com/sensepost/objection/blob/master/tests/utils/patchers/test_android.py#L124) to try and catch this in the future if needed.

**Comment by vincentcox** [comment]
Sorry for the late reply. Monday I have access to the APK, so I can test it. I will let you guys know if works, but after reading the feedback I have good faith in it.
I am amazed by the quick fixes and good responses in this thread. Thanks all in this thread!
You guys rock!

**Comment by leonjza** [comment]
I am relatively certain the bug with the keystore as identified was the problem. If not, feel free to update!

**Comment by mukarramm** [comment]
Hi, I can't find the following path to my Genymotion emulator. Where I supposed to change that and how. Sorry for my ignorance
/usr/local/lib/python3.5/dist-packages/objection-1.1.12-py3.5.egg/objection/utils/assets/objection.jks
