### ISSUE TITLE
Wrong package (not a real bug)

### ISSUE THREAD

**Issue by zafalija** [sensepost/objection#300]
**Describe the bug**
objection doesn't find jarsigner and prompts the user to donwload default-jre, but jarsigner is included in default-jdk

**To Reproduce**
Run objection on a jarsigner-missing linux system

**Expected behavior**
![Schermata da 2019-11-19 12-51-24](https://user-images.githubusercontent.com/56796741/69192510-0099db00-0b25-11ea-8fc6-6d295db4ddf7.png)

**Environment (please complete the following information):**
 - OS: latest kali linux
 - Frida Version 12.7.22
- Objection Version 1.8.2

**Comment by leonjza** [comment]
`jarsigner` just needs to be in your `PATH`.
