### ISSUE TITLE
PatchApk fails when certain languages are present in supported locales

### ISSUE THREAD

**Issue by anirudhrata** [sensepost/objection#303]
**Describe the bug**
PatchApk fails with UnicodeDecodeError when certain languages are present in the application name.

**To Reproduce**
1. Have an APK which has application name in languages such as ukranian, bulgarian etc.
2. PatchApk fails with UnicodeDecodeError with this exception: 
[objectionexception.txt](https://github.com/sensepost/objection/files/3891968/objectionexception.txt)

Looking at the exception you can see that it fails while running `aapt dump badging app.apk`
Attached is the aapt output. 
[badgdump.txt](https://github.com/sensepost/objection/files/3891954/badgdump.txt)

It fails only one some languages, Arabic works well but Ukranian fails.

I had to manually remove all such resource values and then recompile the app for PatchApk to run successfully.

**Environment (please complete the following information):**
Latest objection version, python 3.6, Windows 10

**Comment by MaciejGorczyca** [comment]
> I had to manually remove all such resource values and then recompile the app for PatchApk to run successfully.

@anirudhrata @leonjza can one of you please describe or point me somewhere that describes how do I manually patch this stuff? When I used APK Studio to "unpack" apk, I noticed it contains uk language files and it fails objection patching, cp1250.py can't read bytes above 0x80 I guess.

Attached logs below:

[logs.txt](https://github.com/sensepost/objection/files/4587140/logs.txt)

APK file:

https://drive.google.com/file/d/1BZtkxS9z1GZMc1QN4mo-k-vJTad5M_GL

**Comment by leonjza** [comment]
Unfortunately Windows support is limited. I wrote some tips to help debug patching issues here: https://github.com/sensepost/objection/wiki/Android-APK-Patching
