### ISSUE TITLE
App is not launching 

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#306]
**unable to launch the patched app in iOS Version 13.X devices**

**To Reproduce**

After installation of the patched app

1. idevicedebug -d run com.bundle.id

The app is not launching 

**Environment (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS13.2]

**Additional context**

is there any other way to launch the application and 

continue working  

This I am facing in iOS Verison 13.0 and above

In other versions, it's working as expected

**Comment by leonjza** [comment]
Best thing I can suggest is for you to view device logs for an idea why it did not launch.
