### ISSUE TITLE
Unable to Connect to Frida Server  in iOS 

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#310]
Hi, 

Unable to Connect to Frida Server

user1@user1  Desktop % objection explore
Using USB device `iPhone`
**Unable to connect to the frida server: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually**

I m getting this error while running objection explore

objection version is objection: 1.8.3

Xcode is already running for this device too.

**Comment by leonjza** [comment]
The error describes steps you can take to resolve the issue.
