### ISSUE TITLE
Unable to Run "android hooking set return_value"

### ISSUE THREAD

**Issue by mahendar441** [sensepost/objection#311]
asvid.github.io.fridaapp on (Android: 8.0.0) [usb] # android hooking set return_value asvid.github.io.fridaapp.MainActivity.checkPin
 true                                                                                                                               
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
'NoneType' object has no attribute 'replace'

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.7/dist-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.7/dist-packages/objection/commands/android/hooking.py", line 241, in set_method_return_value
    overload_filter.replace(' ', ''),
AttributeError: 'NoneType' object has no attribute 'replace'

Frida Version: 12.8.1
Objection : 1.8.3
Python: 3.7.5

**Comment by leonjza** [comment]
Thanks! Looks like we already have a PR by @root-intruder at #307 to fix this as well. I will review && merge asap.

**Comment by leonjza** [comment]
This fix is part of the 1.9.0 release now.
