### ISSUE TITLE
Ability to dump output to a file

### ISSUE THREAD

**Issue by Aniruddh-J** [sensepost/objection#314]
**Is your feature request related to a problem? Please describe.**
It more like an enhancement which would be useful.

**Describe the solution you'd like**
`ios hooking lists classes` It would be great if we can add argument like `--dump-file` which should dump all classes to a file named classes in cwd.

**Describe alternatives you've considered**
Creating a plugin?

**Comment by leonjza** [comment]
A `run` subcommand is available that you could use for this.

Eg: `objection -q run "ios hooking list classes" > class_list.txt`
