### ISSUE TITLE
Non Rooted Android Device Won't Run Frida Gadget

### ISSUE THREAD

**Issue by cpb2948** [sensepost/objection#315]
**Describe the bug**
After successfully patching an apk file to include the frida gadget, once installed on the device, I get an error message through logcat 'D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libfrida-gadget.so: deferring to libdir'.

I decompiled the patched apk and the frida gadget shared library is in the libs folder under the target architecture so its definitely there. I also just copied the .so file to all other subfolders just to be sure but I had the same error.

**To Reproduce**
1. Run command 'objection patchapk --source app.apk'
2. Run command 'adb install app.objection.apk'
3. Run the app on the device.

**Expected behavior**
The frida gadget should successfully run and I should be able to connect to it using 'objection explore'

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
objection --debug explore
[debug] Agent path is: /usr/local/lib/python3.7/site-packages/objection/agent.js
[debug] Injecting agent...
Using USB device `Samsung SM-G950U1`
[debug] Attempting to attach to process: `Gadget`
Unable to connect to the frida server: unable to connect to remote frida-server: Unexpected lack of content trying to read a line

Logcat
'D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libfrida-gadget.so: deferring to libdir'.
```

**Environment (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Frida Version 12.8.1
- Objection Version 1.8.3

**Comment by leonjza** [comment]
To be honest, I am not sure what this means. I am wondering if we are not incorrectly assuming the name of the architecture directory (`arm64-v8a` in this case) for your device?

**Comment by sebastiaanv3** [comment]
I'm experiencing the same issue on
- Device: Samsung Galaxy S7 Edge
- OS: Android 

`$ adb shell getprop ro.build.version.release`
`8.0.0`
`$ adb shell getprop ro.product.cpu.abi`
`arm64-v8a`
`$ objection --version`
`objection: 1.8.3`
`$ objection patchapk -s app.apk -Nd -a arm64-v8a`
`$ adb install app.apk`
`Performing Streamed Install`
`Success`
`$ objection explore`
`[debug] Agent path is: /usr/local/lib/python3.7/site-packages/objection/agent.js`
`[debug] Injecting agent...`
`Using USB device `Samsung SM-G935F`
[debug] Attempting to attach to process: `Gadget`
`Unable to connect to the frida server: unable to connect to remote frida-server: Unexpected lack of content trying to read a line`

However, I can't find anything in `adb logcat` related to `ApkSoSource`.
Anything I can perform to debug this anomaly?

**Comment by leonjza** [comment]
@sebastiaanv3 I think your issue may be more related to #316 .

**Comment by sebastiaanv3** [comment]
> @sebastiaanv3 I think your issue may be more related to #316 .

I'm not exactly sure it is the same issue as we do get different error messages. The latest working Frida gadget in @kamikazechaser case is 12.8.6 (cfr https://github.com/frida/frida/issues/1147) whereas in my case it is 12.8.3.
But anyway, this is highely likely a frida (gadget) issue. You can ignore my posts and thanks for your support.

**Comment by leonjza** [comment]
Narrowing down which gadget version stopped working will definitely help in figuring out what broke it, together with how to fix it. :P

**Comment by cpb2948** [comment]
@leonjza The architecture was correct. I verified it manually. Do you want me to try different version of the gadget down to a working version? I experience the same issue on a Nexus 7.

**Comment by leonjza** [comment]
Yeah. I am seeing a few reports on the Frida repository about the gadget being weird lately.
