### ISSUE TITLE
relax dependencies

### ISSUE THREAD

**Issue by blshkv** [sensepost/objection#317]
I have noticed that a strict dependency has been added in the following commit
https://github.com/sensepost/objection/commit/24c0e8effb91e44cb3f61ee206a09fd04097e984
```litecli==1.1.0```

This is not necessary probably. Please avoid a specific version requirement unless it is absolutely necessary

**Comment by leonjza** [comment]
For reference, version was pinned because of and as described [here](https://github.com/dbcli/litecli/issues/75).

**Comment by leonjza** [comment]
Relaxed in e09e7bda54e188b3119b0c3c52e6be9f4cb68860 which should land in the next tagged release.

**Comment by leonjza** [comment]
Done in 1.9.0.
