### ISSUE TITLE
Called nw_tls_create_peer_trust(), no working bypass implemented yet.

### ISSUE THREAD

**Issue by dxxzero** [sensepost/objection#318]
I tried to intercept HTTPS traffic of an iOS app, which didn't quite work. Neither with SSL Kill Switch 2 nor with objection.

Objection throws following error / message:
`Called nw_tls_create_peer_trust(), no working bypass implemented yet.`

Is it possible to implement a bypass for this method?

**Comment by leonjza** [comment]
Its a tricky one! Happy for contributions with it. In the past, it has been unreliable and actually broke more stuff instead.

**Comment by krapgras** [comment]
@leonjza I found this next code sample that seems to be working for me. It not my coding but it is already written for frida.

https://codeshare.frida.re/@dki/ios10-ssl-bypass/

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen.
