### ISSUE TITLE
patchapk fails with apktool >= 2.4.1 when META-INF/services contains files

### ISSUE THREAD

**Issue by BinaryKhaos** [sensepost/objection#319]
**Describe the bug**
apktool 2.4.1 introduced a [fix](https://github.com/iBotPeaches/Apktool/pull/2085) that breaks the patchapk functionality. 

If files in META-INF/services are present in the APK, apktool will now also put it in the root of the decoded APK's META-INF folder (as well as in original). Due to the special way objection builds the APK (apktool build -> zip appending META-INF files to built APK -> signing), this leads to duplicate files (META-INF/services/* is already in the built APK but the same files get appended again leading to duplicates).

This leads to warnings from Python's zipfile (duplicate names) and inevitably to a failure by jarsigner due to the duplicate entries.

**To Reproduce**
1. Run patchapk with apktool >= 2.4.1 on an APK which contains files in META-INF/services

**Expected behavior**
Patched and signed APK file.

**Evidence / Logs / Screenshots**
```text
Appending 43 extra entries in META-INF to the APK...
/usr/lib/python3.7/zipfile.py:1506: UserWarning: Duplicate name: 'META-INF/services/javax.servlet.ServletContainerInitializer'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
/usr/lib/python3.7/zipfile.py:1506: UserWarning: Duplicate name: 'META-INF/services/com.fasterxml.jackson.core.JsonFactory'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signing the new APK may have failed.
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: META-INF/services/javax.servlet.ServletContainerInitializer
```

**Environment (please complete the following information):**
 - Frida Version 12.8.7
 - Objection Version 1.8.3

**Comment by BinaryKhaos** [comment]
I would suggest either to delete the META-INF folder in the root before running apktool build (which is the easiest fix imho and should just work) or testing the original/META-INF/** files against the root META-INF/ and skip those that are already present.

**Comment by leonjza** [comment]
I suspect this is related: https://github.com/sensepost/objection/pull/283

**Comment by M1ck0** [comment]
I am still getting this problem. Any fixes?

**Comment by leonjza** [comment]
I have not worked on this yet, no. Happy for some help to test / PR fixes though. It may mean we need an apktool version check or forced upgrade to a supported version.

**Comment by guillaumelh** [comment]
> I would suggest either to delete the META-INF folder in the root before running apktool build (which is the easiest fix imho and should just work) or testing the original/META-INF/** files against the root META-INF/ and skip those that are already present.

@BinaryKhaos Hi, did you actually manage to fix the problem by removing the fMETA-INF/service files in the root ? I tried to erase them then run apktool again, without success.

**Comment by leonjza** [comment]
@guillaumelh did you do this in the path that gets echoed when you add the `--pause` flag?

**Comment by guillaumelh** [comment]
> @guillaumelh did you do this in the path that gets echoed when you add the `--pause` flag?

Indeed I didn't ! Build is now successful, thanks for the tip.

**Comment by dgrivera** [comment]
Any update on this?

**Comment by leonjza** [comment]
> jarsigner: unable to sign jar: java.io.FileNotFoundException: http://timestamp.digicert.com

Got an internet connection for jarsigner and the timestamp stuff? Otherwise there is very litter in that error to work from.

**Comment by leonjza** [comment]
Just pushed a commit that will force `apktool` v2.4.1 and reverted #238.

**Comment by leonjza** [comment]
Just release 1.9.0 which will force `apktool` 2.4.1. Try it out!
