### ISSUE TITLE
Objection failing with "(os/kern) protection failure" in jailbroken device

### ISSUE THREAD

**Issue by Blueeyes3** [sensepost/objection#320]
Hi Team,

Environment: Jailbroken device - iPhone Xs
                        iOS Version - 12.0.1
                        Frida version on device - 12.8.9
                        Jailbreak app - Chimera
                        Jailbreak Appstore - Chimera

When I am trying to run "objection explore" , I am facing the below error:

"Unable to connect to the frida server: unexpected error while starting thread (act_set_state returned '(os/kern) protection failure')"

But when I am trying to connect with Frida, the application gets loaded properly. And frida-ps also works fine.

Any idea on this error faced?

Thanks

**Comment by leonjza** [comment]
I think this is Frida specific for the jailbreak you have. Other issues: https://github.com/frida/frida/issues/1090 and https://github.com/frida/frida/issues/885.
