### ISSUE TITLE
output of Android byte[]

### ISSUE THREAD

**Issue by jy00055294** [sensepost/objection#325]
Such as a Byte array and Json, will be displayed as the object, the object。
[object, object] to Hex

**Comment by leonjza** [comment]
Sorry this is very little information to work with. Please use the issue templates.

**Comment by arielmiki** [comment]
Hi, can we print byte array and Json when using --dump-args and --dump-return?

**Comment by leonjza** [comment]
@arielmiki yeah that could work! happy to take a pr for it.
