### ISSUE TITLE
Not able patch apk throwing error

### ISSUE THREAD

**Issue by rakeshraks** [sensepost/objection#331]
While trying to patch the apk its throwing error. not able get exctly whats the error for.kindly help to solve this.

![objection_patching_apk_error](https://user-images.githubusercontent.com/26092136/75878944-74e05c00-5e40-11ea-84e1-de18024d89ae.png)

**Comment by leonjza** [comment]
I am not certain whats up here, but I am guessing there may be a space involved in the path and objection on Windows does not like that? Try remove that and see if it helps.

Unfortunately Windows support is a little flaky.
