### ISSUE TITLE
{ Error: EEXIST: file already exists, mkdir '/var/folders/71/2aqasja189daskjnhxp3d3twf3y1276gn/T'

### ISSUE THREAD

**Issue by zero3228** [sensepost/objection#337]
**Describe the bug**
Hello, I have multiple errors and questions here, and I had tried to fix them for the whole day, but no hope.

Command that caused the error: **objection patchipa -s patchedapp.ipa -c 53.........452**

Some errors in the command result:
Cannot resolve rpath for: @rpath/libswiftCore.dylib from /var/folders/...
Cannot resolve rpath for: @rpath/libswiftFoundation.dylib from /var/folders/...
Cannot resolve rpath for: @rpath/libswiftObjectiveC.dylib from /var/folders/...
.
.
.
Warning: Cannot resolve dependency library: /var/folders/...
Warning: missing file: @rpath/libswiftObjectiveC.dylib
Warning: missing file: @rpath/libswiftFoundation.dylib
Warning: missing file: @rpath/libswiftCore.dylib
.
.
{ Error: EEXIST: file already exists, mkdir '/var/folders/71/2aqasja189daskjnhxp3d3twf3y1276gn/T'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.zip (/usr/local/lib/node_modules/applesign/lib/tools.js:142:6)
    at <anonymous>
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/var/folders/71/2aqasja189daskjnhxp3d3twf3y1276gn/T' }
.
.
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/71/2aqasja189daskjnhxp3d3twf3y1276gn/T'/patchedapp-frida-codesigned.ipa'
.
.
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/71/2aqasja189daskjnhxp3d3twf3y1276gn/T/patchedapp-frida-codesigned.ipa'

**Environment (please complete the following information):**
 - Device: macOS Catalina
 - Frida Version 12.8.14
- Objection Version 1.8.4

Thank you.

**Comment by leonjza** [comment]
Make sure you have the latest `applesign`. This was [fixed](https://github.com/nowsecure/node-applesign/pull/90) recently.

**Comment by zero3228** [comment]
@leonjza WOw.. thank you for your very fat response! thank you thank you
