### ISSUE TITLE
Unable to connect to the frida server

### ISSUE THREAD

**Issue by nas3f** [sensepost/objection#342]
**Describe the bug**
When I use explore option it gives me error.

**To Reproduce**
1. Started Frida Server listening
2. run objection explore

**Evidence / Logs / Screenshots**

```root@kali:~/Downloads# objection explore 
Using USB device `iOS Device`
Unable to connect to the frida server: unable to launch iOS app: The operation couldn’t be completed. Application "Gadget" is unknown to FrontBoard.

```

**Environment (please complete the following information):**
 - Device: iPhone7+
 - OS: 12.1
 - Frida Version Frida 12.8.18
- Objection Version objection: 1.8.4

**Comment by leonjza** [comment]
You need to specify the target with the `--gadget` flag, described in the wiki [here](https://github.com/sensepost/objection/wiki/Running-On-A-Jailbroken-Device).

**Comment by dickyher-lab** [comment]
i am having  issue to run --gadget

full command : **objection --gadget "co.id.apple.AppStore" explore**
output : **Unable to connect to the frida server: unexpected error while preparing pipe endpoints for process with pid 1 (mach_port_allocate remote_rx returned '(os/kern) invalid task')**

device used : iphone SE 2nd Gen with iOS 13.7
JB Method : Odyssey 1.3.0
Frida Server & Frida Client Version : 14.2.14
Objection Version : 1.10.1

**Comment by leonjza** [comment]
@dickyher-lab try with vanilla Frida first

**Comment by dickyher-lab** [comment]
Ah my bad,

Its literally issue on the frida, i have tried with option **Uai**
but once, frida used with option such as **-U --codeshare [script] -f [package]**, the frida return with
**Failed to spawn: unexpected error while preparing pipe endpoints for process with pid 1 (mach_port_allocate remote_rx returned '(os/kern) invalid task')**

There are some reports on other behaviour on unc0ver method JB
in this report issues https://github.com/frida/frida-core/issues/120

I think that, i need to open issue on there.

Thanks @leonjza
