### ISSUE TITLE
APK with android:extractNativeLibs=false breaks after patching

### ISSUE THREAD

**Issue by dvalter** [sensepost/objection#351]
**Describe the bug**
Android apps with `android:extractNativeLibs=false` won't work after patching

**To Reproduce**
1. Set extractNativeLibs to false in the manifest
2. Patch that apk
3. Try to install that apk

**Expected behavior**
App will be installed

**Evidence / Logs / Screenshots**
In logcat:
` E NativeLibraryHelper: Library 'libfrida-gadget.so' is compressed - will not be able to open it directly from apk.`
In adb install output:
```
> adb install app.objection.apk 
Performing Streamed Install
adb: failed to install app.objection.apk: Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]
```

**Environment (please complete the following information):**
 - Device: AVD
 - OS: Android 10.0
 - Frida Version 12.8.20
- Objection Version 1.9.0

**Possible fix**
Remove extractNativeLibs flag from the manifest during patching

**Comment by leonjza** [comment]
Could you try using `apktool` to manually decode -> modify the manifest as suggested -> repackaging again with `apktool` and checking if it works? This should be a relatively simple check to add to the patcher though.

**Comment by StingraySA** [comment]
@dvalter I've tried to replicate your error, but with my app it succeeds, and runs on an AVD.

> <?xml version="1.0" encoding="utf-8" standalone="no"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" android:compileSdkVersion="29" android:compileSdkVersionCodename="10" package="com.sensepost.starkindustries" platformBuildVersionCode="29" platformBuildVersionName="10">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application android:allowBackup="true" android:appComponentFactory="androidx.core.app.CoreComponentFactory" android:debuggable="true" android:extractNativeLibs="false" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/AppTheme">
        <activity android:name="com.sensepost.starkindustries.MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

Can you possibly send us a copy of your full error message and maybe your manifest file?

**Comment by dvalter** [comment]
@leonjza it's exactly what I tried and it worked for me.
@StingraySA I managed to replicate the same behavior on a basic template from Android Studio. There're my apk's.
[app-debug.apk.gz](https://github.com/sensepost/objection/files/4416251/app-debug.apk.gz)
[app-debug.objection.apk.gz](https://github.com/sensepost/objection/files/4416254/app-debug.objection.apk.gz)

**Comment by leonjza** [comment]
PR #353 just landed, which will fix this in the next release! 🎉

**Comment by dvalter** [comment]
Thank you for a great tool and a quick response to this issue. I tested the APK I originally had this problem with, and now code from master patches it correctly.

**Comment by harshitshah4** [comment]
@leonjza I know this ticket is closed, but is there a way to include libfrida-gadget.so file without compression in the first place ? Modifying AndroidManifest.xml is time consuming. Probably editing apktool.yml works ?
