### ISSUE TITLE
objection failed to patch the apk [apktool 2.4.1]

### ISSUE THREAD

**Issue by Mubspatel** [sensepost/objection#352]
objection is continuously failing by saying that "apktool version should be at least 2.4.1" whereas objection already detected that apktool version is 2.4.1 What could the possible root cause of this issue?
![objection](https://user-images.githubusercontent.com/42926244/78132971-45227500-743b-11ea-8dee-3fd9c2a578d6.PNG)

**Comment by leonjza** [comment]
Duplicate of #345. Will be released in the next version later this week.
