### ISSUE TITLE
Syntax error on setting methods in watch and set commands

### ISSUE THREAD

**Issue by dineshdinz** [sensepost/objection#367]
Objection version: 1.9.1 
 iOS: 12.4.3

It may be an issue or question please help me out. 

I have tried to watch a method from the DVIA-v2 app (swift version) but getting error in syntax while setting up with watch and set commands. 

![method watch and set error](https://user-images.githubusercontent.com/16970148/80057028-4aa74280-8543-11ea-9f19-c7813dac7a0b.png)

what exactly I am doing wrong or what syntax I have to use. 

**ios hooking watch class DVIA_v2.JailbreakDetectionViewController** 
--works fine. 

**ios hooking watch method -[DVIA_v2.JailbreakDetectionViewController:jailbreakTest1Tapped]**                      
(agent) Error! Unable to find address for selector -[DVIA_v2.JailbreakDetectionViewController:jailbreakTest1Tapped]! The error was:
Error: invalid query; format is: -[NS*Number foo:bar:], +[Foo foo*] or *[Bar baz]

**Comment by leonjza** [comment]
Try placing `-[DVIA_v2.JailbreakDetectionViewController:jailbreakTest1Tapped]` in quotes: `"-[DVIA_v2.JailbreakDetectionViewController:jailbreakTest1Tapped]"`.

You can get command syntax help by prefixing the command with `help`. For example: `help ios hooking watch method`.

**Comment by dineshdinz** [comment]
Thanks works fine.
