### ISSUE TITLE
[bug] unable to find process with name 'system_server'

### ISSUE THREAD

**Issue by bradk15** [sensepost/objection#373]
So as a follow up, I was able to patch the apk under Ubuntu and I used adb to install it to the phone and that seems to work. Now according to what I've read, the app should be a blank screen until Frida is injected, but the app comes up just fine, it just can't process anything because the SSL cert from my debugging proxy is considered bad.

When I try to execute objection explore, I get a bunch of lines with the last being frida.ProcessNotFoundError: unable to find process with name 'system_server'

output from frida-ps -U

```
 PID  Name
----  ------------
7585  frida-server
7434  logcat
7491  logcat
7587  logcat
```

**Comment by leonjza** [comment]
I would expect `Gadget` in the output of `frida-ps -U` when successfully patching and running the activity that has the new/modified constructor as a result.

It could be that the activity that got patched has not run yet, or the patching actually failed. I have no idea what `frida-server` is, but you can try target that one with the `-g` flag in `objection`.
