### ISSUE TITLE
Updater causes an exception for short lived commands

### ISSUE THREAD

**Issue by leonjza** [sensepost/objection#381]
```
Exception ignored in: <function Pool.__del__ at 0x7f51b61b11f0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
```

After installing and executing the command "objection". It displays usage, arguments, but at the end an exception. Accordingly, with other cmds, too

pip3 ver `pip 20.0.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)`

python ver `Python 3.8.2`

objection ver `objection: 1.9.4`

_Originally posted by @MarshalX in https://github.com/sensepost/objection/issues/361#issuecomment-640077851_

**Comment by MarshalX** [comment]
Additional information: there are no exceptions in the home directory

**Comment by MarshalX** [comment]
<details>
  <summary>Screenshots</summary>
  
![image](https://user-images.githubusercontent.com/15520314/83948259-ae9c7680-a824-11ea-87a3-9edda5c16494.png)
![image](https://user-images.githubusercontent.com/15520314/83948264-b52aee00-a824-11ea-8670-90364097197e.png)

</details>

**Comment by leonjza** [comment]
We could just wrap [this](https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/utils/__init__.py#L57) in a try catch. It's an error that is safe to ignore anyways.
