### ISSUE TITLE
Error when patching ipa

### ISSUE THREAD

**Issue by llyouss** [sensepost/objection#384]
- Please, fill in all of the sections in this template.
- Please read each section carefully. Each has a description of what information will help.
- Windows support is limited. There is a good chance that a pull request would help!
- The more information you give, the better.
- Remove this section when you are done.

**Describe the bug**
objection patchipa --source DDSIT.ipa --codesign-signature 0C2E8200Dxxxx
objc[4412]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[4412]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Using latest Github gadget version: 12.10.4
Patcher will be using Gadget version: 12.10.4
No provision file specified, searching for one...
Found provision file /Users/llyouss/Library/Developer/Xcode/DerivedData/repackDF-ducgjaktfykwswaddafdiryraluy/Build/Products/Debug-iphoneos/repackDF.app/embedded.mobileprovision expiring in 364 days, 13:19:20.632685
Found provision file /Users/llyouss/Library/Developer/Xcode/DerivedData/Example-iOS-grxvhffnevswqffhatckiwlhjlcg/Build/Products/Debug-iphoneos/Example-iOS.app/embedded.mobileprovision expiring in 5 days, 15:55:11.632685
Found provision file /Users/llyouss/Library/Developer/Xcode/DerivedData/TouchMeIn4-bzjfcjazyybgulbpfksbstoohngd/Build/Products/Debug-iphoneos/TouchMeIn.app/embedded.mobileprovision expiring in 5 days, 17:59:59.632685
Found provision file /Users/llyouss/Library/Developer/Xcode/DerivedData/KeychainAuthenticator-hbrnspxxjblfkdcspfpiqxndnron/Build/Products/Debug-iphoneos/KeychainAuthenticator.app/embedded.mobileprovision expiring in 5 days, 18:08:23.632685
Found provision file /Users/llyouss/Library/Developer/Xcode/DerivedData/anfield-cziveavdnnqkwdfkntaihkenvhsk/Build/Products/Debug-iphoneos/anfield PRO.app/embedded.mobileprovision expiring in 4 days, 16:43:27.632685
Found a valid provisioning profile
Working with app: anfield DDSIT.app
Bundle identifier is: com.deloitte.dfg.anfield.sit
Codesigning 13 .dylib's with signature 0C2E8200Dxxxx
Code signing: libswiftCoreImage.dylib
Code signing: libswiftObjectiveC.dylib
Code signing: libswiftCore.dylib
Code signing: libswiftCoreGraphics.dylib
Code signing: libswiftUIKit.dylib
Code signing: libswiftMetal.dylib
Code signing: libswiftDispatch.dylib
Code signing: libswiftos.dylib
Code signing: libswiftCoreFoundation.dylib
Code signing: FridaGadget.dylib
Code signing: libswiftDarwin.dylib
Code signing: libswiftQuartzCore.dylib
Code signing: libswiftFoundation.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Cannot find entitlements in binary. Using defaults
Error: stdout: 
stderr: 0C2E8200Dxxxx: no identity found

command: /usr/bin/codesign --no-strict -fs 0C2E8200Dxxxx --entitlements=/var/folders/4d/36slgdp97q304l4dmxsxv77h0000gn/T/applesign/7b12b8a6-af32-47fb-a810-277464403d25/anfield DDSIT.entitlements /var/folders/4d/36slgdp97q304l4dmxsxv77h0000gn/T/DDSIT-frida.ipa.2c8dc3d5-908d-4f69-88d3-6ce2a1e2a2fe/Payload/anfield DDSIT.app/Frameworks/libswiftMetal.dylib
code: 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/applesign/lib/tools.js:47:23)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

Copying final ipa from /var/folders/4d/36slgdp97q304l4dmxsxv77h0000gn/T/DDSIT-frida-codesigned.ipa to current directory...
Traceback (most recent call last):
  File "/Users/llyouss/Desktop/repackDF/env/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/Users/llyouss/Desktop/repackDF/env/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/llyouss/Desktop/repackDF/env/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/llyouss/Desktop/repackDF/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/llyouss/Desktop/repackDF/env/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/llyouss/Desktop/repackDF/env/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/llyouss/Desktop/repackDF/env/lib/python3.7/site-packages/objection/console/cli.py", line 316, in patchipa
    patch_ios_ipa(**locals())
  File "/Users/llyouss/Desktop/repackDF/env/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 94, in patch_ios_ipa
    os.path.join(os.path.abspath('.'), os.path.basename(patcher.get_patched_ipa_path())))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/4d/36slgdp97q304l4dmxsxv77h0000gn/T/DDSIT-frida-codesigned.ipa'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/4d/36slgdp97q304l4dmxsxv77h0000gn/T/DDSIT-frida-codesigned.ipa'

**To Reproduce**
1. Run command '...'
2. Run command '...'

**Environment (please complete the following information):**
 - Device: [e.g. iPhone7]
 - OS: [e.g. iOS12.2]
 - Frida Version [12.10.4]
- Objection Version [1.9.5]

**Application**
If possible, please attach the target application where you can reproduce this bug to the issue.

**Additional context**

**Comment by DreamChaserMXF** [comment]
`0C2E8200Dxxxx ` is just an example, one should get the valid code-signature by `security find-identity -p codesigning -v` which can be found in `objection patchipa --help`

**Comment by leonjza** [comment]
@DreamChaserMXF is right.
