### ISSUE TITLE
How to completely remove frida and Objection installed files from the system. I am looking for a fresh installation

### ISSUE THREAD

**Issue by sidh104** [sensepost/objection#387]
Since i am facing a lot of multiple errors, would like to remove the existing installation of frida and objection

**Comment by leonjza** [comment]
You can use PIP's [uninstall](https://pip.pypa.io/en/stable/reference/pip_uninstall/) command: `pip uninstall objection`. Everything else is stored in `~/.objection`, so just `rm` that directory as well: `rm -Rf ~/.objection`.
