### ISSUE TITLE
device is not connected 

### ISSUE THREAD

**Issue by dineshdinz** [sensepost/objection#40]
I tried to connect android device using usb but i am getting the below error:

(virtual-python3)MacBook-Pro:~ dinz$ objection explore
Error: timed out while waiting for device to appear

*Note: Please make a overview video/blog for better understanding for starters.

**Comment by leonjza** [comment]
Hey,

Did you patch an application and start it before attempting to connect objection?

**Comment by leonjza** [comment]
For more information, the [wiki](https://github.com/sensepost/objection/wiki) has quite a bit of documentation you can refer to. I'll suggest you read the following guides for a better understanding of how objection works:

- Getting started and using objection: [Using-objection](https://github.com/sensepost/objection/wiki/Using-objection)
- Patching Android applications (if you dont have root): [Patching-Android-Applications](https://github.com/sensepost/objection/wiki/Patching-Android-Applications)
- Running on rooted Android devices: [Running-On-A-Rooted-Device](https://github.com/sensepost/objection/wiki/Running-On-A-Rooted-Device)
