### ISSUE TITLE
patched IPA error

### ISSUE THREAD

**Issue by krupalb** [sensepost/objection#402]
hello I'm getting an error after patching a IPA meant for tvOS, any idea how this can be resolved?

`dyld: dependent dylib '@executable_path/Frameworks/FridaGadget.dylib' not found for '/private/var/containers/Bundle/Application/XXXXXX/xxxx.app/Frameworks/FridaGadget.dylib' because it was built for a different platform`

**Comment by leonjza** [comment]
I haven't played with tvOS apps yet, but it looks like the app arch & gadget arch don't match.
