### ISSUE TITLE
Suggestion =]

### ISSUE THREAD

**Issue by B4RD4k** [sensepost/objection#41]
Hi,
First of all great tool, i'm using it alot!!
Secondly, would you please add --json capability to the cookies get options? it will really help =]

And please add more features :) 

great job...

**Comment by leonjza** [comment]
Hey, thanks for the suggestion. I can definitely do that!

**Comment by B4RD4k** [comment]
Thanks...

**Comment by leonjza** [comment]
Going to keep this one open so I don't forget about it.
