### ISSUE TITLE
Unable to install the patched ipa file into iOS device - AMDeviceSecureInstallApplication (ios_deploy)

### ISSUE THREAD

**Issue by ganesh2183** [sensepost/objection#412]
Unable to install the patched ipa file into iOS device

OS: MAC Catalina 10.15.5 (installed in VirtualBox)
iOS Device connected : iPhone 11 (Non-Jailbroken Phone)

Logged-in using new Apple developer ID in Xcode tool and i have created Apple Development Certificates. 

I created the new project in Xcode, build succeeded and installed successfully in iOS Device. But it fails when i try to install patched ipa to iOS device using ios-deploy tool.

I followed the steps mentioned in this link: https://github.com/sensepost/objection/wiki/Patching-iOS-Applications

**objection patchipa --source ~/Downloads/DamnVulnerableiOSApp.ipa --codesign-signature** DB788065444E6695A883E4EECE97AC215DFECD8B

Using latest Github gadget version: 12.11.17
Patcher will be using Gadget version: 12.11.17
No provision file specified, searching for one...
Found provision file /Users/babugan/Library/Developer/Xcode/DerivedData/KMBTestt-estfvctxwdlbtzemjgmxlnbzvyyu/Build/Products/Debug-iphoneos/KMBTestt.app/embedded.mobileprovision expiring in 6 days, 7:49:46.062156
Found provision file /Users/babugan/Library/Developer/Xcode/DerivedData/KMBTest-bqdaayrmrlxrnlgkpesneuvtulmr/Build/Products/Debug-iphoneos/KMBTest.app/embedded.mobileprovision expiring in 6 days, 12:42:25.062156
Found a valid provisioning profile
Working with app: DamnVulnerableIOSApp.app
Bundle identifier is: com.highaltitudehacks.dvia
Creating Frameworks directory for FridaGadget...
Codesigning 1 .dylib's with signature DB788065444E6695A883E4EECE97AC215DFECD8B
Code signing: FridaGadget.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Cannot find entitlements in binary. Using defaults

Copying final ipa from /var/folders/yl/rcc7qwfd7vlf3cpb29njhxsm0000gn/T/DamnVulnerableiOSApp-frida-codesigned.ipa to current directory...
Cleaning up temp files...

unzip DamnVulnerableiOSApp-frida-codesigned.ipa

Archive:  DamnVulnerableiOSApp-frida-codesigned.ipa
   creating: Payload/DamnVulnerableIOSApp.app/
   creating: Payload/DamnVulnerableIOSApp.app/_CodeSignature/
  inflating: Payload/DamnVulnerableIOSApp.app/_CodeSignature/CodeResources  
  inflating: Payload/DamnVulnerableIOSApp.app/main-bg.png  
  inflating: Payload/DamnVulnerableIOSApp.app/card-bg.png  
 extracting: Payload/DamnVulnerableIOSApp.app/menuIcon.png  
   creating: Payload/DamnVulnerableIOSApp.app/en.lproj/
  inflating: Payload/DamnVulnerableIOSApp.app/en.lproj/InfoPlist.strings  
  inflating: Payload/DamnVulnerableIOSApp.app/640_960_SplashScn.png  
  inflating: Payload/DamnVulnerableIOSApp.app/152x152.png  
   ....

**codesign -v --verbose DamnVulnerableIOSApp.app** 
DamnVulnerableIOSApp.app: valid on disk
DamnVulnerableIOSApp.app: satisfies its Designated Requirement

**ios-deploy --bundle DamnVulnerableIOSApp.app -d -v -W**   
[....] Waiting for iOS device to be connected
Handling device type: 1
Already found device? 0
Hardware Model: N104AP
Device Name: Cloud Keybank iPhone 11 ID:151
Model Name: iPhone 11
SDK Name: iphoneos
Architecture Name: arm64e
Product Version: 13.5.1
Build Version: 17F80
[....] Using 00008030-000E21DA3AF0802E (N104AP, iPhone 11, iphoneos, arm64e) a.k.a. 'Cloud iPhone 11 ID:151'.
------ Install phase ------
[  0%] Found 00008030-000E21DA3AF0802E (N104AP, iPhone 11, iphoneos, arm64e) a.k.a. 'Cloud iPhone 11 ID:151' connected through USB, beginning install
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/META-INF/ to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/META-INF/com.apple.ZipMetadata.plist to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/_CodeSignature/ to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/_CodeSignature/CodeResources to device
[  5%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/main-bg.png to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/card-bg.png to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/menuIcon.png to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/en.lproj/ to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/en.lproj/InfoPlist.strings to device
[  6%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/640_960_SplashScn.png to device
[  7%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/152x152.png to device
[  7%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/640x1136_SplashScn.png to device
[  7%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/120x120.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/AppIcon60x60@2x.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/slider-bg.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/AppIcon40x40@2x.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/menuIcon@2x.png to device
[  8%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/slider-active@2x.png to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/card-bg@2x.png to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/ to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/ to device
[  9%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/g9c-Ju-vFC-view-IFp-rO-8Ad.nib to device
[ 10%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/cLD-LZ-seZ-view-4QP-f7-Xbj.nib to device
[ 10%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Base.lproj/Main.storyboardc/UIViewController-5xJ-MS-CJp.nib to device
...
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/Info.plist to device
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/menu-icon@2x.png to device
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/57x57.png to device
[ 49%] Copying /Users/babugan/Downloads/Payload/DamnVulnerableIOSApp.app/PkgInfo to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2020-09-24 04:06:05.229 **ios-deploy[2865:916828] [ !! ] Error 0xe8008001: An unknown error has occurred. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)**

Not sure the reason for this error from ios_deploy tool.

Similarly when check for other pathed ipa file,
codesign -v --verbose KMB_QV2.app 
KMB_QV2.app: code object is not signed at all
In architecture: arm64

Need your help to resolve this issue.

**Comment by ganesh2183** [comment]
Could anyone help on this issue.

Unable to install ipa file in ios device after resign.

**Comment by leonjza** [comment]
I can replicate the problem with the DamnVulnerableiOSApp's, which appear to be a codesigning related error that you can see in Console.app. I don't know why yet.

**Comment by ganesh2183** [comment]
How to fix this issue ??

**Comment by Divya-Kothavari** [comment]
I am also facing same issue. Please let me know how to resolve this issue.

**Comment by leonjza** [comment]
My theory atm is that something has changed signing wise, possibly with free accounts. Will have to test with a paid account to verify.

**Comment by ganesh2183** [comment]
Installed resigned ipa file in iOS device sucessfully.

objection patchipa --source ~/Downloads/Sep_Reg_20200911_1.ipa --codesign-signature 3FD71D844BDC3848961ABAC2DD3A6DB9D65A8750
Checking for a newer version of objection...
Using latest Github gadget version: 12.11.18
Patcher will be using Gadget version: 12.11.18
No provision file specified, searching for one...
Found provision file /Users/babugan/Library/Developer/Xcode/DerivedData/kmb_QV-ekdjjnotvgkbekeilzhxnpevoqtc/Build/Products/Debug-iphoneos/kmb QV.app/embedded.mobileprovision expiring in 365 days, 1:23:26.157498
Found provision file /Users/babugan/Library/Developer/Xcode/DerivedData/KeyBank-csluijbhocxtonfpurbqpnrzralq/Build/Products/Debug-iphoneos/KeyBank.app/embedded.mobileprovision expiring in 358 days, 8:37:23.157498
Found a valid provisioning profile
Working with app: KMB_QV2.app
Bundle identifier is: com.key.kmb.dev.qv1
Codesigning 8 .dylib's with signature 3FD71D844BDC3848961ABAC2DD3A6DB9D65A8750
Code signing: libswiftObjectiveC.dylib
Code signing: libswiftCore.dylib
Code signing: libswiftCoreGraphics.dylib
Code signing: libswiftDispatch.dylib
Code signing: libswiftCoreFoundation.dylib
Code signing: FridaGadget.dylib
Code signing: libswiftDarwin.dylib
Code signing: libswiftFoundation.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Cannot find entitlements in binary. Using defaults
Cannot resolve rpath for: @rpath/MiSnapBarcodeScanner.framework/MiSnapBarcodeScanner from /var/folders/yl/rcc7qwfd7vlf3cpb29njhxsm0000gn/T/Sep_Reg_20200911_1-frida.ipa.4dd76bdc-8e3a-4c69-87b8-0317cf096735/Payload/KMB_QV2.app/Frameworks/MiSnapSDK.framework/MiSnapSDK
Warning: Cannot resolve dependency library: /var/folders/yl/rcc7qwfd7vlf3cpb29njhxsm0000gn/T/Sep_Reg_20200911_1-frida.ipa.4dd76bdc-8e3a-4c69-87b8-0317cf096735/Payload/KMB_QV2.app/Frameworks/MiSnapSDK.framework/MiSnapSDK
Warning: missing file: @rpath/MiSnapBarcodeScanner.framework/MiSnapBarcodeScanner

Copying final ipa from /var/folders/yl/rcc7qwfd7vlf3cpb29njhxsm0000gn/T/Sep_Reg_20200911_1-frida-codesigned.ipa to current directory...
Cleaning up temp files...


When i run objection command i receive below error message,

**objection explore**
Using USB device `iPhone`
Traceback (most recent call last):
  File "./objection", line 10, in <module>
    sys.exit(cli())
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/objection/utils/agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Users/babugan/Library/Python/3.7/lib/python/site-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.InvalidArgumentError: unable to find app with bundle identifier “Gadget”


So i included --gadget command, then i receive the error message as "Unable to connect to the frida server..",

**objection --gadget KMB_QV2 explore**
Using USB device `iPhone`
Unable to connect to the frida server: unable to attach to the specified process

What could be the reason, How to fix this issue ??

**frida-ps -U** command is working fine.

**Comment by leonjza** [comment]
@ganesh2183 nice to it looks like a paid developer account works. Not great news for folks that don't have one though.

As for the error, by default objection tries to attach to a process called `Gadget`. You can change that to one from the `frida-ps -U` output using the `--gadget` flag. eg. `objection --gadget <name> explore`.

**Comment by ganesh2183** [comment]
Yes.

i tried **objection --gadget KMB_QV2 explore**
Using USB device iPhone
Unable to connect to the frida server: unable to attach to the specified process

What could be the reason, How to fix this issue ??

**Comment by leonjza** [comment]
Try the package name: `com.key.kmb.dev.qv1`

**Comment by ganesh2183** [comment]
No it also failed to execute as expected

**objection --gadget "com.key.kmb.dev.qv1" explore**
Using USB device `iPhone`
Unable to connect to the frida server: failed to get the task for process 2401

Also this is Non-Jailbroken device.

Do we need to install frida-server in Non-jailbroken ios device ?

**Comment by leonjza** [comment]
You will have to check the devices crashlog for more information to debug that. Maybe you are facing some anti-frida protections.

Patching an app embeds the frida-gadget which is the server. You dont have to install frida-server.

**Comment by leonjza** [comment]
What is the output of `frida-ps -Uai`? It could be that the gadget did not start. The device  logs should tell you why.

**Comment by ganesh2183** [comment]
**frida-ps -Uai**  
 PID  Name                                   Identifier                                              
----  -------------------------------------  --------------------------------------------------------
 425  EscrowSecurityAlert                    com.apple.EscrowSecurityAlert                           
 519  Gmail                                  com.google.Gmail                                        
2298  KMB_QV2                                com.key.kmb.dev.qv1                                     
2268  PMConfigManager                        42S4GZUXGS.PMConfigManager                              
2260  PMDriver-Runner                        com.facebook.WebDriverAgentRunner.xctrunner             
2285  Settings                               com.apple.Preferences                                   
 368  Siri Search                            com.apple.Spotlight                                     
  62  SpringBoard                            com.apple.springboard                                   
 579  TestFlight                             com.apple.TestFlight                                    
 438  Translate                              com.apple.Translate                                     
   -  AXUIViewService                        com.apple.AXUIViewService                               
   -  AccountAuthenticationDialog            com.apple.AccountAuthenticationDialog                   
   -  App Store                              com.apple.AppStore                                      
   -  AppSSOUIService                        com.apple.AppSSOUIService 

....


How to start gadget ??

**Comment by leonjza** [comment]
With that output it looks like you have a jailbroken phone running frida-server already, so the Gadget process will never appear. There is no need to patch the app, and running a patched app will fail to start the gadget because frida-server running. To help understand this, please check out the wiki [here](https://github.com/sensepost/objection/wiki/Running-On-A-Jailbroken-Device).

**Comment by leonjza** [comment]
> With that output it looks like you have a jailbroken phone running frida-server already

Apologies about this one. Looks like the behaviour of `frida-tools` (and by extention `frida` & `frida-ps`) has changed since I last tested it.

Unfortunately you will have to debug locally why the Gadget is not starting (again, device logs the Console app should help you). What you should see when it works is something like this:

```
$ frida-ps -Uia | grep Gadget
23691  Gadget                                 re.frida.Gadget
```

```
$ objection explore
Checking for a newer version of objection...
Using USB device `iPhone`
Agent injected and responds ok!

     _   _         _   _
 ___| |_|_|___ ___| |_|_|___ ___
| . | . | | -_|  _|  _| | . |   |
|___|___| |___|___|_| |_|___|_|_|
      |___|(object)inject(ion) v1.9.6

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
za.sensepost.ipewpew on (iPhone: 14.0.1) [usb] #
```

**Comment by leonjza** [comment]
Some good news. I managed to find a workaround that got me to sign DVIA-swift and run in on a non-jailbroken iOS 14 device with a free Apple account. The steps are:

- Patch the application as you would with objection
- Resign the application again using https://github.com/DanTheMan827/ios-app-signer
- Deploy and run as normal with ios-deploy.

🎉

**Comment by ganesh2183** [comment]
Thanks for the update.

Let me try from my end and confirm.

**Comment by dipti-code** [comment]
@leonjza I have tried the same method as you mentioned but  getting this issue while running 

objection -g com.hackerdipti.democode explore
and the app i installed using ios-deploy also showing "error: failed to get the task for process 526"

Unable to connect to the frida server: failed to get the task for process 526

The complete log can be found #421
