### ISSUE TITLE
This looks like a code related error

### ISSUE THREAD

**Issue by YiJ-debug** [sensepost/objection#416]
# android heap execute 0x2356                                           
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
list index out of range

Python stack trace: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.0/lib/python3.8/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/root/.pyenv/versions/3.8.0/lib/python3.8/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/root/.pyenv/versions/3.8.0/lib/python3.8/site-packages/objection/commands/android/heap.py", line 118, in execute
    method = args[1]
IndexError: list index out of range

**Comment by leonjza** [comment]
Could you fill in the issue template details please?

**Comment by leonjza** [comment]
I am assuming you did not give the function to call on the handle, and the command validation could be more verbose about it.

Try `android heap execute <handle> <function>`

**Comment by YiJ-debug** [comment]
yes, thanks reply. but i see other one use this like "android heap execute  <handle>", then, it will output "(The handle at `0xxxxx` will be available as the `clazz` variable.)",but when i try it, i can't get this result, i get an error, like submitted above.

**Comment by YiJ-debug** [comment]
like this:  www.anquanke.com/post/id/197657#h3-4, when u open it, u can search "android heap evaluate 0x2526", then u will see it.

**Comment by leonjza** [comment]
`evalute` will drop you in a small editor to write some JavaScript for a handle. `execute` lets you execute a function on a handle.

**Comment by YiJ-debug** [comment]
ohh, it's my wrong, thank u very much.
