### ISSUE TITLE
[bug]apktool is not ready for use in Kali

### ISSUE THREAD

**Issue by Crashbite** [sensepost/objection#418]
**Describe the bug**
apktool is not ready for use

**To Reproduce**
objection patchapk -s .\base.apk

**Evidence / Logs / Screenshots**
The stacktrace I had :

random@KALI:~/Pentest$ sudo objection patchapk -s se.random.random_2020-08-18.apk
[sudo] password for random: 
Checking for a newer version of objection...
No architecture specified. Determining it using `adb`...
Detected target device architecture as: x86_64
Using latest Github gadget version: 12.11.18
Patcher will be using Gadget version: 12.11.18
Detected apktool version as: 2.4.1-dirty
apktool version should be at least 2.4.1
Please see the following URL for more information: https://github.com/sensepost/objection/wiki/Apktool-Upgrades
apktool is not ready for use
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmp2a3trf2p.apktemp.objection.apk'

**Environment (please complete the following information):**

Device: Galaxy Tab s3
OS: Distributor ID:	Kali Description:	Kali GNU/Linux Rolling Release:	2020.3

Frida: /frida-server-12.11.18-android-x86_64 
Objection Version objection: 1.9.6

**Comment by leonjza** [comment]
upgrade apktool as described in the wiki [here](https://github.com/sensepost/objection/wiki/Apktool-Upgrades)
