### ISSUE TITLE
Python Errors

### ISSUE THREAD

**Issue by rustymagnet3000** [sensepost/objection#42]
![image](https://user-images.githubusercontent.com/5367141/33278409-680c514e-d393-11e7-8ba8-e6750193f47c.png)

**Comment by rustymagnet3000** [comment]
`which python`
/usr/bin/python

`which objection`
/usr/local/bin/objection

Is anybody else getting a lot of python crashes while using Objection?  When I use just Frida I don't get these crashes.  These don't seem to cause an issue as Objection still works.

**Comment by leonjza** [comment]
This is a [known issue](https://bugs.python.org/issue30837) with `python` on High Sierra based when making use of `multiprocessing` (which objection does).

If you want to revert to the old way of how `fork`'s etc were handled, you can `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` in your shells startup script.
