### ISSUE TITLE
Patching IPA Not Working for my iPhone

### ISSUE THREAD

**Issue by dipti-code** [sensepost/objection#422]
- Please, fill in all of the sections in this template.
- Please read each section carefully. Each has a description of what information will help.
- Windows support is limited. There is a good chance that a pull request would help!
- The more information you give, the better.
- Remove this section when you are done.

**Describe the bug**
1-->Downloadedthe ipa file from appstore uploaded app.
2-->Tryig to follow the process using the patching of ipa as mentioned

**To Reproduce**
1. Run command '...'

objection patchipa --source /Users/xxxx/Documents/AAAA/whatsapp/xxxx.ipa   --codesign-signature 53E8C2D187Axxxxxxxxx

2. Run command '...'

**Similar issues**
Please link the issues in this repository that is similar to yours.

For example: #358, #229 etc.

Codesigning patched IPA...
Error: This IPA is encrypted
    at Applesign.signAppDirectory (/usr/local/lib/node_modules/applesign/index.js:137:15)
    at Applesign.signIPA (/usr/local/lib/node_modules/applesign/index.js:100:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/usr/local/lib/node_modules/applesign/bin/applesign.js:55:7)

**Expected behavior**

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
objection --debug explore
```

**Environment (please complete the following information):**
 - Frida Version [e.g. 22]
- Objection Version [e.g. 1.6.2]

**Application**
If possible, please attach the target application where you can reproduce this bug to the issue.

**Additional context**

**Comment by leonjza** [comment]
> Error: This IPA is encrypted

It is not possible to patch encrypted IPA's.

**Comment by dipti-code** [comment]
@leonjza  so we can not patch encrypted iPA's. but any other way if we have. Like for android we can pactched which was downloaded from play store.
So only ioS has the. solution for jail breaking as solution?

**Comment by leonjza** [comment]
The only way is to strip DRM using a jailbroken device and something like bfinject first.
