### ISSUE TITLE
Print []byte (byte array) in hexdump format instead of array of numbers

### ISSUE THREAD

**Issue by aj3423** [sensepost/objection#429]
**Is your feature request related to a problem? Please describe.**
When printing function arguments or return values, print byte array in hexdump format instead of  [-111, 2, 33, ....]
 
**Describe the solution you'd like**
Hexdump like Frida's  `console.log(hexdump(data, { length: data_len, header: false, ansi: true }));`

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by leonjza** [comment]
We could add a flag that dumps hex instead of parsed values yeah. Happy to accept a PR!
