### ISSUE TITLE
KeyChain dump missing protection class attributes when TouchID or FaceID is used for authentication 

### ISSUE THREAD

**Issue by antoniozekic** [sensepost/objection#43]
Is it possible to modify the «https://github.com/sensepost/objection/blob/master/objection/hooks/ios/keychain/dump.js» in order to list the keychain items and their attributes when TouchID or FaceID s used for authentication?

I can see that even when exported to *.json, some of the protection class attributes are not listed properly or missing completely.

MWR needle has a great example (I'm using this script currently): https://github.com/mwrlabs/needle/blob/master/needle/modules/storage/data/keychain_dump_frida.py

**Comment by leonjza** [comment]
Thanks for the report!

Ill have to test this as the TouchID flag parsing logic exists, but definitely not the FaceID stuff. It may be that the TouchID flags don't parse correctly making it look like it does not exist at all in the first place.

Will look into it asap!

**Comment by antoniozekic** [comment]
Thanks for considering. It's such a great application and a lifesaver. I've used it recently for testing an application using FaceID authentication and I've also tested the same functionality (same application) that uses TouchID in order to confirm that the issue exists with both TouchID and FaceID. I think the problems is basically the same for types of authentication, no difference at all.

**Comment by bernard-wagner** [comment]
Strange. Will need to test again, used it on a project a few weeks ago and worked as expected. I wrote the Needle module and ported the code to Objection, so should work the same. Might have messed something up when we refactored the ACL parsing for Objection.

**Comment by antoniozekic** [comment]
@leonjza @bernard-wagner Have you had the chance to look into it?

**Comment by leonjza** [comment]
Apologies @antoniozekic, things are a little headless chicken at the moment. This is still on my list though!

**Comment by antoniozekic** [comment]
@leonjza Have you maybe had the chance to look into this issue?

**Comment by leonjza** [comment]
Sadly not. I might still have Xcode open somewhere in-between the 1000 windows I have open.. ;)
On a more serious note, this is definitely a high priority for me, so the moment I can spare some time I will get to it.

**Comment by leonjza** [comment]
Finally took a closer look at this. I don't have an iPhone X device with me to test properly so my results may be skewed but I suspect there is no difference in the `SecAccessControlRef` for a keychain entry based on TouchID / FaceID.

The ACL header file has a deprecation for `kSecAccessControlTouchIDAny` and a replacement for `kSecAccessControlBiometryAny` which both have the same value.

```text
$ grep -A 12 "typedef CF_OPTIONS(CFOptionFlags, SecAccessControlCreateFlags)" /System/Library/Frameworks/Security.framework/Versions/A/Headers/SecAccessControl.h

typedef CF_OPTIONS(CFOptionFlags, SecAccessControlCreateFlags) {
    kSecAccessControlUserPresence           = 1u << 0,
    kSecAccessControlBiometryAny            CF_ENUM_AVAILABLE(10_13_4, 11_3) = 1u << 1,
    kSecAccessControlTouchIDAny             API_DEPRECATED_WITH_REPLACEMENT("kSecAccessControlBiometryAny", macos(10.12.1, 10.13.4), ios(9.0, 11.3)) = 1u << 1,
    kSecAccessControlBiometryCurrentSet     CF_ENUM_AVAILABLE(10_13_4, 11_3) = 1u << 3,
    kSecAccessControlTouchIDCurrentSet      API_DEPRECATED_WITH_REPLACEMENT("kSecAccessControlBiometryCurrentSet", macos(10.12.1, 10.13.4), ios(9.0, 11.3)) = 1u << 3,
    kSecAccessControlDevicePasscode         CF_ENUM_AVAILABLE(10_11, 9_0) = 1u << 4,
    kSecAccessControlOr                     CF_ENUM_AVAILABLE(10_12_1, 9_0) = 1u << 14,
    kSecAccessControlAnd                    CF_ENUM_AVAILABLE(10_12_1, 9_0) = 1u << 15,
    kSecAccessControlPrivateKeyUsage        CF_ENUM_AVAILABLE(10_12_1, 9_0) = 1u << 30,
    kSecAccessControlApplicationPassword    CF_ENUM_AVAILABLE(10_12_1, 9_0) = 1u << 31,
} __OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);
```

On my TouchID capable device with iOS 11.3, the contents of `kSecAttrAccessControl` on a keychain item matched for both `kSecAccessControlTouchIDAny` / `kSecAccessControlBiometryAny` and `kSecAccessControlTouchIDCurrentSet` / `kSecAccessControlBiometryCurrentSet`. This could very well be because my device simply doesn't have FaceID support.

```text
# kSecAccessControlTouchIDAny

DEBUG: <SecAccessControlRef: 0x1c422e4a0>
{
    od =     {
        cbio =         {
            pbioc = <d7396a15 7cf03283 22f28644 5f4957b9>;
        };
    };
    odel = 1;
    oe = 1;
}

# kSecAccessControlBiometryAny

DEBUG: <SecAccessControlRef: 0x1c4235420>
{
    od =     {
        cbio =         {
            pbioc = <d7396a15 7cf03283 22f28644 5f4957b9>;
        };
    };
    odel = 1;
    oe = 1;
}

# kSecAccessControlTouchIDCurrentSet

DEBUG: <SecAccessControlRef: 0x1c04271c0>
{
    od =     {
        cbio =         {
            pbioc = <d7396a15 7cf03283 22f28644 5f4957b9>;
            pbioh = <2d3a389d 581bd40e bd652f34 17777fcf 657e2b4a 15405d55 d01fadba 0714808a>;
        };
    };
    odel = 1;
    oe = 1;
}

# kSecAccessControlBiometryCurrentSet

DEBUG: <SecAccessControlRef: 0x1c042bc80>
{
    od =     {
        cbio =         {
            pbioc = <d7396a15 7cf03283 22f28644 5f4957b9>;
            pbioh = <2d3a389d 581bd40e bd652f34 17777fcf 657e2b4a 15405d55 d01fadba 0714808a>;
        };
    };
    odel = 1;
    oe = 1;
}
```

An example dump with `kSecAccessControlBiometryAny` set is:

```json
[
  {
    "item_class": "kSecClassGenericPassword",
    "create_date": "2018-06-13 08:54:54 +0000",
    "modification_date": "2018-06-13 08:54:54 +0000",
    "description": "",
    "comment": "",
    "creator": "",
    "type": "",
    "script_code": "",
    "alias": "",
    "invisible": "",
    "negative": "",
    "custom_icon": "",
    "protected": "",
    "access_control": "kSecAccessControlTouchIDAny",
    "accessible_attribute": "kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly",
    "entitlement_group": "8AH3PS2AS7.za.sensepost.ipewpew",
    "generic": "credentials",
    "service": "",
    "account": "credentials",
    "label": "",
    "data": "<62706c69 73743030 d4010203 0405061d 1e582476 65727369 6f6e5824 6f626a65 63747359 24617263 68697665 72542474 6f701200 0186a0a7 07081314 15161755 246e756c 6cd3090a 0b0c0f12 574e532e 6b657973 5a4e532e 6f626a65 63747356 24636c61 7373a20d 0e800280 03a21011 80048005 80065875 7365726e 616d6558 70617373 776f7264 52762051 63d21819 1a1b5a24 636c6173 736e616d 65582463 6c617373 65735c4e 53446963 74696f6e 617279a2 1a1c584e 534f626a 6563745f 100f4e53 4b657965 64417263 68697665 72d11f20 54726f6f 74800108 111a232d 32373f45 4c545f66 696b6d70 7274767f 888b8d92 9da6b3b6 bfd1d4d9 00000000 00000101 00000000 00000021 00000000 00000000 00000000 000000db>"
  }
]
```

Going to leave this one open until I can get my hands on a FaceID capable device to test further.

**Comment by leonjza** [comment]
Got my hands on a FaceID capable device and can confirm my original findings are true. So, the question now really is, do we want to rename the `kSecAccessControlTouchIDAny` and `kSecAccessControlTouchIDCurrentSet` attributes in the dumper to their newer `Biometry` equivalents?

**Comment by antoniozekic** [comment]
I don't think it's necessary, it's just important that the `accessible_attribute` is always displayed (even without json dump).
Or if possible to display the attributes according to the device ID.

**Comment by leonjza** [comment]
In my testing so far, the `accessible_attribute` is only empty when running in a simulator or the keychain entry doesn't have any `kSecAttrAccessControl` attributes set.

**Comment by leonjza** [comment]
Awesome. Lets close for now and see if another test case pops up later! Thanks!
