### ISSUE TITLE
patchapk support for xapk

### ISSUE THREAD

**Issue by WanghongLin** [sensepost/objection#431]
Some apps or games are packaged in xapk format and has multiple apks. After make patching for main apk with objection, other apks should sign with the same jks manually. Otherwise the installation will failed with signature mismatch.

```sh
$ apksigner sign --ks /path/to/objection/objection/utils/assets/objection.jks --ks-pass pass:basil-joule-bug config.arm64_v8a.apk objection
```

Can the command `patchapk` support xapk, also sign other apks (e.g config.arm64_v8a.apk) automatically with same key?

Or `patchapk` support apk without launched Activity?

If I try to patch other apks (e.g config.arm64_v8a.apk) which doesn't have launched activity, I got the following error.
`Unable to determine the launchable activity for this app.`

**Comment by leonjza** [comment]
Version 1.10 got the `signapk` command to let you sign other apk's with the same jks.

https://github.com/sensepost/objection/releases/tag/1.10.0
