### ISSUE TITLE
Cannot install the generated ipa file (free apple account)

### ISSUE THREAD

**Issue by fuomag9** [sensepost/objection#434]
With any IPA file I try to create via object by following the guide, when I install them via ios-deploy I always get 2020-12-21 00:42:52.144 ios-deploy[21397:128522] [ !! ] Error 0xe8008001: An unknown error has occurred. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by fuomag9** [comment]
https://github.com/nowsecure/node-applesign/issues/113 Seems to be related and I had the same issues

**Comment by fuomag9** [comment]
How I made stuff work (the exact steps):
- Dumped the ipa from my ipad
- added iPhone12,1 to the supported devices in the plist file
- zipped the file and renamed it to .ipa
- used objection to patch the ipa
- resigned the ipa with https://github.com/nowsecure/node-applesign/issues/113#issuecomment-728944761
- unzipped the resigned ipa
- deployed via ios-deploy

**Comment by weev3** [comment]
same issue here. #428 . This error message got only after updating applesign. Below link will fix code signing problem. https://medium.com/@dinezh.shetty/setting-up-frida-without-jailbreak-on-devices-running-latest-ios-12-4-27c7cfa6c9a2 
After installing ipa with `ios-deploy`, run `objection explore` and you are good to go. 
(note: download latest frida gadget lib file.)

**Comment by leonjza** [comment]
Some progress was made on this, with changes that objection would need mentioned here: https://github.com/nowsecure/node-applesign/issues/113#issuecomment-790764961
