### ISSUE TITLE
Unable to codesign patched ipa 

### ISSUE THREAD

**Issue by r3tribut0r** [sensepost/objection#437]
[Description]
I am unable to code sign a Frida-patched IPA (DVIA-v2) in this case even with iOS app signer.
I use the command:
objection patchipa --source ./DVIA-v2-swift.ipa --codesign-signature 0627[snipped] --skip-cleanup

[Environment]
Mobile - iPhone 11 (iOS 14.2)

[Steps to reproduce]
1. Download the DVIA-v2 from https://github.com/prateek147/DVIA-v2/blob/master/DVIA-v2-swift.ipa
2. Used objection command: objection patchipa --source ./DVIA-v2-swift.ipa --codesign-signature 0627[...snipped...] --skip-cleanup
2. Get the DVIA-v2-swift-frida.ipa from the temp folder location (in my case: /var/folders/qg/1kyt55455sg_7sk9js7l6jdw0000gn/T/DVIA-v2-frida.ipa)
3. Sign using the iOS App Signer (https://dantheman827.github.io/ios-app-signer/)
4. Unzip the signed IPA and use iOS deploy command: ios-deploy --bundle Payload/*.app --debug -W
5. The deployed app installs but iOS deploy shows with error: (lldb) error: failed to get the task for process 882
6. Attempting to use Objection -g "com.temp.name" explore, I get the message: Unable to connect to the frida server: failed to get the task for process 882

**Evidence / Logs / Screenshots**
```text
me@macbook tmp % objection -d -g "com.hangkan.dangkan" explore
[debug] Agent path is: /Library/Python/3.8/site-packages/objection/agent.js
[debug] Injecting agent...
Using USB device `iPhone`
[debug] Attempting to attach to process: `com.hangkan.dangkan`
[debug] Unable to find process: `com.hangkan.dangkan`, attempting spawn
Unable to connect to the frida server: failed to get the task for process 908

me@macbook tmp % frida-ps -Uai | grep angkan
908  DVIA-v2                                com.hangkan.dangkan 
```

**Environment (please complete the following information):**
 - Device: [iPhone11]
 - OS: [e.g. iOS14.2]
 - Frida Version [e.g. 14.2.3]
- Objection Version [e.g. 1.9.6]

**Comment by leonjza** [comment]
How sure are you this is a code signing issue? Have you tried just vanilla `frida` tools?

**Comment by r3tribut0r** [comment]
Figured it out.
So basically in iOS App Signer I needed to uncheck the flag 'No get-task-allow'. 
This is not an issue with objection but since applesign was not working I has to fallback to iOS App Signer and unchecking the aforementioned setting helped me connect to the gadget.
