### ISSUE TITLE
Hooking an entire class is not working as expected 

### ISSUE THREAD

**Issue by rypz79** [sensepost/objection#442]
following [this tutorial](https://book.hacktricks.xyz/mobile-apps-pentesting/android-app-pentesting/frida-tutorial/objection-tutorial#hooking-watching-an-entire-class)  
I tried:
```
roey@HP-Spectre-x360-13:~$ objection --gadget "com.goldtouch.ynet" explore                   
Using USB device `SM-N975F`
Agent injected and responds ok!

     _   _         _   _
 ___| |_|_|___ ___| |_|_|___ ___
| . | . | | -_|  _|  _| | . |   |
|___|___| |___|___|_| |_|___|_|_|
      |___|(object)inject(ion) v1.10.1

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
com.goldtouch.ynet on (samsung: 11) [usb] # android hooking watch class com.goldtouch.ynet.ui.activities.StoryActivity --dump-args --dump-return
(agent) Hooking com.goldtouch.ynet.ui.activities.StoryActivity.access$000(com.goldtouch.ynet.ui.activities.StoryActivity)
.... 
.... 
(agent) Registering job 846790. Type: watch-class for: com.goldtouch.ynet.ui.activities.StoryActivity
com.goldtouch.ynet on (samsung: 11) [usb] # jobs list
  Job ID    Hooks  Type
--------  -------  ---------------------------------------------------------------
  846790       41  watch-class for: com.goldtouch.ynet.ui.activities.StoryActivity
com.goldtouch.ynet on (samsung: 11) [usb] #  
```
As shown in the tutorial the hooking job should be working in the foreground dumping info as I "play" with the app. 
I'm using latest objection and frida both client (x64) and server (Magisk v22) at v14.2.13-1

Any suggestions will be gladly welcomed. 

Thank You

**Comment by leonjza** [comment]
Hey, theres a few things we should ask ourselves / you can try.

- Does this also fail in other apps?
- Does hooking a single class method work?
- Does writing a custom hook and running it with vanilla Frida work?
- Have you tried the `android deoptimize` command first, and then running the hooking?

**Comment by rypz79** [comment]
@leonjza 
It works. Apparently I didn't "play" with the right screens.
Now a new problem emerges. I hook one value to TRUE then hook an entire class and bang the server crashes while the app is still working on my mobile. why ??
Can you check the dump please ?
[objection--DUMP.txt](https://github.com/sensepost/objection/files/6117696/objection--DUMP.txt)
TNX

**Comment by leonjza** [comment]
It's really hard to tell without spending time reversing the app to understand what is happening. The best I can offer is that you do that, and try and isolate a way to reproduce the crash. This could very well be a frida specific bug, so an isolated test case to report will go a long way into fixing it.

Good luck!
