### ISSUE TITLE
How to use a declare function from an imported javascript file?

### ISSUE THREAD

**Issue by abcdefgnihao** [sensepost/objection#447]
for example, if i type "import /root/test.js" on commandline, my console will automatically execute my startup function. But what if I wanna using other function later?

**Comment by leonjza** [comment]
Hey! Unfortunately this is not something we support yet without some code changes. Your best bet will be to use vanilla Frida for this which arguably does a really good job at it too :)

**Comment by abcdefgnihao** [comment]
OK
