### ISSUE TITLE
[Feature request] Android wildcard hooking

### ISSUE THREAD

**Issue by vdun** [sensepost/objection#45]
e.g. : `android hooking watch class_method com.myApp.MyClass *`

**Comment by leonjza** [comment]
Absolutely doable! Thanks.

**Comment by vdun** [comment]
This might help: https://github.com/0xdea/frida-scripts/blob/master/raptor_frida_android_trace.js

**Comment by leonjza** [comment]
This will be possible in the next release using `android hooking watch class qualified.class.name (optional: ---flags)`
