### ISSUE TITLE
[bug] functions not recognized

### ISSUE THREAD

**Issue by tstifxoxo** [sensepost/objection#450]
I first listed all functions of class by using 
`android hooking list class_methods me.appname.appname.services.api.ApiResponse$Companion`
and i've got following function listed
`public final <T> me.appname.appname.services.api.ApiResponse<T> me.appname.appname.services.api.ApiResponse$Companion.create(retrofit2.Response<T>)` and few more (this function was most interesting for me)

then i tried to hook onto this function manually by writting
`android hooking watch class_method me.appname.appname.services.api.ApiResponse$Companion.create(retrofit2.Response)`
but it gave me error saying that function can't be found. 

`Error: java.lang.ClassNotFoundException: Didn't find class "me.appname.appname.services.api.ApiResponse$Companion.create(retrofit2" on path: DexPathList[[zip file "/data/app/me.appname.appname-1/base.apk"],nativeLibraryDirectories=[/data/app/me.appname.appname-1/lib/arm, /vendor/lib, /system/lib]]`

but then when i try to hook all function in class `Companion` i get following output and it manages to hook properly!

`(agent) Hooking me.appname.appname.services.api.ApiResponse$Companion.create(retrofit2.Response)`

What could be the reason why I can't find this function directly but rather relay on non argument hooking from objection? Can someone please tell me what is the reason?

**Comment by leonjza** [comment]
This is most probably a parsing issue with the name you provided. Try and add the `<T>` to the argument.

**Comment by tstifxoxo** [comment]
It still doesn't work. @leonjza 
I tried adding `android hooking watch class_method me.profitcard.profitcard.services.api.ApiResponse$Companion.create(retrofit2.Response<T>)` but nothing happens. The reason why i am trying to hard to access this is because i tried hooking this function on Frida but it never gets executed while when i hook on it with objection (but no specifying arguments because i obviously can't hook onto the function i want directly) it gets called.

**Comment by leonjza** [comment]
Right. It's been a while since I've looked at this part of the agent tbh, and I see we strip generics from enumerated methods in the class watcher.

You'd have to debug this one I'm afraid. The full class watcher is [here](https://github.com/sensepost/objection/blob/1.10.2/agent/src/android/hooking.ts#L56-L118) (it enumerates all of the methods it can find, cleans them up and hooks), and the method watcher is [here](https://github.com/sensepost/objection/blob/1.10.2/agent/src/android/hooking.ts#L120-L208) which parses the string you pass in the CLI. In theory, the (cleaned up) method name enumerated using the class watcher should match the one you pass on the CLI.

For hints on setting up a development environment, check out the wiki [here](https://github.com/sensepost/objection/wiki/Development-Environment-Installation) and [here](https://github.com/sensepost/objection/wiki/Agent-Development-Environment).

**Comment by tstifxoxo** [comment]
It's impossible for me to setup development environment because i won't be at my Linux PC for quiet some time and i'm on Windows right now sadly. Is there any chance you could abstractly help me on finding out what the problem is here? What could be making hook not recognize the function or its arguments when i pass it? I just don't understand. The main problem occured when i wanted to hook this function with Frida and the method was never executing when i hooked it but then i saw using objection it gets called. Not being able to hook with Objection using method arguments but rather hooking all methods in class gave me some very weird position. Thanks a bunch for the help. I really appreciate it

**Comment by leonjza** [comment]
The debug environment should work fine on Windows. Debugging the agent is the only way to get to the bottom of what is happening here.

**Comment by leonjza** [comment]
Can you try hooking with these commands?

```
android hooking watch class_method me.appname.appname.services.api.ApiResponse$Companion.create
```

and

```
android hooking watch class_method me.appname.appname.services.api.ApiResponse$Companion.create "retrofit2.Response|
"
```

**Comment by tstifxoxo** [comment]
Ok this worked! Thanks a bunch lol!
But what i can't understand now is why Frida can't hook onto this function? I mean it hooks but it never gets triggered like in Objection? I asked on their Git but no one is responding to me... How could it be that objection manages to intercept that function call which relays on Frida but Frida doesn't see it?

```
const activity4 = Java.use('me.appname.appname.services.api.ApiResponse$Companion')
				activity4.create.overload('retrofit2.Response').implement = function(a){
					console.log("API called!!!: " + a)
					console.log("---------------------------");
					
					return this.create(a)
}
```

This is the same function i hook with Objection and it works now but it doesn't get executed in Frida for some reason... No errors were shown from Frida's side as well

**Comment by leonjza** [comment]
Take a close look at the hooking code I linked. You are setting `implement` when it should be `implementation`.
