### ISSUE TITLE
Unable to connect to the frida server with -N -h -p

### ISSUE THREAD

**Issue by xuanyangyang** [sensepost/objection#458]
Unable to connect to the frida server with -N -h -p，but use frida -H can connect
![image](https://user-images.githubusercontent.com/19355674/116805203-616d7580-ab57-11eb-9399-8db21f940a40.png)

**Environment (please complete the following information):**
 - Device: android 9
 - OS: macOS Big Sur 11.3
 - Frida Version 14.2.14
- Objection Version 1.11.0

**Comment by leonjza** [comment]
duplicate of #456
