### ISSUE TITLE
frida.ProcessNotFoundError: unable to find process with name 'Gadget'

### ISSUE THREAD

**Issue by TomHubGit** [sensepost/objection#46]
Hi there,

I just installed frida and objection to try some iOS debugging. Unfortunately I only receive errors about closed connection and missing gadget. 
I tried to google it and read all the docs but havent found anything. So hopefully I dont ask a stupid RTFM question.

I have 
- a jailbroken iPad with iOS 9.3.3
- connected through USB cable
- frida is installed through Cydia and the frida-server is running
- objection is installed through pip

frida is capable to list the device
```
frida-ls-devices 
Id                                        Type    Name        
----------------------------------------  ------  ------------
local                                     local   Local System
581759c322bf                    tether  iOS Device  
tcp                                       remote  Local TCP  

```
Process listening seems to work also:
```
frida-ps -Uai
PID  Name           Identifier                     
---  -------------  -------------------------------
994  Cydia          com.saurik.Cydia               
993  Kalender       com.apple.mobilecal            
290  Mail           com.apple.mobilemail           
941  Nachrichten    com.apple.MobileSMS            
  -  App Store      com.apple.AppStore             
...
```

When I try objection explore, for a dedicated process/gadget, I receive the following error:
```
objection -g "com.apple.Preferences" explore
Error: unable to find process with name 'com.apple.Preferences'

```
Even though the process exists. 

When I run objection device_type I receive another issue:
```
objection device_type
Traceback (most recent call last):
  File "/root/virtual-python3/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/virtual-python3/lib/python3.6/site-packages/objection/console/cli.py", line 164, in device_type
    device_name, system_name, model, system_version = get_device_info()
  File "/root/virtual-python3/lib/python3.6/site-packages/objection/commands/device.py", line 20, in get_device_info
    runner.run(hook=hook)
  File "/root/virtual-python3/lib/python3.6/site-packages/objection/utils/frida_transport.py", line 346, in run
    session = self.get_session()
  File "/root/virtual-python3/lib/python3.6/site-packages/objection/utils/frida_transport.py", line 281, in get_session
    return frida.get_usb_device(5).attach(state_connection.gadget_name)
  File "/root/virtual-python3/lib/python3.6/site-packages/frida/core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "/root/virtual-python3/lib/python3.6/site-packages/frida/core.py", line 115, in _pid_of
    return self.get_process(target).pid
  File "/root/virtual-python3/lib/python3.6/site-packages/frida/core.py", line 73, in get_process
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
frida.ProcessNotFoundError: unable to find process with name 'Gadget'
```

**Comment by leonjza** [comment]
Heya,

Could you try and specify the value for `-g` from the `Name` output of `frida-ps -U` ?   
Eg: `objection -g Cydia explore`

**Comment by leonjza** [comment]
Additionally, I think if you specify the PID with `-g` that should also work.

**Comment by TomHubGit** [comment]
Pretty awesome quick reply ;) Thanks for that.

Tried it again with the calendar app:
```
frida-ps -Uai
PID  Name           Identifier                     
---  -------------  -------------------------------
993  Kalender       com.apple.mobilecal            

```

I then tried to specific -g option with the name and identifier from frida-ps, unfortunately same result:
```
objection -g "com.apple.mobilecal" explore
Error: unable to find process with name 'com.apple.mobilecal'
(virtual-python3) root@kali:/var/www/html/windows# objection -g "Kalender" explore
Error: unable to find process with name 'Kalender'
```

**Comment by TomHubGit** [comment]
Not sure if this is helpful, the Linux version I run frida and objection on:
```
uname -a
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux

```

**Comment by leonjza** [comment]
Interesting. Is the calendar app foregrounded when you try and connect objection?

**Comment by leonjza** [comment]
Also, can you try and connect with just `frida` ? Something like `frida -U Kalender`?

**Comment by TomHubGit** [comment]
The calendar app is open. 
Interestingly enough, friday says the connection is closed:
```
frida -U Kalender
     ____
    / _  |   Frida 10.6.34 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to attach: the connection is closed            
```

**Comment by TomHubGit** [comment]
This is what happens when I try to use frida to discover the calendar app:
```
frida-discover <PID of calendar app>
Injecting script...                                                     
Process terminated
Stopping...

```

**Comment by leonjza** [comment]
I don't have a jailbroken device with me now (and this might sound like a silly question) but is the `frida-server` version on the iPad at least 10.6.x ?

**Comment by TomHubGit** [comment]
I installed the latest version from the frida repository through Cydia. Just checked it and it says 10.6.35

**Comment by leonjza** [comment]
Ok. I will have to test this as soon as I can get my hands on a jailbroken device again. Sorry about that. I'll also fix that `device_type` command not honouring `-g`.

**Comment by TomHubGit** [comment]
Dont worry, thanks for the help so far. Pretty cool stuff you do!

Just some pretty strange thing, I tried device_type again and got some repsonse:
```
frida-ps -Uai
 PID  Name           Identifier                     
----  -------------  -------------------------------      
 290  Mail           com.apple.mobilemail           

objection -g 209 device_type
Connection: USB
Name: com.apple.accountsd
System: iPhone OS
Model: iPad
Version: 9.3.3

```

**Comment by TomHubGit** [comment]
Just tried explore again and got some response, however with an error (not sure if this is because i dont know what I do :) with objection or if this is related to the error)

```
objection -g 209 explore

     _     _         _   _
 ___| |_  |_|___ ___| |_|_|___ ___
| . | . | | | -_|  _|  _| | . |   |
|___|___|_| |___|___|_| |_|___|_|_|
        |___|(object)inject(ion) v1.2.3

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
com.apple.accountsd on (iPad: 9.3.3) [usb] # ls


An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: script is destroyed
com.apple.accountsd on (iPad: 9.3.3) [usb] # 

```

**Comment by TomHubGit** [comment]
Something I discovered was a timeout error during mem dump, maybe it is useful:

```
memory dump all /root/_mem_dump

An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: timeout was reached
ch.appV3 on (iPad: 9.3.3) [usb] # 

```

**Comment by leonjza** [comment]
At this point, given the errors you have reported here I am going to go with something weird with the environment for now. Have you considered [patching your target application](https://github.com/sensepost/objection/wiki/Patching-iOS-Applications) and giving that a go in the meantime?

**Comment by TomHubGit** [comment]
Havent tried it yet, I will see if I can follow the tutorial. I have to find the app .ipa file first and then get all the dependencies.

**Comment by TomHubGit** [comment]
Maybe you can give me a hint as I try to setup the XCode project. I always receive this error:
```
Failed to create provisioning profile.
There are no devices registered in your account on the developer website. Plug in and select a device to have Xcode register it.
```
However I dont see where I can register my device. Or do I have to buy an Apple Dev subscription?

**Comment by leonjza** [comment]
You definitely do not need to buy any subscriptions. I am not 100% sure why you are getting that, but [this](https://github.com/sensepost/objection/wiki/Patching-iOS-Applications#preparations---xcode) guide has generally worked ok for me, given that XCode can see my device etc. Are you sure the iPad you are using is ok though? Some of these problems seem very strange :P

**Comment by TomHubGit** [comment]
mmmh, pretty strange. So I installed XCode and followed your guide, still receive the same error. Creating a new project results in this missing device error.

The device itself is working fine (from what I can tell :D ) Never experienced any issues with it.
<img width="411" alt="screen shot 2018-01-20 at 22 18 56" src="https://user-images.githubusercontent.com/20123996/35188114-6b4a2166-fe30-11e7-8649-96536882aae7.png">

**Comment by TomHubGit** [comment]
Some googling did help in the end. 
The project scheme was set to a Simulator iPhone 8. 
I had to go to the very top of the drop down menu and choose "add..."
Then I added my device.
Clicking on the button again, I became a new error message that the Bundle Identifier is not unique.
After changing the Bundle Identifier I was able to generate the provisioning profile.

Pretty weired, but it seems to work now. Hopefully this info can helps someone else.

Just noticed I have uploaded the wrong screenshot above...
<img width="402" alt="screen shot 2018-01-20 at 22 26 35" src="https://user-images.githubusercontent.com/20123996/35188291-efa8fc50-fe32-11e7-910a-5130e32ced3e.png">
<img width="391" alt="screen shot 2018-01-20 at 22 28 06" src="https://user-images.githubusercontent.com/20123996/35188292-f583af94-fe32-11e7-816d-ae674de6e47d.png">
<img width="515" alt="screen shot 2018-01-20 at 22 28 40" src="https://user-images.githubusercontent.com/20123996/35188294-f7c7065c-fe32-11e7-9752-55d7199fca33.png">

**Comment by leonjza** [comment]
Awesome thanks for the feedback! So just to clarify, are you able to run a patched application now?

**Comment by TomHubGit** [comment]
Just something to add, I am right that objection can also be started over the network?

Maybe I can try to access the iPad through SSH and link objection to the frida-server process, would that work?

**Comment by leonjza** [comment]
Yes you can connect to a remote gadget by specifying the the `-N` / `--network` flag and then giving the remote `--host` and `--port` to use where Frida is listening before the `explore` command. So something like `objection -N -h 192.168.0.1 -p 27042 explore`.

**Comment by TomHubGit** [comment]
Thanks for that. I will try it soon. Sorry for the late reply, kinda busy at the moment. 
Really appreciate it 👍

**Comment by TomHubGit** [comment]
I modified the plist for the LaunchDaemon to start frida-server listening on the ip address. It seems to work, ssh connectivity works as well, but objection gets a timeout.
on the iPad:
`ps aux
root            1030   0.0  0.3   683248   2776   ??  Ss   11:27PM   0:00.03 /usr/sbin/frida-server -l 10.0.1.132:27042
`

This is what I got on the Linux system
```
~ # objection -N -h 10.0.1.132 -p 27042 explore                                                             

Error: unable to connect to remote frida-server: Could not connect to 10.0.1.132: Connection timed out

```

**Comment by TomHubGit** [comment]
I just installed a new linux box and tried it there again.
ideviceinfo, frida-ps etc. seems to work.

Now I get a dyld error

```
frida-ls-devices                                                  
Id                                        Type    Name        
----------------------------------------  ------  ------------
local                                     local   Local System
56bcfc8581759c322bf     tether  iOS Device  
tcp                                       remote  Local TCP   
(objection) 
------------------------------------------------------------
~ # frida-ps -Uai                                                                                       
PID  Name          Identifier                     
---  ------------  -------------------------------
760  Calendar      com.apple.mobilecal            
314  Cydia         com.saurik.Cydia               
290  Mail          com.apple.mobilemail           
744  Messages      com.apple.MobileSMS            
635  Terminal      com.officialscheduler.mterminal
  -  App Store     com.apple.AppStore                    
  -  Camera        com.apple.camera           

objection -g "Calendar" explore                                                                     
Error: unexpected error while probing dyld of target process
```

**Comment by TomHubGit** [comment]
I was able to use frida to connect for example to the calendar app:

```
frida-trace -U -i "*open" Calendar                                                                  
Instrumenting functions...                                              
BZ2_bzopen: Auto-generated handler at "/root/__handlers__/libbz2.1.0.dylib/BZ2_bzopen.js"
BZ2_bzdopen: Auto-generated handler at "/root/__handlers__/libbz2.1.0.dylib/BZ2_bzdopen.js"
fscache_open: Auto-generated handler at "/root/__handlers__/libCoreFSCache.dylib/fscache_open.js"
mtrie_open: Auto-generated handler at "/root/__handlers__/DictionaryServices/mtrie_open.js"

```

**Comment by leonjza** [comment]
I'll be honest, I am pretty confused by the inconsistency of the issues you are facing here. I'll test out some of this in a jailbroken device as soon as possible and revert back.

**Comment by TomHubGit** [comment]
Dont worry, I am confused too ;) Anyway, I really appreciate your effort on this one. If there is anything else I can test or do, just let me know. I will play around with a lil bit more. 

PS: The network connect should be fine, right? In terms of syntax etc. I cant really see what is the problem. Service is running and listening on the iPad, the right interface and defined port. But still a timeout. Pretty strange

**Comment by leonjza** [comment]
> PS: The network connect should be fine, right? In terms of syntax etc. I cant really see what is the problem.

Yep the command syntax is 100%.

**Comment by TomHubGit** [comment]
Ok, no idea what happened or what might be different... but it seems to work now.

Thanks again for being so supportive and I am looking forward to play around with objection :D 

```
~ # objection -g Mail device_type                                                                                     
Connection: USB
Name: com.apple.mobilemail
System: iPhone OS
Model: iPad
Version: 9.3.3
(objection) 

 # objection -g Mail explore                                                                                           

     _     _         _   _
 ___| |_  |_|___ ___| |_|_|___ ___
| . | . | | | -_|  _|  _| | . |   |
|___|___|_| |___|___|_| |_|___|_|_|
        |___|(object)inject(ion) v1.2.3

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
com.apple.mobilemail on (iPad: 9.3.3) [usb] # ls
NSFileType      Perms  NSFileProtection    Read    Write    Owner     Group       Size      Creation                   Name
------------  -------  ------------------  ------  -------  --------  ----------  --------  -------------------------  ----------------------------------
Regular           436  n/a                 True    False    root (0)  admin (80)  1.2 KiB   2016-05-23 03:11:22 +0000  126AccountIcon@2x.png
Regular           436  n/a                 True    False    root (0)  admin (80)  3.6 KiB   2016-05-23 03:11:22 +0000  126AccountIcon~ipad.png
Regular           436  n/a                 True    False    root (0)  admin (80)  1.2 KiB   2016-05-23 03:11:22 +0000  163AccountIcon@2x.png
Regular           436  n/a                 True    False    root (0)  admin (80)  3.6 KiB   2016-05-23 03:11:22 +0000  163AccountIcon~ipad.png

```

**Comment by TomHubGit** [comment]
PS: If there is anything I should test in this case to help you, just let me know!

**Comment by leonjza** [comment]
Dug out an old iOS 8 jailbroken device and tested this out. I seem to be able to consistently connect as expected, apart from the odd hook not working (which is expected). I have tried to improve some of the help that gets shown when errors occur too which will hopefully help in the future.
