### ISSUE TITLE
Objection error message in non-rooted android device

### ISSUE THREAD

**Issue by ganesh2183** [sensepost/objection#476]
OS: Windows 10
Python version: 3.8.2
Frida version: 15.0.9

Patched android apk for Non-rooted android. Trying to connect to non-rooted android device using objection.  Unable to connect to android device, how to solve this issue.

![16278828406077073580405835093822](https://user-images.githubusercontent.com/41476297/127809709-c87b34bb-9035-467b-8799-1fc7da1e9caa.jpg)

**Comment by gav1no** [comment]
Hey, this is due to a recent change in Frida (15+). A workaround is to find the process ID (PID) when launching the app using `frida-ps -U`, then use that PID and use it with objection like this; `objection  --gadget PID explore` 

hope this helps :)

**Comment by ganesh2183** [comment]
Thanks for your reply.

Once patched apk installed into non-rooted android device. When i run frida-ps -U command, I m seeing only "waiting for USB device to appear..." It is not showing any PIDs, why??

How to solve this.

**Comment by gav1no** [comment]
Are you using a physical device or emulator?

**Comment by gav1no** [comment]
can you adb into the device? `adb shell`

**Comment by ganesh2183** [comment]
I m using real device and able to run adb shell command.

**Comment by ganesh2183** [comment]
Hi, any update on this issue.

**Comment by leonjza** [comment]
@ganesh2183 I'll suggest you try and get just the vanilla `frida` command working and connected to your app first.

**Comment by jj0e** [comment]
I'm facing the same issue... Is there anyway to use a lower version since this has to do with recent Frida changes??

**Comment by ganesh2183** [comment]
> @ganesh2183 I'll suggest you try and get just the vanilla `frida` command working and connected to your app first.

@leonjza Tried Frida command, it is working as expected with Android emulator. With **frida-ps -Uia** command it list all process running in emulator.

But when try with non rooted android device (real device) , we are getting the above error message as 'device not found'.

Please help me to solve this.

**Comment by ganesh2183** [comment]
@leonjza Could you help to resolve this issue.

**Comment by leonjza** [comment]
Sorry, I don't really know what is wrong. If `frida-ps` is  not working for you on a real device, then objection probably wont either.

The best I can do now is to tell you that [this is the function call that is of interest](https://github.com/sensepost/objection/blob/cef0513d26227aad197cb24e5ef25f07f3613aa6/objection/utils/agent.py#L123) in case you want to spend some time debugging.

**Comment by sky281998** [comment]
Upgrade frida to the latest version
Upgrade frida tools 
Patch the APK with the latest frida gadget
Once installed -> open the APK -> frida-ps -U (get the PID) -> Use the PID to open the APK (objection --gadget "PID" explore) 

Not sure why I'm not able to open it through the package name. but this surely helped me. 

Give a heads up if that works for you too

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen.
