### ISSUE TITLE
Bypassing Network Security Configuration in Android 7

### ISSUE THREAD

**Issue by rsmith31415** [sensepost/objection#48]
Is it possible to bypass the network security configuration in Android 7 with objection? Currently, there are a two approaches (as described [here](https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2017/november/bypassing-androids-network-security-configuration/)) to achieve this, but it would be quite convenient to be able to do the same within objection or in the process of patching the app via `objection patchapk `.

I ask this question mainly because in the same article linked above, there is a section called "Hooking on runtime" which shows how to perform this bypass in frida, so I thought it might be possible to do it in objection.

**Comment by leonjza** [comment]
Hey! This is on my todo list to experiment with but I totally its possible, just a matter of implementation!

**Comment by rsmith31415** [comment]
Great! I would be very interested in testing that feature.

**Comment by leonjza** [comment]
Just committed this in 484963461f9b5e24614daae749bbbd3030bf0c53, should be available as soon as I tag v1.2.7.

**Comment by leonjza** [comment]
Also added d53ff2c4dec31d3cf5ea6dd8c657e36777ad16da to try and bypass this at runtime.

**Comment by rsmith31415** [comment]
Excellent! I will report back after testing this improvement.
