### ISSUE TITLE
not throwing an exception.

### ISSUE THREAD

**Issue by sfdota** [sensepost/objection#481]
[tab] for command suggestions
com.fenqile.fenqile on (samsung: 7.1.2) [usb] # android sslpinning disable
(agent) Custom TrustManager ready, overriding SSLContext.init()
(agent) Found okhttp3.CertificatePinner, overriding CertificatePinner.check()
(agent) Found okhttp3.CertificatePinner, overriding CertificatePinner.check$okhttp()
(agent) Found com.android.org.conscrypt.TrustManagerImpl, overriding TrustManagerImpl.verifyChain()
(agent) Found com.android.org.conscrypt.TrustManagerImpl, overriding TrustManagerImpl.checkTrustedRecursive()
(agent) Registering job 631385. Type: android-sslpinning-disable
com.fenqile.fenqile on (samsung: 7.1.2) [usb] # (agent) [631385] Called SSLContext.init(), overriding TrustManager with empty one.
(agent) [631385] Called (Android 7+) TrustManagerImpl.checkTrustedRecursive(), not throwing an exception.
(agent) [631385] Called (Android 7+) TrustManagerImpl.checkTrustedRecursive(), not throwing an exception.
(agent) [631385] Called (Android 7+) TrustManagerImpl.checkTrustedRecursive(), not throwing an exception.
 can not scrap apk data

**Comment by leonjza** [comment]
This ticket has no information.
