### ISSUE TITLE
Unable to determine launchable activity

### ISSUE THREAD

**Issue by AndreMPCosta** [sensepost/objection#483]
**Describe the bug**
When trying to patch an apk I get this message:
Exception: Unable to determine launchable activity

**To Reproduce**
1. Run command 'objection patchapk --source 132.apk --architecture armeabi-v7a'

**Expected behavior**
It should patch the apk I guess.

**Evidence / Logs / Screenshots**
![image](https://user-images.githubusercontent.com/3736805/132945106-151e3b55-821b-4d87-b427-c43bf1e79be0.png)

**Environment (please complete the following information):**
 - OS: Mac OS 11.5.2
- Objection Version 1.11.0

**Application**
Check attachments
[132_orig.apk.zip](https://github.com/sensepost/objection/files/7147638/132_orig.apk.zip)

**Comment by leonjza** [comment]
The error means it doesnt know where the app starts. Specify a class with the `--target-class` flag.
