### ISSUE TITLE
Objection Scripting ?

### ISSUE THREAD

**Issue by DSTRULLU** [sensepost/objection#489]
Hi

Now I build SVM to detect some malware type and I use objection combine with Frida for Dynamic analysis. I make a program to run automatically the analysis but I have problem.

When I run my Objection's process to hook some class my prompt freeze and my program can't execute the remaining code. To solve this I want to make a script with objection instructor without using the command line. Is it possible ?

**Comment by IPMegladon** [comment]
Objection does have an API that you may be able to use for things like this.
Closing issue as stale, feel free to reopen.
