### ISSUE TITLE
[bug] Instagram 209.0

### ISSUE THREAD

**Issue by kkm** [sensepost/objection#496]
https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-209-0-0-21-119-release/

Does anyone have any idea why this doesn't work anymore?

I did try with command line:

`objection -g com.instagram.android  explore` then `android sslpinning disable` 
and
`frida -U -f com.instagram.android -l script.js --no-paus`

both no longer work.
I'm not sure if it should work.

**Comment by leonjza** [comment]
I'd be surprised if the generic hooks we have bypasses pinning in an app like Instagram out of the box. Your only option here is to reverse the application and discover how they have implemented it manually.
