### ISSUE TITLE
frida.ProcessNotFoundError: unable to find process with name 'Gadget'

### ISSUE THREAD

**Issue by iaskwho** [sensepost/objection#5]
when i use it, command:objection device_type
error occurred：
**frida.ProcessNotFoundError: unable to find process with name 'Gadget'**

**Comment by leonjza** [comment]
Hey,

Is your patched application running? What is the output of `frida-ps -U` after you have launched the patched application?

**Comment by leonjza** [comment]
Closing this for now. Feel free to reopen if this issue persists.

**Comment by tonythomasv** [comment]
Hi Guys,

I installed objection using pip3 and when I try to run "**objection explore**". I get the error "**unable to find process with name gadget**".

Below is part of the output of "**frida-ps -U**" and my output when I try to run "**objection explore"**
`
androidanalyst@gh0st> frida-ps -U | grep -i su
5631  daemonsu:0
5633  daemonsu:0:5628
2097  daemonsu:10106
 580  daemonsu:master
 511  daemonsu:mount:master
5412  eu.chainfire.supersu
5628  su
 135  surfaceflinger
1307  wpa_supplicant
androidanalyst@gh0st> objection explore
Error: unable to find process with name 'Gadget'
androidanalyst@gh0st> 
`
It would be great if you guys could take a look. Thanks in Advance.

**Comment by leonjza** [comment]
@tonythomasv given that the `frida-ps -U` output shows all of the processes running on your Android device, I am assuming you have a rooted device with Frida running. In this case, you need specify the gadget name with the `--gadget` flag to that of the bundle identifier of the application you are wanting to connect to.

For more information, have a look at [this](https://github.com/sensepost/objection/wiki/Running-On-A-Rooted-Device) wiki page.

**Comment by tonythomasv** [comment]
@leonjza :+1:  Thankyou. This worked beautifully. :)
