### ISSUE TITLE
launchable-activity-Check from aapt not 100% valid?

### ISSUE THREAD

**Issue by acuntex** [sensepost/objection#50]
There is a check for the launchable active in the code, that checks for "launchable-activity". Thats why I always get the error "Unable to determine the launchable activity using aapt"

The Code has a comment:
> ['launchable-activity: name=', 'com.app.activity', '  label=', 'bob']

But the actual line by aapt dump badging is:
> launchable activity name='com.app.activity'label='bob' icon=''

**Comment by leonjza** [comment]
Heya, which version of `aapt` have you got there? Might be that a newer version changed that, in which case we can easily just search for both.

**Comment by acuntex** [comment]
Not sure, might be also an old version because it was already installed on my system ;)

> Android Asset Packaging Tool, v0.2

The fix you talked about might work, I tested it and it found the activity. properly.

**Comment by leonjza** [comment]
Thanks for verifying, will update and test asap.

**Comment by leonjza** [comment]
Tested a few apps and looks like its still being output as per the code comments. `aapt` version:

```
$ aapt v        
Android Asset Packaging Tool, v0.2-24.0.0
```
