### ISSUE TITLE
I am trying to installed objection tool for android pen testing. For installation used command pip3 install objection, but in response getting this error. Please suggest

### ISSUE THREAD

**Issue by yashashri2494** [sensepost/objection#500]
<img width="1433" alt="Screenshot 2021-11-11 at 1 00 04 PM" src="https://user-images.githubusercontent.com/86764716/141256536-1347833f-dceb-4d26-80ed-148c84aeadc4.png">

**Comment by leonjza** [comment]
This is as a result of the frida dependency. I found two related issues that may help you in solving it. https://github.com/frida/frida/issues/1051 & https://github.com/frida/frida/issues/531.
