### ISSUE TITLE
Getting stuck on starting objection command

### ISSUE THREAD

**Issue by bikeebh** [sensepost/objection#505]
Hi

I just update my objection version in Mac OS 
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
and try to run objection in iOS device 14.0 

and it's getting stuck there like this 

Mac:insert_dylib me$ objection -S 1c75b114669f8b4f8da4053456efaa65678c53c72 explore
Using USB device `iPhone`

the same is working in other machine. 

@leonjza can u please suggest some troubleshooting steps

**Comment by bikeebh** [comment]
This does't help getting stuck and only this log is coming

objection -S c060d879e8fe2211e877d76ee8e46b8a96891ba1 --gadget com.test.app explore
**Using USB device `iPhone`**

I run one Xcode sample app also for resolve image mounting 

@leonjza this is happening after updating objection.

**Comment by leonjza** [comment]
Sorry, this is not really enough information for me to help debug and or be useful. You can try adding the `--debug` flag and see if there is more useful output, but otherwise I don't really know.

**Comment by fdciabdul** [comment]
try with python 3.9.1

**Comment by zhuzhu-Top** [comment]
I use -g pass the PID  ,it work

**Comment by owen800q** [comment]
Fro anyone encountering this issue
use objection -g pid explore

**Comment by timemout** [comment]
thank you for the '"-g", it's really helpful, but what i'm interested in is that the "-g" requires the application to be already up and running. 
what if i wanted to spawn the application alongside some custom command using the "-s " parameters, what do i use to spawn the application ?

**Comment by leonjza** [comment]
Spawning was refactored in the latest HEAD and will land in the next release.

**Comment by jacky1234** [comment]
> sample app also for resolve image mounting

tried, useless

**Comment by jacky1234** [comment]
> I use -g pass the PID ,it work

tried, useless

**Comment by sangcx5** [comment]
I use this command: `objection -d -g 1256 explore`
then I got this output:
```
[debug] Agent path is: /opt/homebrew/lib/python3.11/site-packages/objection/agent.js
[debug] Injecting agent...
Using USB device `iPhone`
[debug] Attempting to attach to process: `1256`
[debug] Process attached!
Agent injected and responds ok!
```

and then got stuck, nothing happen next, what should I do now?
