### ISSUE TITLE
Support injection at Application.onCreate for Android

### ISSUE THREAD

**Issue by WanghongLin** [sensepost/objection#509]
On Android platform, I found some apps have signature verification mechanism which will cause the app crash or exit at its very early stage if the app resigned by `objection`.

Currently the frida-gadget injected point is `onCreate` of first `Activity` for Android, is it right?

I am wondering if the frida-gadget injected point can be moved to `Application.onCreate`, then I can take further steps from frida script to prevent app crash or exit.

The ideal solution is the injected point `Application.onCreate` or `Activity.onCreate` can be specified from an option when invoke `patchapk` command.

**Comment by leonjza** [comment]
> Currently the frida-gadget injected point is `onCreate` of first `Activity` for Android, is it right?

It patches the launchable activity. 

You can tell he patcher to use a different class with the [`--tarrget-class`](https://github.com/sensepost/objection/blob/1.11.0/objection/console/cli.py#L339) flag.
