### ISSUE TITLE
[bug] Bug Description Here

### ISSUE THREAD

**Issue by qingyi11** [sensepost/objection#513]
**Environment (please complete the following information):**
 - Device: [e.g. Redmi K20Pro]
 - OS: [e.g. Android 10]
 - Frida Version [e.g. 12.8.0]
- Objection Version [e.g. 1.8.4]

Stuck after execution

![pic](https://user-images.githubusercontent.com/46914233/146738862-fed8822d-c83e-42e7-b936-f1a0740838c8.png)

**Comment by leonjza** [comment]
Try adding the `--debug` flag to the `objection` command to get more information.
