### ISSUE TITLE
[bug] objection ：frida.core.RPCException: unable to find method 'ping'

### ISSUE THREAD

**Issue by lixi5338619** [sensepost/objection#514]
Raise：
frida.core.RPCException: unable to find method 'ping'
Asking jobs to stop...
Unloading objection agent...

Version：
Frida 12.11.18
objection  1.8.4

I think it might be a version problem...
I am not willing to change the version...

**Comment by CDuPlooy** [comment]
If your not willing to change the version, then you'll need to find someone who's willing to help you out with your specific version. 

Imo you have two options, and the one is far easier than the other :)
