### ISSUE TITLE
Feature Request: watch-class-methods with overload selection

### ISSUE THREAD

**Issue by acuntex** [sensepost/objection#52]
Would it be possible to enhance the watch-class-methods-functionality to watch only specific overloads?

Currently it watches all overloads which is somehow useless if you have an obfuscated class that has a lot of method overloads called "a" :-)

**Comment by leonjza** [comment]
Adding to the wishlist!

**Comment by leonjza** [comment]
This has since been implemented. See the help [here](https://github.com/sensepost/objection/blob/master/objection/console/helpfiles/android.hooking.watch.class_method.txt).
