### ISSUE TITLE
import Fridascript error

### ISSUE THREAD

**Issue by hasanali586q** [sensepost/objection#530]
not: my device root and not patch  app
step
1) run frida ./frida-server-latest
2) run "objection --gadget "myapp" explore"  good working
3) but run  'import sslbypass.js'  problem 
```
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
unable to handle 64-bit processes due to build configuration
```
script code: https://codeshare.frida.re/@segura2010/android-certificate-pinning-bypass/

and I want to use frida with objection somewhere but there is a problem
1) frida -f "myapp" -U
2) objection --gadget "myapp" explore 
problem not working

**Comment by decidedlygray** [comment]
I could be wrong, but:

Without a rooted phone `frida -f "myapp" -U` won't work. Without a patched app `objection --gadget "myapp" explore` won't work. You need one or the other

**Comment by leonjza** [comment]
@hasanali586q could open a new issue, providing the full stack trace leading up to the error please? Filling in the whole bug report template will help.

@decidedlygray regardless of how you spawn/attach, importing scripts should work in either case.
