### ISSUE TITLE
App blocks all trafic after launching it by frida

### ISSUE THREAD

**Issue by 7987890hkjh** [sensepost/objection#531]
I am trying to launch facebook app with frida command: "frida -U -f com.facebook.katana".

But it sends about 40 requests at max (thats not enough) and loading screen stays endless

![photo_2022-03-05_21-58-18](https://user-images.githubusercontent.com/98693489/156896580-d118eaa2-daf9-452f-8f0a-6858aaf498b9.jpg)

**Comment by hasanali586q** [comment]
%resume write and enter pls

**Comment by CDuPlooy** [comment]
This isn't relevant to objection.
