### ISSUE TITLE
[bug] Why Internet Permission is required in script mode

### ISSUE THREAD

**Issue by harshitshah4** [sensepost/objection#536]
- Please, fill in all of the sections in this template.
- Please read each section carefully. Each has a description of what information will help.
- Windows support is limited. There is a good chance that a pull request would help!
- The more information you give, the better.
- Remove this section when you are done.

**Describe the bug**
So when patching the apk with script it should ideally not check for injecting internet permission right ? gadget's config.json file also has interaction type as "script". 
My understanding is we need to inject internet permission in "listen" mode, where we need to interact with frida's gadget via cli using usb debugging.

**To Reproduce**
1. objection patchapk --script-source /path/to/script.json --gadget-config /path/to/config.json --architecture <desired_architecture>

**Similar issues**
Please link the issues in this repository that is similar to yours.

For example: #358, #229 etc.

**Expected behavior**
Since Frida Gadget requires to have internet permission in order to open socket, this helps debugging helps via cli, when running in "listen" mode, but since in "script" mode, we don't require internet permission, objection shouldn't try to insert or look for Internet Permission in AndroidManifest.xml.

**Evidence / Logs / Screenshots**
After running the above command following logs are generated: 
<img width="1177" alt="Screenshot 2022-04-07 at 5 28 32 PM" src="https://user-images.githubusercontent.com/14928914/162193587-3a3b472e-14e2-4f61-b3cb-85e4de36eda8.png">
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
objection --debug explore
```

**Environment (please complete the following information):**
 - Device: Used without connecting any device
 - OS: Android
 - Frida Version 15.1.17
- Objection Version 1.11.0

**Application**
If possible, please attach the target application where you can reproduce this bug to the issue.

**Additional context**

**Comment by leonjza** [comment]
Yeah, technically we don't need the permission for script mode, but it's not something I think we'll change now. The patcher will change soon when we rely on the Frida provided injection capability soon anyways.
