### ISSUE TITLE
[bug] Bug Description Here

### ISSUE THREAD

**Issue by rahul-1485** [sensepost/objection#543]
**Describe the bug**

I am able to patch the IPA and able to install it but when i try to run it i got below error.

**Could not start com.apple.debugserver!
Please make sure to mount the developer disk image first:
  1) Get the iOS version from `ideviceinfo -k ProductVersion`.
  2) Find the matching iPhoneOS DeveloperDiskImage.dmg files.
  3) Run `ideviceimagemounter` with the above path.**

I have tried to mount the disk image but issue is same.

I am using non rooted device.

**To Reproduce**
	1.	objection patchipa --source /Users/Rahul/Desktop/Objection/Thumba2807.ipa --codesign-signature 70F8B27AAE80BC22A16B06C3AC5410709920A62F
	2.	ideviceinstaller -i Thumba2807-frida-codesigned.ipa
	3.	idevicedebug -d run com.pcloudy.Screencaster

**Expected behavior**

In earlier objection version(1.9.6) it was working but in 1.11.0 it is showing this error.

**Evidence / Logs / Screenshots**

Please find the attached screenshot.
<img width="1258" alt="2" src="https://user-images.githubusercontent.com/78218864/167006084-fc03a47d-ba32-4a43-9902-fec415e50f47.png">

**Environment (please complete the following information):**
 - Device: [e.g. iPhone7]
 - OS: [IOS 15]
 - Frida Version [15.1.10]
- Objection Version [1.11.0]

**Application**
If possible, please attach the target application where you can reproduce this bug to the issue.

[Thumba2807.ipa.zip](https://github.com/sensepost/objection/files/8634601/Thumba2807.ipa.zip)

**Comment by rahul-1485** [comment]
Any can anyone help on this.

**Comment by leonjza** [comment]
Deploy a blank application from XCode and it set everything up for you.
