### ISSUE TITLE
Patched application closes without pausing at start screen

### ISSUE THREAD

**Issue by ljiazh3ng** [sensepost/objection#548]
**Describe the bug**
Ran objection on the base.apk and signed the config files using Objection signapk. After successfully downloading the apk to my Android Emulator(x86). I run the app, however the application just shut down, not giving me time to connect frida.

Any advise is appreciated.

**To Reproduce**
1. Run command 'objection patchapk -s test_app.apk'
2. Run command 'objection signapk config.arm64_v8a.apk'

**Expected behavior**
Application should pause on the start screen for me to connect frida and monitor traffic.

**Environment (please complete the following information):**
 - Device: [Android emulator]
 - Frida Version [15.1.22]
- Objection Version [1.11.0]

**Application**
Heckfire Ata mobile game

**Comment by leonjza** [comment]
Sorry, without more information it's not possible to help you. Filling in the logs section in the bug report template would be a good start.
