### ISSUE TITLE
aapt dont working while build-tools installed

### ISSUE THREAD

**Issue by d41sys** [sensepost/objection#561]
I have installed aapt and made an alias so it working normally.
But when I execute this command objection still ignores aapt.
I have set up android home path.

Is any specific for mac?
```
$ objection patchapk --source zalo.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: x86_64
Using latest Github gadget version: 15.2.2
Patcher will be using Gadget version: 15.2.2
Unable to find aapt. Install it with: apt install aapt (Kali Linux) before continuing.
Cleaning up temp files...
```

**Comment by IPMegladon** [comment]
Marking as stale and duplicate of #244, make sure it is included in your `$PATH` as that is what objection uses.
