### ISSUE TITLE
patchipa is getting stuck after running idevicedebug

### ISSUE THREAD

**Issue by bikeebh** [sensepost/objection#562]
objection explore command getting stuck and showing 

Mac-mini-5:biometric admin$ objection explore
Using USB device `iPhone`

1 Mac-mini-5:Desktop radmin$ idevicedebug -d run com.app.thumba
working_directory: /private/var/mobile/Containers/Data/Application/8AA1273C-34F4-4269-B3F3-5A03C0DDDD61

Setting logging bitmask...
Setting maximum packet size...
Setting working directory...
Setting argv...
app_argv[0] = /private/var/containers/Bundle/Application/C0CF39CD-03A1-4C19-A967-F645158D88AE/Thumba!.app/Thumba!
Checking if launch succeeded...
Setting thread...
Continue running process...
Entering run loop...

2 Mac-mini-5:biometric admin$ objection explore
Using USB device `iPhone`

**Environment (please complete the following information):**
 - Device: iPhone11 Pro
 - OS: iOS15.0
 - Objection Version 1.11.0
 - Mac OS version : 12.4
 -  idevicedebug version 1.3.1

**Comment by bikeebh** [comment]
@leonjza any idea on this issue

**Comment by bikeebh** [comment]
@leonjza  Is this tool will work on iOS version 15 and above using Mac OS version 12.4?

**Comment by leonjza** [comment]
It will work virtually anywhere Frida works.

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen.
