### ISSUE TITLE
[bug] objection spawn error

### ISSUE THREAD

**Issue by Lunction** [sensepost/objection#564]
Unable to connect to the frida server: unable to launch iOS app: The operation couldn’t be completed. Application "xx" is unknown to FrontBoard.
frida:15.2.2
MacOS:Big Sur 11.4

**Comment by CDuPlooy** [comment]
Have you tried spawning the application with just frida? Sounds like your identifier might be wrong.

**Comment by Lunction** [comment]
Just use the package name
