### ISSUE TITLE
NSUserDefaults Output Truncated

### ISSUE THREAD

**Issue by aress31** [sensepost/objection#575]
Hi Sensepost,

I am getting a truncated variable when dumping the `NSUserDefaults` store using:

```bash
x.y.z on (iPhone: XX.X) [net] # ios nsuserdefaults get

{
    --- REDACTED ---
    "x.key.y" = {length = 154, bytes = 0x7b226669 REDACTED... REDACTED 3939397d };
}
```

If an option could be added to allow the full output, that would save the hassle of manually looking for the `plist` file and parsing it! :)

Thanks,
Alex

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen.
