### ISSUE TITLE
[bug]--dump-args --dump-return doesnt display correctly

### ISSUE THREAD

**Issue by lyonnhk** [sensepost/objection#577]
**Describe the bug**
Same issue as https://github.com/sensepost/objection/issues/415

Expected args and return value however it only shows the calls.
![image](https://user-images.githubusercontent.com/57974924/196385176-c639fba7-01b4-48b0-b3ef-fb4a5bcee9fd.png)

**To Reproduce**
1. Run objection.
2. Hook to any non-void method: android hooking watch class_method [method URI] --dump-args --dump-return.
3. Watch as objects are passed around.

**Similar issues**
https://github.com/sensepost/objection/issues/415

**Expected behavior**

**Evidence / Logs / Screenshots**
![image](https://user-images.githubusercontent.com/57974924/196384523-4ce8ac7e-77fc-4f52-8cf4-a2d90d4b29d5.png)

**Environment (please complete the following information):**
 - Device: Samsung S10
 - OS: android 10
 - Frida Version 15.2.2
- Objection Version 1.11.0

**Comment by IPMegladon** [comment]
Closing issue as stale, feel free to reopen.
