### ISSUE TITLE
[bug] Patched APK is not installable

### ISSUE THREAD

**Issue by dannyyy** [sensepost/objection#578]
**Describe the bug**
I tried to patch the apk of the Roborock app. I tried different versions of the app. All of them are not installable on Android 13 (Emulator Pixel 5 device). After trying to install, this error appears `app not installed as package appears to be invalid`

In the most recent version, I get the following output while patching. Older version didn't have this:
```
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

W: /var/folders/7j/wknp27k94mvc2t7btv0nc0_00000gn/T/tmpkn0veux3.apktemp/AndroidManifest.xml:18: Tag <action> attribute name has invalid character '*'.
W: /var/folders/7j/wknp27k94mvc2t7btv0nc0_00000gn/T/tmpkn0veux3.apktemp/AndroidManifest.xml:18: Tag <action> attribute name has invalid character ''.
W: /var/folders/7j/wknp27k94mvc2t7btv0nc0_00000gn/T/tmpkn0veux3.apktemp/AndroidManifest.xml:18: Tag <action> attribute name has invalid character ''.
```

**To Reproduce**
1. Download the Roborock 4.0.13 apk (arm64-v8a)
2. Run `objection patchapk -s Roborock_4.0.13.apk`
3. Upload new apk into emulator
4. Try to install the app

**Expected behavior**
At least the installation should work. Furthermore I expect to have a disabled SSL certificate pinning.

**Evidence / Logs / Screenshots**
If any helpful I can post some screenshots

**Environment (please complete the following information):**
 - Device: MacBook Pro M1 Max 12.6
 - Target Device: Android Emulator (Pixel 5) with Android 13
 - Objection Version: 1.11.0

**Application**
APK is too large. But can be downloaded here: https://apkcombo.com/roborock/com.roborock.smart/download/apk

**Comment by ax** [comment]
Give a try to https://github.com/ax/apk.sh

**Comment by IPMegladon** [comment]
It is likely worth checking whether the same issue occurs when the app is decoded and subsequently built with apktool manually.
You could also try with the `--skip-resources` and `--ignore-nativelibs` flags added.
Though that said, closing issue as stale for now. Feel free to reopen.
