### ISSUE TITLE
Install success but objection not in command(win10, py3)

### ISSUE THREAD

**Issue by HuynhDat007** [sensepost/objection#580]
When I run "pip3 install objection" and has messege success, but I test on command "objection" then
"'objection' is not recognized as an internal or external command,
operable program or batch file."

Please help me!

![image](https://user-images.githubusercontent.com/32337127/198172703-24ce855b-6761-4a7a-8c48-0cc18d624b7f.png)

**Comment by alongj** [comment]
use pyenv-win to install python and pip. After objection installed, create file named objection.bat in .../pyenv-win/shims/objection.bat. Return to termimal, everything is ok! 
The obejction.bat is blow:
`
@echo off
chcp 1250 > NUL
call pyenv exec %~n0 %*
`

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen. However this was likely an environment setup issue rather than being related to objection.
