### ISSUE TITLE
Unable to find aapt. Install it with: apt install aapt (Kali Linux) before continuing - MAC

### ISSUE THREAD

**Issue by matt-b-mitchell97** [sensepost/objection#587]
Command `objection patchapk -s base.apk` is encountering error when trying to find aapt.

I am getting an error saying "Unable to find aapt. Install it with: apt install aapt (Kali Linux) before continuing." but I definitely have aapt and aapt2 present. I have tried adding it to $PATH seemingly unsuccessfully. 

All pip3 and brew packages and libraries are upgraded and Gadget is using version 16.0.2.

Error:

![Screenshot 2022-11-17 at 14 48 12](https://user-images.githubusercontent.com/58299329/202450617-27ef0653-82cc-4f78-b750-cda32bb82656.png)

Build-tools directory: 

![Screenshot 2022-11-17 at 14 45 19](https://user-images.githubusercontent.com/58299329/202450035-40cb5d80-eac4-4c07-881f-5d183c206540.png)

**Comment by trapp3rhat** [comment]
Same issue here. I added the path of the aapt tool in the PATH variables on my .zprofile but still not working and showing the same error.

**Comment by Sotime1150** [comment]
> 
it work my case
use vim .zshrc for edit then pass E (for edit)
paste.    **export PATH="$PATH:$HOME/Library/android/sdk/build-tools/33.0.1"** to .zshrc

**Comment by IPMegladon** [comment]
Marking issue as stale, not related to objection itself.
