### ISSUE TITLE
[bug] unable to applesign

### ISSUE THREAD

**Issue by kukuwhy6** [sensepost/objection#588]
Installation of "applesign" succeeded.
I'm not good at English.

Why is that?

![image](https://user-images.githubusercontent.com/116343476/203271551-429dfd09-2b5b-4f08-a663-04b6a7f9af11.png)

**Comment by vadim-a-yegorov** [comment]
Run on macOS with Xcode installed.

**Comment by IPMegladon** [comment]
I suspect `applesign` was not part of your path. Closing issue as stale, do not think this is an objection issue but rather to do with the environment setup.
