### ISSUE TITLE
Issue in using Objection with corellium iOS device

### ISSUE THREAD

**Issue by ubaidahmedIN** [sensepost/objection#597]
I am using corellium's virtual device for testing an application. I am using USBFlux and is able to connect to the device using the command frida-ps -Ua.
However, when I use the command: **_objection -g 1292 explore_**. I get the following output

```
Using USB device `iPhone`
Unable to connect to the frida server: unable to communicate with remote frida-server; please ensure that major 
versions match and that the remote Frida has the feature you are trying to use
```
I even tried using this command: **_objection --network --host 10.11.1.2 -g 1292 explore_**. I still get the above error.

Frida version on my mac and the corellium device is 16.0.1

I am struggling with the above issue for quite some time. Please help me out.

**Comment by CDuPlooy** [comment]
I think you might need to either upgrade the version of frida that objection uses, or downgrade the device frida version. There is a branch that works with Frida v16 https://github.com/sensepost/objection/pull/579, although I haven't had a chance to test on corellium

**Comment by CDuPlooy** [comment]
Tested this on corellium, works as intended
