### ISSUE TITLE
1.2.5 dependency error

### ISSUE THREAD

**Issue by rustymagnet3000** [sensepost/objection#60]
Hi @leonjza 

After upgrading to 1.2.5 I am hitting an error when iOS patching.

`objection patchipa -s unencryptedapp.ipa -c MY_DEVELOPER_ID --skip-cleanup`

Checking the other closed Issues, I made sure my Node & pip3 version were both updated.

`$ node --version`
v9.7.1

`$ python -V`
Python 3.6.4

`$ pip3 --version`
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

```
Using latest Github gadget version: 10.6.58
Patcher will be using Gadget version: 10.6.58
No provision file specified, searching for one...
No provisioning files found. Please specify one or generate one by building an app.
Working with app: myapp.app
Bundle identifier is: com.me.mobile.hello
Codesigning 21 .dylib's with signature 1D200xxxxxxxxx
Code signing: libswiftMapKit.dylib
Code signing: libswiftCoreImage.dylib
Code signing: libswiftObjectiveC.dylib
Code signing: libswiftCore.dylib
Code signing: libswiftCoreGraphics.dylib
Code signing: libswiftUIKit.dylib
Code signing: libswiftMetal.dylib
Code signing: libswiftCoreData.dylib
Code signing: libswiftDispatch.dylib
Code signing: libswiftos.dylib
Code signing: libswiftCoreFoundation.dylib
Code signing: FridaGadget.dylib
Code signing: libswiftDarwin.dylib
Code signing: libswiftContacts.dylib
Code signing: libswiftQuartzCore.dylib
Code signing: libswiftCoreAudio.dylib
Code signing: libswiftAVFoundation.dylib
Code signing: libswiftFoundation.dylib
Code signing: libswiftCoreMedia.dylib
Code signing: libswiftCoreLocation.dylib
Code signing: libswiftsimd.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/objection/console/cli.py", line 205, in patchipa
    patch_ios_ipa(**locals())
  File "/usr/local/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 70, in patch_ios_ipa
    patcher.archive_and_codesign(original_name=source, codesign_signature=codesign_signature)
  File "/usr/local/lib/python3.6/site-packages/objection/utils/patchers/ios.py", line 405, in archive_and_codesign
    self.patched_ipa_path
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by rustymagnet3000** [comment]
the only difference from previously, it is asking me to specify a provisioning profile.

`No provisioning files found. Please specify one or generate one by building an app.`

**Comment by leonjza** [comment]
heya!

Thanks for reporting this. Looking at the output here, I think the correct thing that should have happened is the patcher should have stopped at `No provisioning files found. Please specify one or generate one by building an app.` instead of racing on. The error comes with `list2cmdline ` [here](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/ios.py#L405) as there is no patched IPA to begin with, resulting in it being `None` at this stage and command build failing.

So, for now, make sure you have a [valid provisioning profile](https://github.com/sensepost/objection/wiki/Patching-iOS-Applications#preparations---mobileprovision) ready for objection to use then this _should_ work. In the mean time I will update the patcher to fail faster when this condition occurs.

**Comment by rustymagnet3000** [comment]
Nice one @leonjza 

Have you got an undocumented flag where I can specify the embedded.mobileprovision file?

It is not picking the file up, from the current working directory (which includes the un-touched IPA).

**Comment by leonjza** [comment]
You can specify the mobile provision file to use with `--provision-file` in the `patchipa`. All of the objection command line commands have the `--help` flag which should reveal the flags it supports.

**Comment by rustymagnet3000** [comment]
ok I can see from your file that you search ~/Library/Developer/Xcode/DerivedData/

for the `embedded.mobileprovision`. Let me try that now.

**Comment by rustymagnet3000** [comment]
Sorry, yes.

$ `objection patchipa --help`

**Comment by rustymagnet3000** [comment]
`objection patchipa -s unencryptedapp.ipa -c MY_DEVELOPER_ID --provision-file embedded.mobileprovision`

WORKED ✅
