### ISSUE TITLE
[Bug] Unable to connect to the frida server

### ISSUE THREAD

**Issue by Drjacky** [sensepost/objection#600]
I first ran this: `objection patchapk --source /Users/usernameeee/Desktop/sample-pulled.apk` and it generated the patched apk successfully.

then: `objection -g com.example.app explore -q` ->

```bash
Unable to connect to the frida server: need Gadget to attach on jailed Android; its default location is: /Users/usernameeee/.cache/frida/gadget-android-arm64.so
```

but when I decompile the objectionized APK, the so files are in the lib folder already:
<img width="211" alt="Screenshot 2023-01-13 at 20 11 18" src="https://user-images.githubusercontent.com/2296754/212410653-16f3415f-626b-4926-a352-8e6adf4f2c6f.png">

**Comment by Drjacky** [comment]
Ran like this: `frida -U nameOfTheApp` and it worked.

**Comment by Drjacky** [comment]
But still want to know why I cannot use `objection explore`? I get this:
```bash
Unable to connect to the frida server: need Gadget to attach on jailed Android; its default location is: /Users/usernameeee/.cache/frida/gadget-android-arm64.so
```

**Comment by Drjacky** [comment]
I need to run the app once and then run `objection explore`.

**Comment by z0xyz** [comment]
> I need to run the app once and then run `objection explore`.

That did work, but not for all apps.
