### ISSUE TITLE
failed to create process.

### ISSUE THREAD

**Issue by thejackal2017** [sensepost/objection#619]
Hi , i installed objection without any errors during the installation process, but no matter which option i use i always get:
`failed to create process.`

Python version:
`Python 3.9.0`

pip version:
`pip 20.2.3`

Any ideas what might be the cause of this problem ?

**Comment by IPMegladon** [comment]
Please provide more information such as which objection commands you are trying to use? Do you get the same error even when running something like `objection --help`?

**Comment by IPMegladon** [comment]
Closing issue as stale for now as it was created quite a while back, feel free to reopen.
