### ISSUE TITLE
Option to avoid signing

### ISSUE THREAD

**Issue by mesidex** [sensepost/objection#624]
**Is your feature request related to a problem? Please describe.**
When running signed APK files on a rooted device, it is not possible to log in through Google. Many of the methods I've tried to solve this issue with ended up breaking the installation of the modified APK file. My target device is on Android 13

**Describe the solution you'd like**
I was wondering if it would be possible to, for example, add an argument like `--skip-signing` to prevent objection from signing the final APK.

**Describe alternatives you've considered**
I've tried things like copying the META-INF folder from the original APK file to the modified one, as well as disabling any kind of SSL pinning via [TrustMeAlready](https://github.com/ViRb3/TrustMeAlready).

**Additional context**
If there are any known solutions already, please let me know :)

**Comment by leonjza** [comment]
This is not an option that exists now, but is really easy to add. Essentially it will be a new flag to this command [here](https://github.com/sensepost/objection/blob/1.11.0/objection/console/cli.py#L351), flowing through to [here](https://github.com/sensepost/objection/blob/1.11.0/objection/commands/mobile_packages.py#L223) to skip that step.
