### ISSUE TITLE
Unable to connect to the frida server: target terminated with signal 9

### ISSUE THREAD

**Issue by pharazone** [sensepost/objection#627]
**Describe the bug**
I typed objection -g apk_name explore, frida-server is running with a magisk plugin. But here is a wrong message:
Unable to connect to the frida server: target terminated with signal 9

**Environment (please complete the following information):**
 - Device: pixel 5
 - OS: android 13
 - Frida Version 16.1.1 
- Objection Version 1.11.0

<img width="566" alt="image" src="https://github.com/sensepost/objection/assets/11215634/f935eabf-2472-417b-bb00-9eb611bf7c8b">

**Comment by IPMegladon** [comment]
Suspect this is not an objection-related issue. Have you tried attaching to the app using frida? e.g. `frida -U 20166`

**Comment by IPMegladon** [comment]
Closing issue as stale for now as it was created quite a while back, feel free to reopen.
