### ISSUE TITLE
[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by willbrow** [sensepost/objection#63]
Hi,
I am getting the below message and i am using kali linux has anyone else had this issue or know how to fix it please.Thanks 

Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog.

**Comment by leonjza** [comment]
A quick google shows [this thread](https://groups.google.com/forum/#!topic/apktool/fD8k6EKAEFQ). Can you try patch with the [`--decode-resources`](https://github.com/sensepost/objection/blob/master/objection/console/cli.py#L228) flag?

**Comment by willbrow** [comment]
Ive tried adding on --decode-resources but i still get the same error mate.

I am able to connect to device and open the patched app and also disable ssl pinning but the app keeps crashing

**Comment by leonjza** [comment]
Unfortunately I can not really suggest anything further from here, other than looking at the APK itself as well as adb logcat output to try and determine why the application crashes. It could be that the app has some anti-debugging logic or the patcher actually failed to name a few of many reasons why it be crashing.

**Comment by leonjza** [comment]
Had this same error recently as a result of not decoding the assets by default. I am going to inverse the default for this flag in the apk patcher soon.

**Comment by leonjza** [comment]
I flipped the default for this flag in 1.2.8 now.
