### ISSUE TITLE
App crashing on run

### ISSUE THREAD

**Issue by gitbugr** [sensepost/objection#64]
Run through patch, everything went smoothly. No errors, nice .apk... Until I run it on my device

"Linkedin keeps stopping" - closes automatically

App: LinkedIn (latest apk)
Device: Samsung Galaxy S7 Edge
Version: Android 7.0

Also tried with an older LinkedIn ipa build on iPhone 7 and wouldn't open there either. /:

**Comment by leonjza** [comment]
They might have anti-debugging/tampering tricks within the app. Did you check the output of `adb logcat` or the crash log from XCode for more information about why it crashes?

**Comment by leonjza** [comment]
Gave this a quick try and it seems to boot fine on my test device.

<img width="769" alt="screen shot 2018-03-24 at 09 25 58" src="https://user-images.githubusercontent.com/1148127/37861594-7d2aa626-2f45-11e8-9cf1-4f4f17367f9b.png">

**Comment by gitbugr** [comment]
Damn.. So, I pulled the build from my phone and patched it, and now it's working.
The first time, I'd downloaded it using a browser extension from the online Play Store... Very strange. I don't understand why that would be - but regardless, thank you for your help

**Comment by leonjza** [comment]
👍
