### ISSUE TITLE
I/O error unable to write directory

### ISSUE THREAD

**Issue by nsonaniya2010** [sensepost/objection#65]
frida

***
Failed to load the Frida native extension: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s)
to the Python egg cache:

  [Errno 5] Input/output error

The Python egg cache directory is currently set to:

  /root/.cache/Python-Eggs

Perhaps your account does not have write access to this directory?
You can change the cache directory by setting the PYTHON_EGG_CACHE
environment variable to point to an accessible directory.

Please ensure that the extension was compiled for Python 3.x.

**Comment by leonjza** [comment]
This looks like `frida` itself did not install properly, possibly because you not have write access to `/root/.cache/Python-Eggs`. Please check that you can successfully `pip3 install frida`. If you don't come right on your current platform then I suggest you try this is something like a Kali Linux VM or similar.

**Comment by nsonaniya2010** [comment]
When i typed command following o/p is there:
```
Requirement already satisfied: frida in /usr/local/lib/python3.6/dist-packages/frida-10.7.7-py3.6-linux-x86_64.egg
Requirement already satisfied: colorama>=0.2.7 in /usr/local/lib/python3.6/dist-packages (from frida)
Requirement already satisfied: prompt-toolkit>=0.57 in /usr/local/lib/python3.6/dist-packages/prompt_toolkit-1.0.15-py3.6.egg (from frida)
Requirement already satisfied: pygments>=2.0.2 in /usr/lib/python3/dist-packages (from frida)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt-toolkit>=0.57->frida)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages/wcwidth-0.1.7-py3.6.egg (from prompt-toolkit>=0.57->frida)
``

**Comment by nsonaniya2010** [comment]
Also, i have uninstalled and installed frida and objection again also i have given the full read write permission but i am getting same error.

**Comment by nsonaniya2010** [comment]
Also how can i ensure this `Please ensure that the extension was compiled for Python 3.x.` or how can i compile it in Python 3.X ?

**Comment by leonjza** [comment]
I am sorry, but unfortunately I am still unsure about what exactly is going wrong here for you. I suspect if the installation of Frida fails (like with your permissions issues) when the prebuilt extensions are [downloaded](https://github.com/frida/frida-python/blob/2a583e9b3072cbf7cf26fb97ccc2968f176af2fb/src/setup.py#L55) you can face similar issues to the ones you have now where it looks like Frida is installed, but in fact it is not.

The only thing I can suggest is you try and remove Frida & re-install, try this in a fresh VM or install in a new [virtual environment](https://virtualenv.pypa.io/en/stable/) like the [wiki](https://github.com/sensepost/objection/wiki/Installation#virtual-installation) suggests.
