### ISSUE TITLE
[bug] Unable to connect to the frida server: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use

### ISSUE THREAD

**Issue by nu0l** [sensepost/objection#650]
**Describe the bug**
As follows：
```
Using USB device `iPhone`
Unable to connect to the frida server: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
```

**To Reproduce**
1. Run command `objection -g com.xxxx.xxxx explore`

**Evidence / Logs / Screenshots**
<img width="1444" alt="image" src="https://github.com/sensepost/objection/assets/54735907/ff68598e-2310-4ad1-8eab-819727b12546">

**Environment (please complete the following information):**
 - Device: [e.g. iPhone se 2020]
 - OS: [e.g. iOS14.4.2]
 - Frida Version [e.g. 16.1.7]
- Objection Version [e.g. 1.11.0]

**Application**
If possible, please attach the target application where you can reproduce this bug to the issue.

**Additional context**
frida-server: Normal operation
<img width="680" alt="image" src="https://github.com/sensepost/objection/assets/54735907/d5262053-8b43-4744-9328-3d33f1bc8fb6">
`frida-ps -U -ai` : The command runs normally
<img width="651" alt="image" src="https://github.com/sensepost/objection/assets/54735907/cbbb9c88-0bbf-4863-9348-c964b62b441e">

**Comment by nu0l** [comment]
I found in issues649 that his Frida version and objection are the same as mine, so I don't think it's the Frida version of the problem #649

**Comment by IPMegladon** [comment]
Make sure your client version of frida is also the same as the server. Additionally I would recommend retrying this with the new frida version, I know there were some issues on iOS regarding this a while back so possible that it is fixed now.

**Comment by IPMegladon** [comment]
Closing issue as stale, feel free to reopen.
