### ISSUE TITLE
Concatenated AES Encryption Key

### ISSUE THREAD

**Issue by kpratik99** [sensepost/objection#655]
Hi,

While running an objection on an ios app, concatenated AES key is displayed:

length = 456, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000154

Any way around to print full encryption key?

**Comment by leonjza** [comment]
Going to need more info on the type, and how you got that output. In short, it will probably require you to write a custom hook (you can use objections hook generators to get you started fast) to dump what you need.

**Comment by IPMegladon** [comment]
Closing issue as stale, feel free to reopen.
