### ISSUE TITLE
Can't install objection, what's the problem?

### ISSUE THREAD

**Issue by jimckylin** [sensepost/objection#657]
install in terminal:

username@192 ~ % pip3 install objection
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: objection in ./Library/Python/3.9/lib/python/site-packages (1.11.0)
Requirement already satisfied: frida>=14.0.0 in ./Library/Python/3.9/lib/python/site-packages (from objection) (16.1.10)
Requirement already satisfied: frida-tools>=6.0.0 in /Library/Python/3.9/site-packages (from objection) (12.3.0)

username@192 ~ % objection
zsh: command not found: objection

**Comment by vivek-np** [comment]
same issue happening.

**Comment by IPMegladon** [comment]
Please provide more information on how to replicate this. This does not appear to be an objection issue but rather related to the python environment configuration.
