### ISSUE TITLE
patchapk zipalign error

### ISSUE THREAD

**Issue by user4584** [sensepost/objection#66]
Command: objection patchapk -s app.apk -a x86
Gadget version: 10.7.7
Zip align error: 

Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signed the new APK
Performing zipalign
Zipaligning the APK may have failed. Read the following output to determine if zipalign actually had an error: 

ERROR: unknown flag -p
Zip alignment utility
Copyright (C) 2009 The Android Open Source Project

Usage: zipalign [-f] [-v] <align> infile.zip outfile.zip
       zipalign -c [-v] <align> infile.zip

  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  -c: check alignment only (does not modify file)
  -f: overwrite existing outfile.zip
  -v: verbose output

Zipaling completed

**Comment by leonjza** [comment]
What is the output of `zipalign -h` for you?

I have:

```
$ zipalign -h
Zip alignment utility
Copyright (C) 2009 The Android Open Source Project

Usage: zipalign [-f] [-p] [-v] [-z] <align> infile.zip outfile.zip
       zipalign -c [-v] <align> infile.zip

  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  -c: check alignment only (does not modify file)
  -f: overwrite existing outfile.zip
  -p: page align stored shared object files
  -v: verbose output
  -z: recompress using Zopfli
```

**Comment by user4584** [comment]
Command to download zipalign: sudo apt-get install zipalign
Distro: Linux, Debian based
Output: 

Zip alignment utility
Copyright (C) 2009 The Android Open Source Project

Usage: zipalign [-f] [-v] <align> infile.zip outfile.zip
       zipalign -c [-v] <align> infile.zip

  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  -c: check alignment only (does not modify file)
  -f: overwrite existing outfile.zip
  -v: verbose output

You know another source for zipalign download, which could include -p, -z flags? 
Also, thank you for your help, it is much appreciated.

**Comment by user4584** [comment]
I manually downloaded zipalign and it works now!

**Comment by leonjza** [comment]
Apologies for the late reply, I am using whichever version Kali provides.

**Comment by user4584** [comment]
No worries, I downloaded zipalign on kali too, which did produce the -p flag, then manually installed it from kali to the other distro, which was giving me trouble. In case anyone runs into the same problem, hopefully they can do that too as a fix!
