### ISSUE TITLE
stuck when use `android hooking list classes` command

### ISSUE THREAD

**Issue by jacky1234** [sensepost/objection#665]
**Describe the bug**
When I use command `android hooking list classes`, it will stuck the whole thing. the terminate has nothing output.
And once I use the issue command `android hooking list classes`, other command will work unusually either.

Here is the video recorder:

https://github.com/sensepost/objection/assets/10626484/79e009da-4f3a-4ab6-bdc2-e591f84ee7da

**Environment (please complete the following information):**
 - Device: pixel 4
 - OS: android 13
 - Frida Version 16.2.1
- Objection Version : 1.11.0

Have anyone met the same issue, I would apprecate it if you help me.

**Comment by IPMegladon** [comment]
This issue does not appear to be in objection, but rather either in Frida or a detection mechanism of the app. Using `Java.enumerateLoadedClassesSync()` of Frida causes the same issue.
