### ISSUE TITLE
Objection throwing an error when launched

### ISSUE THREAD

**Issue by SHUBHAMD12** [sensepost/objection#672]
I have installed objection using pip3. but when i try to launch it it throws the following error. i have tried reinstalling but still getting the same issue.

![image](https://github.com/sensepost/objection/assets/43086690/31a75252-b1d1-4868-9387-001dc49daca5)

**Comment by adoyon23** [comment]
I was able to fix this issue by running `pip3 install setuptools` from [here](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources)

**Comment by SHUBHAMD12** [comment]
Thanks for your help @adoyon23

**Comment by SHUBHAMD12** [comment]
FIXED.

**Comment by singe** [comment]
In general, it's totally worth googling error messages before opening up an issue. For e.g. https://duckduckgo.com/?q=ModuleNotFoundError%3A+No+module+named+%27pkg_resources%27
