### ISSUE TITLE
Failure to unpack apk

### ISSUE THREAD

**Issue by ghost** [sensepost/objection#68]
![capture](https://user-images.githubusercontent.com/37070674/39187552-87b8670c-47c5-11e8-80ef-f1d8a434d07a.PNG)

This error keeps occuring when trying to unpack an apk, it seems that objection is looking for a randomised apk name but apktool generates an apk called 1.apk so objection can't find it.

![capture1](https://user-images.githubusercontent.com/37070674/39187632-bcfd67dc-47c5-11e8-81c9-18ec2159994b.PNG)

Don't know if something changed but this has only just started happening when I recently installed the latest version of objection.

Tested with apktool v2.3.2 and v2.3.1 still the same issue

**Comment by leonjza** [comment]
Hey, thanks for reporting this. Based on the exception in the screenshot, I think this is similar to #14 which relates to non-ascii characters in the APK's name.

Additionally, I noticed you are running this on Windows. FWIW, unfortunately Windows support for objection is a little flaky. Would be happy to get some help to improve that.

**Comment by ssp132** [comment]
Hi Leon, I've just started using Objection on Windows and find this very same issue with quite a few apks (not all of them though). I'm using version 2.3.4 of apktool. As this was first raised 2 years ago, I wondered if you know of a resolution at all? Thanks.

**Comment by leonjza** [comment]
Watch issue #309 which should help once it's landed.

**Comment by ssp132** [comment]
Thanks

**Comment by leonjza** [comment]
Closing this in favour of the conversation in the PR.
