### ISSUE TITLE
[bug] Tracking pc ip address

### ISSUE THREAD

**Issue by sn1ln** [sensepost/objection#680]
Hello, I wanted to ask you why the IP of the pc is being tracked.
When processing the application seeing this displays internet disconnection
Asus Z01QD Phone
Here are the screenshots https://imgur.com/a/79LktHe

**Comment by IPMegladon** [comment]
Please provide more details on the issue you are having. I do not see any error in the screenshot you provided. If you need further sslpinning bypass capability, you will likely have to write you own frida script for that.

**Comment by IPMegladon** [comment]
More information needed in order to be able to reproduce, closing as stale for now. Feel free to reopen if you can provide more details.
