### ISSUE TITLE
[bug] ios.keychain.remove/update is completed but not supported

### ISSUE THREAD

**Issue by AegeanYan** [sensepost/objection#683]
- Please, fill in all of the sections in this template.
- Please read each section carefully. Each has a description of what information will help.
- Windows support is limited. There is a good chance that a pull request would help!
- The more information you give, the better.
- Remove this section when you are done.

**Describe the bug**
I found that in objection/command/ios/keychain.py and agent/src/ios/keychain.ts, the function for keychain removing and updating is completed, but I could not call them in the objection. I've upgrade my objection.

**To Reproduce**
```text
ios keychain remove --account a --service b
```

**Similar issues**
Not found.

**Expected behavior**
Seems these two functions are not registered by somewhere. Hope someone could point out for me.

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
objection --debug explore
```

**Environment (please complete the following information):**
 - Device: [e.g. iPhoneXR]
 - OS: [e.g. iOS14.2]
 - Frida Version [e.g. 16.1.11]
- Objection Version [e.g. 1.11.0]

**Log**
Unknown or ambiguous command:

**Comment by leonjza** [comment]
We've not had a new release in a while and are working on it. For now, a build from source will give you the latest.

**Comment by AegeanYan** [comment]
Hi, I received these when I build with command `make test`
```text
AssertionError: 'Alias  Key   Certificate\n-----  ----  ---------[19 chars]ue\n' != 'Alias    Key    Certificate\n-------  -----  ---[30 chars]ue\n'
- Alias  Key   Certificate
+ Alias    Key    Certificate
?        ++   +
- -----  ----  -----------
?            ^^
+ -------  -----  -------------
?      ++      ^^^^^
- test   True  True
+ test     True   True
?        ++    +
```

Seems I need my own Key Certificate? But I don't know where to specific it.

**Comment by leonjza** [comment]
Expected, we haven't fixed any tests yet.

**Comment by AegeanYan** [comment]
Succeed with build.
Here is my snippet.
```text
cd agent
npm install
cd ..
make clean
make frida-agent
make sdist
cd dist
pip install xxx.tar.gz
```
