### ISSUE TITLE
It gets stuck when entering objection.

### ISSUE THREAD

**Issue by yunfenglaoshi** [sensepost/objection#685]
![image](https://github.com/sensepost/objection/assets/57252667/749db778-078d-4cbc-a914-39bf4e8e1c92)
When I try to enter the 'objection' mode, it gets stuck here. My phone already has root access, and I've noticed that it's been stuck here for a long time without any error messages appearing

**Comment by IPMegladon** [comment]
Recommend adding the debug flag (-d) to get more information. Also just make sure there is not a debugger or such attached to the application while using objection.
