### ISSUE TITLE
Cannot install Apple Sign

### ISSUE THREAD

**Issue by hoangnam714** [sensepost/objection#688]
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/7584a38d-f7bf-4a91-8615-09f45d42fedb">
Sorry but is anyone having the same error as me, I can't install apple sign because the file doesn't exist

**Comment by IPMegladon** [comment]
This issue is not related to Objection, you can look at 
https://goulet.dev/posts/node-dyld-library-not-loaded-icu4c/
to see if that resolves your issue.
