### ISSUE TITLE
Android SSL Pinning not working on Vesync App

### ISSUE THREAD

**Issue by Zahlii** [sensepost/objection#713]
I tried to remove the Vesync app's certificate pinning using objection to intercept my smart meter API calls, however the default approach for me did not work.

I had to manually decompile/modify/recompile with apktool. It seems the following methods did not hook properly (left jadx decompiled, right apktool disassembled and modified code to always return void with which it works). No idea if this can be easily ported to objection/frida.

```bash
vim ./smali_classes5/com/etekcity/vesyncplatform/util/g1.smali

=>>>

.class public final Lcom/etekcity/vesyncplatform/util/g1;
.super Ljava/lang/Object;
.source "SourceFile"
...
```

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/c5dab0d5-0365-4f45-a0cd-5b88742eb32a" />

**Comment by IPMegladon** [comment]
While adding this to objection would be fairly trivial, I don't believe the intention of objection is to be able to work for the myriad of different custom pinning implementations.
That said, I would recommend looking at writing small Frida scripts for cases like this.
In this example something like the following should do the equivalent:
```js
const clazz = Java.use("com.etekcity.vesyncplatform.util.g1");
// Hook the checkServerTrusted function and replace it with an empty function.
clazz.checkServerTrusted.implementation = function(chain, authType) {};
```
