### ISSUE TITLE
More precision in the documentation

### ISSUE THREAD

**Issue by gurkerl83** [sensepost/objection#8]
Hi, 
the documentation mentions the following note. 

"This is not some form of jailbreak/root bypass. By using objection, you are still limited by all of the restrictions imposed by the applicable sandbox you are facing."

It would be helpful to know what the application sandbox restrictions are in detail to determine what use cases are possible with Frida on a non-rooted device and which require a modification to the operating system. 

Thanks!

**Comment by leonjza** [comment]
Great idea thanks!

**Comment by leonjza** [comment]
I have created a [resources](https://github.com/sensepost/objection/wiki/Resources) wiki page with a collection of links that would hopefully help to clear up some questions.

In the case of your specific question, have a look at the [OWASP MSTG](https://github.com/OWASP/owasp-mstg) project. More specifically, the platform overviews for both [iOS](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06a-Platform-Overview.md) and [Android](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05a-Platform-Overview.md).
