### ISSUE TITLE
Connect to PID instead of Gadget

### ISSUE THREAD

**Issue by ninoz** [sensepost/objection#82]
Hi have an application which is doing some funky anti debugging and forking child processes.  The application name does not appear in PS but I do have the PID.  Is it possible to get objection to connect based on PID opposed to the name?

Thanks

**Comment by leonjza** [comment]
This is only doable in a jailbroken environment. If you have `frida-server` running you can specify the PID with the `-g` flag.

**Comment by ninoz** [comment]
Ah I thought I had tried that!  Working now!  Thanks for your work on this project :)

**Comment by vangivang** [comment]
Hi from 2021. Ahh that actually was extremely helpful thanks for the question and the answer.
I hit the same issue as well. I do not see the expected package name but I got the pid.
Using a rooted device. Both frida -U -p [pid] and objection -g [pid] worked in this case.
