### ISSUE TITLE
Feature Request: APK Job Embedding

### ISSUE THREAD

**Issue by Oshawk** [sensepost/objection#84]
I am aware that this is likley a VERY large request but I feel, were it implemented, this would make objection truly one-of-a-kind.

My idea would be to allow startup jobs to be specified whilst patching an APK that would be ran when the app is opened. This would allow the app to function fully autonomously without the need for a connection to a computer.

This would be especially useful for the sslpinning job as I don't think there is a tool out there that offers this capability to be fully automated.

Frida [does allow](https://www.frida.re/docs/gadget/#script) a gadget to execute a script / scripts instead of waiting for a connection however am aware that a lot is done on the side of the PC, not Android device.

Again, I am aware of the magnitude of this request and would be shocked if it were to be implemented any time soon but I and i'm sure many other people would be glad if it were to be in the future.

Thanks,
Joseph.

**Comment by leonjza** [comment]
Hey! Thanks for the suggestion. Is is definitely something I have wanted to play with and add since the release of the feature allowing the gadget to pickup scripts from the filesystem.

Soon :)

**Comment by Oshawk** [comment]
Great! I am looking forward to developments.

**Comment by leonjza** [comment]
Just an iOS specific note. It wont be possible to do the SSL pinning bypasses on iOS without the app being launched with a debugger attached to relax the code signing requirements. The `Interceptor` API is not available when codesigning is `required`.

**Comment by Techbrunch** [comment]
Looks like this issue has been solved (for Android at least) with the 1.9.0 release.

Check the pull request for an example: https://github.com/sensepost/objection/pull/329

**Comment by leonjza** [comment]
This will be possible for iOS in the next release as well thanks to #349.
