### ISSUE TITLE
Pass true or false as an argument of  "ios ui touchid_bypass"

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#86]
Can i pass false to "ios ui touchid_bypass" and when user give Touchid on device and  that time false, Instead of all time pass.

**Comment by leonjza** [comment]
Hey,

The command does [not accept arguments](https://github.com/sensepost/objection/blob/master/objection/console/helpfiles/ios.ui.touchid_bypass.txt) to pass on to the [hook](https://github.com/sensepost/objection/blob/master/objection/hooks/ios/ui/touchid.js) no. To disable the bypass, you can stop the job that gets started when you run `ios ui touchid_bypass` with [`jobs kill <job_id>`](https://github.com/sensepost/objection/blob/master/objection/console/helpfiles/jobs.kill.txt) after getting the `job_id` with [`jobs list`](https://github.com/sensepost/objection/blob/master/objection/console/helpfiles/jobs.list.txt). This will restore the behaviour as originally intended by the application.

HTH
