### ISSUE TITLE
Build Objection on mac and install Locally

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#87]
Hi, 
I wanted to add some things in this project and want to see the changes 
How can i do that?

Please help me.

**Comment by leonjza** [comment]
Awesome! Getting a development environment up to hack away at objection is pretty simple. All you need to do is clone your fork from Github and install it using `pip`. For example:

- Fork the repository on Github
- Clone it somewhere on disk like at `~/code/objection`
- Create a new python3 virtual environment with something like `virtualenv -p python3 ~/code/venv3`
- Activate the new virtual environment with `source ~/code/venv3/bin/activate`
- `cd` to your fork at `~/code/objection` and install it with `pip install --editable .`

Now, any changes you make will be immediately applied without the need for another install.

Have fun!
