### ISSUE TITLE
Undocumented Windows Dependencies

### ISSUE THREAD

**Issue by FlavSec** [sensepost/objection#9]
Hi,

The 'installation' prereqs section on the wiki lists 'python version 3.3+' as the only real prerequisite.

However, it appears that objection/utils/packages.py expects 'which' to be available on the local system in order to locate all of the Android dependencies (aapt, apktool, etc).

It's possible to use objection on Windows by commenting out the dependency-checking section and manually specifying each tool's location, or by installing an environment that provides 'which'. It may be worth stating this explicitly in the documentation so Windows users with unmodified command-line environments will be able to figure out what they're missing.

**Comment by leonjza** [comment]
Thanks for the report!

Admittedly, I never really tested this in a Windows environment, but I would be more than happy for a PR that updates the dependency checker for the Android patching command to support Windows installations (unless I get around to testing it out myself).

**Comment by FlavSec** [comment]
Added a PR with shutil.which() - I've noticed that this causes issues with paths containing spaces in delegator.run(). I'll open a separate PR for that fix if I have a chance to look at it tonight.

**Comment by leonjza** [comment]
Thanks! Merged #10. Will keep this open until there is more clarity on the spaces issue you mentioned.

**Comment by FlavSec** [comment]
So here's what I've got on the spaces issue:

You can pass subprocess.Popen() either a single string containing the entire command and options ( "ls -al /etc" ) or you can pass the command and every option as a list ( ['ls', '-al', '/etc'] ). The list method is preferred because it is resilient to spaces or other field separators in options and command paths. For example, subprocess.Popen("c:\program files\java\jdk1.8\bin\jarsigner.exe -verify c:\path\to\apk") will not work, because the space in "Program Files" isn't automagically escaped.

I thought the solution to this was to re-write all of the delegator.run() calls to be list-based calls instead of string-based calls. This works on Windows! Yay! Unfortunately, it doesn't work on Mac or Linux hosts that I tested. Digging further, I found that Delegator explicitly sets the 'Shell' flag from subprocess.Popen() to 'True'. Having this set to 'True' while also passing in a list-based command string apparently results in ambiguous, undefined behavior on a non-Windows OS- in our use case, subprocess.Popen() was interpreting the very first list argument as the entire command string, which obviously wouldn't work.

I was able to get Mac and Linux calls working by manually setting Shell='False' for the subprocess.Popen() call - this is recommended best practice, I believe, because Shell='True' allows shell metacharacters to be interpreted. Unfortunately, I hit another snag here - Delegator doesn't seem to allow you to explicitly set the Shell=False flag for its subprocess.Popen() calls, it sets it to 'True' and doesn't expose any way of changing that property.

For now, I worked up a quick re-write that uses subprocess.Popen() manually - this works on all three operating systems with python 3.3+. However, it's not as pretty or convenient as having all the helper methods that Delegator provides. If you think it makes sense, I could write up a really light Delegator-esque helper class in helpers.py that exposes much of the functionality that this project was using from Delegator (mostly stdout and stderr reading).

What do you think? Worth rewriting to tear out Delegator? Or should I look for some work-around that keeps Delegator in the project? Maybe a PR to their project that allows manually setting of the 'Shell' argument to subprocess.Popen()?

**Comment by FlavSec** [comment]
I'm dumb. Using shlex.quote() should address all of my issues - I'll submit a PR once I test it on all three platforms. I still feel a bit uneasy about not being able to explicitly use 'shell=False' in Delegator, but this should be a much more elegant fix.

**Comment by leonjza** [comment]
Thanks for looking into this! :) I think for now if we can get away with `quote()` solving the spacing issues it would be super. As for the `shell=True` part, maybe its worth working with the upstream repo and getting that added?

**Comment by FlavSec** [comment]
This should all be addressed by PR #13

**Comment by leonjza** [comment]
Thank you @FlavSec. This should now be part of v1.0.4 just released.
