### ISSUE TITLE
Objection Installation

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#91]
Hi,

When i am trying to install objection

pip3 install -U objection

This is throwing some error

i m using python3 version 

$ python3 -V
Python 3.6.5
$ pip3 -V
pip 9.0.3 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (python 3.6)

Error

**Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rv/cz39gybd7px4d_t18h91682m0000gn/T/pip-build-41cc7g2p/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rv/cz39gybd7px4d_t18h91682m0000gn/T/pip-ajv2o56g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rv/cz39gybd7px4d_t18h91682m0000gn/T/pip-build-41cc7g2p/frida/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.**

Please Help me !

**Comment by leonjza** [comment]
This looks like frida failed to install. You can try and install it separately to try and debug why it failed with `pip install frida --upgrade`.

**Comment by jemshit** [comment]
This error is related to frida. I assume objection uses uses it. There is problem with SSL certificate of frida host whatever, so the full error is 
```
running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/frida
    copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/frida
    copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.6/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/android/frida-12.3.1-py3.6-macosx-10.6-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
    
    ----------------------------------------
Command "/Users/android/Documents/fridaa/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/1b/41j0g7w52tncfkfkc775346r0000gn/T/pip-install-138g_kim/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/1b/41j0g7w52tncfkfkc775346r0000gn/T/pip-record-bvcvtdn8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/android/Documents/fridaa/venv/bin/../include/site/python3.6/frida" failed with error code 1 in /private/var/folders/1b/41j0g7w52tncfkfkc775346r0000gn/T/pip-install-138g_kim/frida/
```
To solve (and also to install frida on mac), you can [download](https://pypi.org/project/frida/12.3.1/#files) and save file to `/Users/youUserName/frida-12.3.1-py3.6-macosx-10.6-intel.egg`, then run the installation command of objection again which fixes problem.
