### ISSUE TITLE
Failed to load the Frida native extension: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by megapro17** [sensepost/objection#94]
```
objection patchapk -s .\myapp.apk

***
Failed to load the Frida native extension: DLL load failed: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.3.0', 'console_scripts', 'objection')()
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\program files\python37\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files\python37\lib\site-packages\objection\console\cli.py", line 2, in <module>
    import frida
  File "c:\program files\python37\lib\site-packages\frida\__init__.py", line 26, in <module>
    raise ex
  File "c:\program files\python37\lib\site-packages\frida\__init__.py", line 6, in <module>
    import _frida
ImportError: DLL load failed: The specified module could not be found.
```

Windows 10 1803, Python 3.7.0b5 x64

**Comment by leonjza** [comment]
Looks like installing Python 3.6 solves this issue on Windows. I am not 100% sure why 3.7 causes this, unfortunately.

**Comment by lintangtimur** [comment]
same like me
Windows 10
Python 36

DLL load failed: The specified module could not be found

**Comment by cpholguera** [comment]
Hi, I know from Ole that the new binaries were compiled for Python 3.7. I had the same problem on Windows 10 Python 3.6 and just upgraded it to the latest 3.7. After that everything was fine. Be sure that any previous installation of frida is not there anymore.

I hope this helps you :)

**Comment by lintangtimur** [comment]
@cpholguera thanks, installing python 3.7 and its working

**Comment by cpholguera** [comment]
That's great. You're very welcome!

**Comment by ericsia** [comment]
python 3.8 not working

**Comment by leonjza** [comment]
I just added Python 3.8 to Travis [here](https://github.com/sensepost/objection/commit/a3f809b8768731d07c2fd6000cd42cb78c5a2b8b), and the builds seem to pass? https://travis-ci.org/sensepost/objection/jobs/599164510

**Comment by gipvavo** [comment]
same here, frida not working with same error message when using python3.8 on Windows 10

**Comment by pabx06** [comment]
> I just added Python 3.8 to Travis [here](https://github.com/sensepost/objection/commit/a3f809b8768731d07c2fd6000cd42cb78c5a2b8b), and the builds seem to pass? https://travis-ci.org/sensepost/objection/jobs/599164510

you only checking the installation process . with works. but dll doesn't get load when trying some python with 'import frida'

**Comment by pabx06** [comment]
> same here, frida not working with same error message when using python3.8 on Windows 10

same thing here . also tried 3.6, 3.7 3.8  x86 & x64 bins ... the one that worked for me was : ``Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32``

**Comment by leonjza** [comment]
Please see https://github.com/frida/frida/issues/1057 for Windows 3.8 support. This is not an objection issue.

**Comment by ehearns** [comment]
The problem seems to exist across all versions of python from 3.6 to 3.75.  Anyone has a fix?  I'm dying to get this to work.

Ed

**Comment by leonjza** [comment]
This is a Frida issue. You need to be able to install that and run the frida command line utilities from the `frida-tools` python package.
