### ISSUE TITLE
Significance of         **self.device_serial = None**  Statement

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#95]
class StateConnection(object):
    """ A class controlling the connection state of a device. """

    TYPE_USB = 0
    TYPE_REMOTE = 1

    def __init__(self) -> None:
        """
            Init a new connection state, defaulting to a USB
            connection.
        """

        self.usb = True
        self.network = False
        self.host = '127.0.0.1'
        self.port = 27042
        self._type = self.TYPE_USB
        **self.device_serial = None**

What is significance of this  device_serial in this class and why this is none

Thanks

Bikee Bihari

**Comment by leonjza** [comment]
This is the default value for the device state. Added as part of https://github.com/sensepost/objection/commit/b886387ae1314be69900fdec0f509b2e4cacb425.
