### ISSUE TITLE
ios app crashed 

### ISSUE THREAD

**Issue by amagdaraog** [sensepost/objection#97]
When I try the App on different machine (but same ipad) it works fine, what am I missing?
Using objection latest on both machines.

> Incident Identifier: DB10C91F-9978-42A6-A8A2-B4422A3BF343
CrashReporter Key:   2f9597763eea8fc6b9db21cc06f9eddc91461d61
Hardware Model:      iPad7,5
Process:             iPhone [2729]
Path:                /private/var/containers/Bundle/Application/E4B9D3B2-A57A-4D94-A319-0ED88246DBC0/iPhone.app/iPhone
Identifier:          
Version:             5.0.1 (5.0.1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           
Date/Time:           2018-06-27 15:23:49.6877 +0800
Launch Time:         2018-06-27 15:23:35.0893 +0800
OS Version:          iPhone OS 11.3 (15E216)
Baseband Version:    n/a
Report Version:      104
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0
Application Specific Information:
abort() called
Filtered syslog:
None found

**Comment by leonjza** [comment]
Its really hard to tell. I would suggest inspecting any stack traces you may have in the device logs view for more information.

**Comment by amagdaraog** [comment]
When the app doesn't have any SSL pinning, it works fine, but when it does, it crashes or doesn't work even if has `ios sslpinning disable` command.

**Comment by leonjza** [comment]
Even in this case there is literally nothing for me to go by here. I suggest investigating stack traces, reading log files and doing some research on the errors you see to figure out whats going it. Might even learn a trick or two along the way :)

**Comment by amagdaraog** [comment]
Will keep you posted if I found some relevant info, thanks for the hard work man!
